import { Estimation, EstimationFormData, AvmResult, EnvoiInfo } from '../types';
import { computeAvm } from '../utils/avmEngine';

function mkBien(overrides: Partial<EstimationFormData>): EstimationFormData {
  return {
    adresse: '',
    ville: '',
    code_postal: '',
    lat: 0,
    lon: 0,
    type_bien: 'appartement',
    surface: 0,
    nb_pieces: 0,
    nb_chambres: 0,
    etage: 0,
    nb_etages: 0,
    surface_terrain: 0,
    annee_construction: 0,
    dpe: 'D',
    ges: 'D',
    etat: 'bon',
    exposition: '',
    caracteristiques: [],
    description: '',
    points_forts: [],
    points_defendre: [],
    charges_mensuelles: 0,
    taxe_fonciere: 0,
    ...overrides,
  };
}

function mkAvm(data: EstimationFormData): AvmResult {
  return computeAvm(data) || {
    prix: { estimation: 0, fourchette_basse: 0, fourchette_haute: 0, prix_m2: 0, confiance: 0.5, confiance_label: 'faible' },
    loyer: { estimation: 0, fourchette_basse: 0, fourchette_haute: 0, loyer_m2: 0, rendement_brut: 0 },
    ajustements: [],
    comparables: [],
    marche_reference: { prix_m2_bas: 0, prix_m2_median: 0, prix_m2_haut: 0, ecart_vs_marche_pct: 0 },
  };
}

function mkEnvoi(
  envoyeLe: string,
  email: string,
  nom: string,
  ouvertures: Array<{ jours_apres: number; device: 'mobile' | 'desktop' | 'tablette' }> = [],
): EnvoiInfo {
  const envoyeLeDate = new Date(envoyeLe);
  const ouverturesEvents = ouvertures.map(o => {
    const d = new Date(envoyeLeDate);
    d.setDate(d.getDate() + o.jours_apres);
    return { date: d.toISOString(), user_agent: o.device };
  });
  return {
    envoye_le: envoyeLe,
    email_destinataire: email,
    nom_destinataire: nom,
    objet: `Votre avis de valeur`,
    message: 'Bonjour, veuillez trouver ci-joint l\'avis de valeur pour le bien évalué.',
    ouvertures: ouverturesEvents,
    derniere_ouverture: ouverturesEvents.length ? ouverturesEvents[ouverturesEvents.length - 1].date : undefined,
    token_public: Math.random().toString(36).substring(2, 14),
  };
}

export const MOCK_AVIS_VALEUR: Estimation[] = [
  // === 5 BROUILLONS ===
  {
    id: 'adv_001',
    type: 'avis_valeur',
    statut: 'brouillon',
    source: 'estimation_rapide',
    parent_estimation_id: 'est_001',
    version: 1,
    created_at: '2026-04-22T09:00:00Z',
    updated_at: '2026-04-22T10:30:00Z',
    auteur: 'Sophie Leroy',
    client: { civilite: 'M.', nom: 'Prévost', prenom: 'Thomas', email: 'thomas.prevost@gmail.com', telephone: '06 12 34 56 78' },
    bien: mkBien({
      adresse: '16 rue du Hameau', ville: 'Paris', code_postal: '75015',
      lat: 48.8323, lon: 2.2893, surface: 42, nb_pieces: 2, nb_chambres: 1, etage: 2, nb_etages: 7,
      annee_construction: 1960, dpe: 'E', ges: 'E', etat: 'a_rafraichir', exposition: 'Sud',
      caracteristiques: ['balcon', 'cave', 'ascenseur'], charges_mensuelles: 180, taxe_fonciere: 1200,
    }),
    avm: mkAvm(mkBien({ adresse: '16 rue du Hameau', ville: 'Paris', code_postal: '75015', surface: 42, nb_pieces: 2, etat: 'a_rafraichir', dpe: 'E', caracteristiques: ['balcon', 'cave', 'ascenseur'], type_bien: 'appartement' })),
    valeur_retenue: null,
    photo_url: 'https://picsum.photos/seed/adv001/800/600',
  },
  {
    id: 'adv_002',
    type: 'avis_valeur',
    statut: 'brouillon',
    source: 'bien_portefeuille',
    version: 1,
    created_at: '2026-04-21T14:20:00Z',
    updated_at: '2026-04-22T08:45:00Z',
    auteur: 'Sophie Leroy',
    client: { civilite: 'Mme', nom: 'Moreau', prenom: 'Claire', email: 'claire.moreau@gmail.com', telephone: '06 11 22 33 44' },
    bien: mkBien({
      adresse: '22 quai de Saône', ville: 'Lyon', code_postal: '69001', lat: 45.7640, lon: 4.8272,
      surface: 90, nb_pieces: 4, nb_chambres: 3, etage: 3, nb_etages: 5,
      annee_construction: 2005, dpe: 'B', ges: 'B', etat: 'bon', exposition: 'Ouest',
      caracteristiques: ['balcon', 'parking', 'cave', 'ascenseur'],
      points_forts: ['Vue fleuve', 'DPE B', 'Parking'],
      charges_mensuelles: 350, taxe_fonciere: 1600,
    }),
    avm: mkAvm(mkBien({ adresse: '22 quai de Saône', ville: 'Lyon', code_postal: '69001', surface: 90, nb_pieces: 4, etat: 'bon', dpe: 'B', caracteristiques: ['balcon', 'parking'], type_bien: 'appartement' })),
    valeur_retenue: null,
    photo_url: 'https://picsum.photos/seed/adv002/800/600',
  },
  {
    id: 'adv_003',
    type: 'avis_valeur',
    statut: 'brouillon',
    source: 'manuel',
    version: 1,
    created_at: '2026-04-20T11:00:00Z',
    updated_at: '2026-04-21T16:10:00Z',
    auteur: 'Jean Dubois',
    client: { civilite: 'M.', nom: 'Blanc', prenom: 'Antoine', email: 'antoine.blanc@proton.me', telephone: '06 55 66 77 88' },
    bien: mkBien({
      adresse: '14 cours du Médoc', ville: 'Bordeaux', code_postal: '33300', lat: 44.8588, lon: -0.5746,
      surface: 35, nb_pieces: 2, nb_chambres: 1, etage: 0, nb_etages: 3,
      annee_construction: 1990, dpe: 'D', ges: 'D', etat: 'bon', exposition: 'Sud',
      caracteristiques: ['terrasse'], points_forts: ['Terrasse', 'Rez-de-chaussée jardin'],
      charges_mensuelles: 90, taxe_fonciere: 480,
    }),
    avm: mkAvm(mkBien({ adresse: '14 cours du Médoc', ville: 'Bordeaux', code_postal: '33300', surface: 35, nb_pieces: 2, etat: 'bon', dpe: 'D', caracteristiques: ['terrasse'], type_bien: 'appartement' })),
    valeur_retenue: null,
    photo_url: 'https://picsum.photos/seed/adv003/800/600',
  },
  {
    id: 'adv_004',
    type: 'avis_valeur',
    statut: 'brouillon',
    source: 'annonce_url',
    version: 1,
    created_at: '2026-04-19T13:00:00Z',
    updated_at: '2026-04-19T13:45:00Z',
    auteur: 'Marc Dupont',
    client: { civilite: 'Mme', nom: 'Laurent', prenom: 'Émilie', email: 'e.laurent@gmail.com', telephone: '07 99 88 77 66' },
    bien: mkBien({
      adresse: '3 rue Pasteur', ville: 'Lyon', code_postal: '69007', lat: 45.7470, lon: 4.8390,
      surface: 58, nb_pieces: 3, nb_chambres: 2, etage: 1, nb_etages: 4,
      annee_construction: 1978, dpe: 'D', ges: 'D', etat: 'bon', exposition: 'Est',
      caracteristiques: ['cave'], charges_mensuelles: 130, taxe_fonciere: 820,
    }),
    avm: mkAvm(mkBien({ adresse: '3 rue Pasteur', ville: 'Lyon', code_postal: '69007', surface: 58, nb_pieces: 3, etat: 'bon', dpe: 'D', type_bien: 'appartement' })),
    valeur_retenue: null,
    photo_url: 'https://picsum.photos/seed/adv004/800/600',
  },
  {
    id: 'adv_005',
    type: 'avis_valeur',
    statut: 'brouillon',
    source: 'estimation_rapide',
    parent_estimation_id: 'est_005',
    version: 1,
    created_at: '2026-04-18T15:00:00Z',
    updated_at: '2026-04-21T10:00:00Z',
    auteur: 'Sophie Leroy',
    client: { civilite: 'Mme', nom: 'Bernard', prenom: 'Hélène', email: 'h.bernard@yahoo.fr', telephone: '06 22 33 44 55' },
    bien: mkBien({
      adresse: '5 impasse des Lilas', ville: 'Lyon', code_postal: '69006', lat: 45.7698, lon: 4.8502,
      surface: 150, nb_pieces: 6, nb_chambres: 4, etage: 0, nb_etages: 2,
      surface_terrain: 600, annee_construction: 1965, dpe: 'G', ges: 'G', etat: 'a_restructurer',
      exposition: 'Sud', caracteristiques: ['jardin', 'cave'], type_bien: 'maison',
      charges_mensuelles: 0, taxe_fonciere: 3200,
    }),
    avm: mkAvm(mkBien({ adresse: '5 impasse des Lilas', ville: 'Lyon', code_postal: '69006', surface: 150, nb_pieces: 6, etat: 'a_restructurer', dpe: 'G', caracteristiques: ['jardin'], type_bien: 'maison' })),
    valeur_retenue: null,
    photo_url: 'https://picsum.photos/seed/adv005/800/600',
  },

  // === 3 FINALISÉES (prix retenus, honoraires configurés, non envoyées) ===
  {
    id: 'adv_006',
    type: 'avis_valeur',
    statut: 'finalisee',
    source: 'estimation_rapide',
    parent_estimation_id: 'est_003',
    version: 1,
    created_at: '2026-04-17T10:00:00Z',
    updated_at: '2026-04-18T14:00:00Z',
    auteur: 'Sophie Leroy',
    client: { civilite: 'Mme', nom: 'Fontaine', prenom: 'Isabelle', email: 'i.fontaine@outlook.fr', telephone: '07 65 43 21 09' },
    bien: mkBien({
      adresse: '8 allée des Roses', ville: 'Bordeaux', code_postal: '33000', lat: 44.8378, lon: -0.5792,
      surface: 130, nb_pieces: 5, nb_chambres: 3, etage: 0, nb_etages: 2,
      surface_terrain: 400, annee_construction: 1972, dpe: 'D', ges: 'D', etat: 'bon',
      exposition: 'Sud-Ouest', caracteristiques: ['jardin', 'parking', 'cave'], type_bien: 'maison',
      description: 'Belle maison de ville avec jardin arboré',
      points_forts: ['Jardin 400m²', 'Quartier calme', 'Double garage'],
      points_defendre: ['DPE à améliorer'],
      charges_mensuelles: 0, taxe_fonciere: 2100,
    }),
    avm: mkAvm(mkBien({ adresse: '8 allée des Roses', ville: 'Bordeaux', code_postal: '33000', surface: 130, nb_pieces: 5, etat: 'bon', dpe: 'D', caracteristiques: ['jardin', 'parking'], type_bien: 'maison' })),
    valeur_retenue: 624000,
    valeur_retenue_detail: { prix: 624000, honoraires_pct: 5, charge_honoraires: 'acquereur' },
    photo_url: 'https://picsum.photos/seed/adv006/800/600',
  },
  {
    id: 'adv_007',
    type: 'avis_valeur',
    statut: 'finalisee',
    source: 'estimation_rapide',
    parent_estimation_id: 'est_008',
    version: 1,
    created_at: '2026-04-15T09:00:00Z',
    updated_at: '2026-04-16T11:30:00Z',
    auteur: 'Sophie Leroy',
    client: { civilite: 'M.', nom: 'Simon', prenom: 'Benoît', email: 'benoit.simon@icloud.com', telephone: '06 33 44 55 66' },
    bien: mkBien({
      adresse: '88 avenue Haussmann', ville: 'Paris', code_postal: '75008', lat: 48.8746, lon: 2.3132,
      surface: 120, nb_pieces: 5, nb_chambres: 3, etage: 6, nb_etages: 7,
      annee_construction: 1885, dpe: 'D', ges: 'D', etat: 'refait_a_neuf', exposition: 'Sud-Est',
      caracteristiques: ['ascenseur', 'gardien', 'cave', 'balcon'],
      description: 'Haussmannien rénové, vue dégagée',
      points_forts: ['Haussmannien', 'Gardien', 'Dernier étage partiel', 'Vue'],
      points_defendre: ['Charges copro élevées'],
      charges_mensuelles: 750, taxe_fonciere: 4800,
    }),
    avm: mkAvm(mkBien({ adresse: '88 avenue Haussmann', ville: 'Paris', code_postal: '75008', surface: 120, nb_pieces: 5, etat: 'refait_a_neuf', dpe: 'D', caracteristiques: ['ascenseur', 'balcon'], type_bien: 'appartement' })),
    valeur_retenue: 1720000,
    valeur_retenue_detail: { prix: 1720000, honoraires_pct: 4, charge_honoraires: 'acquereur' },
    photo_url: 'https://picsum.photos/seed/adv007/800/600',
  },
  {
    id: 'adv_008',
    type: 'avis_valeur',
    statut: 'finalisee',
    source: 'manuel',
    version: 1,
    created_at: '2026-04-13T10:30:00Z',
    updated_at: '2026-04-14T16:00:00Z',
    auteur: 'Jean Dubois',
    client: { civilite: 'M.', nom: 'Garcia', prenom: 'Philippe', email: 'p.garcia@sfr.fr', telephone: '06 88 99 00 11' },
    bien: mkBien({
      adresse: '12 rue Ste-Catherine', ville: 'Bordeaux', code_postal: '33000', lat: 44.8378, lon: -0.5727,
      surface: 85, nb_pieces: 4, nb_chambres: 2, etage: 2, nb_etages: 5,
      annee_construction: 1890, dpe: 'C', ges: 'C', etat: 'bon', exposition: 'Sud',
      caracteristiques: ['balcon', 'cave'], points_forts: ['Hyper-centre', 'Hauts plafonds'],
      charges_mensuelles: 220, taxe_fonciere: 1250,
    }),
    avm: mkAvm(mkBien({ adresse: '12 rue Ste-Catherine', ville: 'Bordeaux', code_postal: '33000', surface: 85, nb_pieces: 4, etat: 'bon', dpe: 'C', caracteristiques: ['balcon'], type_bien: 'appartement' })),
    valeur_retenue: 418000,
    valeur_retenue_detail: { prix: 418000, honoraires_pct: 5, charge_honoraires: 'acquereur' },
    photo_url: 'https://picsum.photos/seed/adv008/800/600',
  },

  // === 3 ENVOYÉES NON OUVERTES ===
  {
    id: 'adv_009',
    type: 'avis_valeur',
    statut: 'envoyee',
    source: 'estimation_rapide',
    parent_estimation_id: 'est_012',
    version: 1,
    created_at: '2026-04-10T09:00:00Z',
    updated_at: '2026-04-12T10:00:00Z',
    auteur: 'Jean Dubois',
    client: { civilite: 'Mme', nom: 'Rousseau', prenom: 'Nathalie', email: 'n.rousseau@gmail.com', telephone: '06 44 55 66 77' },
    bien: mkBien({
      adresse: '18 avenue Jean Jaurès', ville: 'Bordeaux', code_postal: '33000', lat: 44.8405, lon: -0.5690,
      surface: 75, nb_pieces: 4, nb_chambres: 2, etage: 2, nb_etages: 4,
      annee_construction: 2015, dpe: 'A', ges: 'A', etat: 'neuf', exposition: 'Sud-Ouest',
      caracteristiques: ['balcon', 'terrasse', 'parking', 'ascenseur'],
      points_forts: ['DPE A', 'Terrasse 20m²', 'Neuf BBC', 'Parking'],
      charges_mensuelles: 280, taxe_fonciere: 1100,
    }),
    avm: mkAvm(mkBien({ adresse: '18 avenue Jean Jaurès', ville: 'Bordeaux', code_postal: '33000', surface: 75, nb_pieces: 4, etat: 'neuf', dpe: 'A', caracteristiques: ['balcon', 'terrasse', 'parking'], type_bien: 'appartement' })),
    valeur_retenue: 435000,
    valeur_retenue_detail: { prix: 435000, honoraires_pct: 5, charge_honoraires: 'acquereur' },
    envoi: mkEnvoi('2026-04-12T10:00:00Z', 'n.rousseau@gmail.com', 'Mme Nathalie Rousseau'),
    photo_url: 'https://picsum.photos/seed/adv009/800/600',
  },
  {
    id: 'adv_010',
    type: 'avis_valeur',
    statut: 'envoyee',
    source: 'manuel',
    version: 1,
    created_at: '2026-04-08T14:00:00Z',
    updated_at: '2026-04-09T11:00:00Z',
    auteur: 'Sophie Leroy',
    client: { civilite: 'M.', nom: 'Martin', prenom: 'David', email: 'david.martin@wanadoo.fr', telephone: '06 67 89 01 23' },
    bien: mkBien({
      adresse: '7 rue Vaugirard', ville: 'Paris', code_postal: '75006', lat: 48.8482, lon: 2.3395,
      surface: 62, nb_pieces: 3, nb_chambres: 2, etage: 3, nb_etages: 6,
      annee_construction: 1925, dpe: 'E', ges: 'E', etat: 'bon', exposition: 'Sud',
      caracteristiques: ['cave', 'ascenseur'],
      charges_mensuelles: 320, taxe_fonciere: 1850,
    }),
    avm: mkAvm(mkBien({ adresse: '7 rue Vaugirard', ville: 'Paris', code_postal: '75006', surface: 62, nb_pieces: 3, etat: 'bon', dpe: 'E', caracteristiques: ['ascenseur'], type_bien: 'appartement' })),
    valeur_retenue: 920000,
    valeur_retenue_detail: { prix: 920000, honoraires_pct: 5, charge_honoraires: 'acquereur' },
    envoi: mkEnvoi('2026-04-09T11:00:00Z', 'david.martin@wanadoo.fr', 'M. David Martin'),
    photo_url: 'https://picsum.photos/seed/adv010/800/600',
  },
  {
    id: 'adv_011',
    type: 'avis_valeur',
    statut: 'envoyee',
    source: 'estimation_rapide',
    parent_estimation_id: 'est_007',
    version: 1,
    created_at: '2026-04-05T16:00:00Z',
    updated_at: '2026-04-07T09:15:00Z',
    auteur: 'Marc Dupont',
    client: { civilite: 'Mme', nom: 'Perrin', prenom: 'Christine', email: 'c.perrin@orange.fr', telephone: '07 12 23 34 45' },
    bien: mkBien({
      adresse: '25 boulevard des Belges', ville: 'Lyon', code_postal: '69006', lat: 45.7712, lon: 4.8492,
      surface: 110, nb_pieces: 5, nb_chambres: 3, etage: 4, nb_etages: 6,
      annee_construction: 1930, dpe: 'D', ges: 'D', etat: 'bon', exposition: 'Sud-Est',
      caracteristiques: ['balcon', 'cave', 'ascenseur', 'gardien'],
      points_forts: ['Quartier prestigieux', 'Balcon traversant'],
      charges_mensuelles: 450, taxe_fonciere: 2100,
    }),
    avm: mkAvm(mkBien({ adresse: '25 boulevard des Belges', ville: 'Lyon', code_postal: '69006', surface: 110, nb_pieces: 5, etat: 'bon', dpe: 'D', caracteristiques: ['balcon', 'ascenseur'], type_bien: 'appartement' })),
    valeur_retenue: 725000,
    valeur_retenue_detail: { prix: 725000, honoraires_pct: 5, charge_honoraires: 'acquereur' },
    envoi: mkEnvoi('2026-04-07T09:15:00Z', 'c.perrin@orange.fr', 'Mme Christine Perrin'),
    photo_url: 'https://picsum.photos/seed/adv011/800/600',
  },

  // === 2 OUVERTES ===
  {
    id: 'adv_012',
    type: 'avis_valeur',
    statut: 'ouverte',
    source: 'estimation_rapide',
    parent_estimation_id: 'est_006',
    version: 1,
    created_at: '2026-04-02T10:00:00Z',
    updated_at: '2026-04-03T14:00:00Z',
    auteur: 'Sophie Leroy',
    client: { civilite: 'M.', nom: 'Leclerc', prenom: 'Julien', email: 'j.leclerc@gmail.com', telephone: '06 78 90 12 34' },
    bien: mkBien({
      adresse: '44 rue de la Pompe', ville: 'Paris', code_postal: '75016', lat: 48.8645, lon: 2.2789,
      surface: 98, nb_pieces: 4, nb_chambres: 3, etage: 5, nb_etages: 7,
      annee_construction: 1910, dpe: 'D', ges: 'D', etat: 'bon', exposition: 'Sud-Ouest',
      caracteristiques: ['balcon', 'cave', 'ascenseur', 'gardien'],
      points_forts: ['Haussmannien', 'Vue dégagée', 'Quartier résidentiel'],
      charges_mensuelles: 520, taxe_fonciere: 3400,
    }),
    avm: mkAvm(mkBien({ adresse: '44 rue de la Pompe', ville: 'Paris', code_postal: '75016', surface: 98, nb_pieces: 4, etat: 'bon', dpe: 'D', caracteristiques: ['balcon', 'ascenseur'], type_bien: 'appartement' })),
    valeur_retenue: 1180000,
    valeur_retenue_detail: { prix: 1180000, honoraires_pct: 4, charge_honoraires: 'acquereur' },
    envoi: mkEnvoi('2026-04-03T14:00:00Z', 'j.leclerc@gmail.com', 'M. Julien Leclerc', [
      { jours_apres: 0, device: 'mobile' },
      { jours_apres: 1, device: 'desktop' },
      { jours_apres: 3, device: 'mobile' },
    ]),
    mandat_signe: true,
    mandat_signe_le: '2026-04-15T10:00:00Z',
    photo_url: 'https://picsum.photos/seed/adv012/800/600',
  },
  {
    id: 'adv_013',
    type: 'avis_valeur',
    statut: 'ouverte',
    source: 'bien_portefeuille',
    version: 1,
    created_at: '2026-04-01T08:00:00Z',
    updated_at: '2026-04-02T16:30:00Z',
    auteur: 'Jean Dubois',
    client: { civilite: 'Mme', nom: 'Dufour', prenom: 'Sophie', email: 'sophie.dufour@free.fr', telephone: '06 45 67 89 01' },
    bien: mkBien({
      adresse: '10 rue du Jardin Public', ville: 'Bordeaux', code_postal: '33000', lat: 44.8428, lon: -0.5798,
      surface: 105, nb_pieces: 4, nb_chambres: 3, etage: 1, nb_etages: 3,
      annee_construction: 1850, dpe: 'E', ges: 'E', etat: 'bon', exposition: 'Sud',
      caracteristiques: ['cave', 'cheminee'],
      points_forts: ['Pierre noble', 'Moulures d\'époque', 'Face au jardin'],
      charges_mensuelles: 180, taxe_fonciere: 1900,
    }),
    avm: mkAvm(mkBien({ adresse: '10 rue du Jardin Public', ville: 'Bordeaux', code_postal: '33000', surface: 105, nb_pieces: 4, etat: 'bon', dpe: 'E', caracteristiques: ['cheminee'], type_bien: 'appartement' })),
    valeur_retenue: 545000,
    valeur_retenue_detail: { prix: 545000, honoraires_pct: 5, charge_honoraires: 'acquereur' },
    envoi: mkEnvoi('2026-04-02T16:30:00Z', 'sophie.dufour@free.fr', 'Mme Sophie Dufour', [
      { jours_apres: 2, device: 'desktop' },
      { jours_apres: 5, device: 'mobile' },
    ]),
    photo_url: 'https://picsum.photos/seed/adv013/800/600',
  },

  // === 2 ARCHIVÉES ===
  {
    id: 'adv_014',
    type: 'avis_valeur',
    statut: 'archivee',
    source: 'estimation_rapide',
    parent_estimation_id: 'est_004',
    version: 1,
    created_at: '2026-03-12T09:00:00Z',
    updated_at: '2026-03-20T15:00:00Z',
    auteur: 'Marc Dupont',
    client: { civilite: 'M.', nom: 'Garnier', prenom: 'Luc', email: 'luc.garnier@yahoo.fr', telephone: '06 98 76 54 32' },
    bien: mkBien({
      adresse: '3 rue Victor Hugo', ville: 'Paris', code_postal: '75011', lat: 48.8587, lon: 2.3739,
      surface: 55, nb_pieces: 3, nb_chambres: 2, etage: 1, nb_etages: 5,
      annee_construction: 1930, dpe: 'F', ges: 'F', etat: 'a_renover', exposition: 'Nord',
      caracteristiques: ['cave'], points_defendre: ['DPE F', 'Travaux importants', 'Exposition Nord'],
      charges_mensuelles: 150, taxe_fonciere: 1450,
    }),
    avm: mkAvm(mkBien({ adresse: '3 rue Victor Hugo', ville: 'Paris', code_postal: '75011', surface: 55, nb_pieces: 3, etat: 'a_renover', dpe: 'F', type_bien: 'appartement' })),
    valeur_retenue: 418000,
    valeur_retenue_detail: { prix: 418000, honoraires_pct: 6, charge_honoraires: 'acquereur' },
    photo_url: 'https://picsum.photos/seed/adv014/800/600',
  },
  {
    id: 'adv_015',
    type: 'avis_valeur',
    statut: 'archivee',
    source: 'manuel',
    version: 1,
    created_at: '2026-02-28T13:00:00Z',
    updated_at: '2026-03-10T10:00:00Z',
    auteur: 'Sophie Leroy',
    client: { civilite: 'Mme', nom: 'Blanc', prenom: 'Karine', email: 'karine.blanc@gmail.com', telephone: '07 34 56 78 90' },
    bien: mkBien({
      adresse: '20 rue de la Part-Dieu', ville: 'Lyon', code_postal: '69003', lat: 45.7602, lon: 4.8580,
      surface: 45, nb_pieces: 2, nb_chambres: 1, etage: 6, nb_etages: 10,
      annee_construction: 1975, dpe: 'E', ges: 'E', etat: 'a_rafraichir', exposition: 'Ouest',
      caracteristiques: ['ascenseur', 'cave'], charges_mensuelles: 180, taxe_fonciere: 520,
    }),
    avm: mkAvm(mkBien({ adresse: '20 rue de la Part-Dieu', ville: 'Lyon', code_postal: '69003', surface: 45, nb_pieces: 2, etat: 'a_rafraichir', dpe: 'E', caracteristiques: ['ascenseur'], type_bien: 'appartement' })),
    valeur_retenue: 228000,
    valeur_retenue_detail: { prix: 228000, honoraires_pct: 6, charge_honoraires: 'acquereur' },
    photo_url: 'https://picsum.photos/seed/adv015/800/600',
  },
];
