import { BienPortefeuille } from '../types';

export const MOCK_BIENS_PORTEFEUILLE: BienPortefeuille[] = [
  {
    id: 'bien_001',
    adresse: '12 rue Péclet',
    ville: 'Paris 15e',
    code_postal: '75015',
    type_bien: 'appartement',
    surface: 52,
    nb_pieces: 3,
    etage: 2,
    dpe: 'C',
    statut_mandat: 'Mandat exclusif',
    auteur: 'Sophie Leroy',
    photo_url: 'https://picsum.photos/seed/bien001/400/300',
  },
  {
    id: 'bien_002',
    adresse: '8 avenue des Tilleuls',
    ville: 'Boulogne-Billancourt',
    code_postal: '92100',
    type_bien: 'maison',
    surface: 120,
    nb_pieces: 5,
    etage: 0,
    dpe: 'B',
    statut_mandat: 'Prospection',
    auteur: 'Jean Dubois',
    photo_url: 'https://picsum.photos/seed/bien002/400/300',
  },
  {
    id: 'bien_003',
    adresse: '45 cours de la Liberté',
    ville: 'Lyon 3e',
    code_postal: '69003',
    type_bien: 'appartement',
    surface: 68,
    nb_pieces: 3,
    etage: 4,
    dpe: 'C',
    statut_mandat: 'Mandat simple',
    auteur: 'Jean Dubois',
    photo_url: 'https://picsum.photos/seed/bien003/400/300',
  },
  {
    id: 'bien_004',
    adresse: '22 quai de Saône',
    ville: 'Lyon 1er',
    code_postal: '69001',
    type_bien: 'appartement',
    surface: 90,
    nb_pieces: 4,
    etage: 3,
    dpe: 'B',
    statut_mandat: 'Mandat exclusif',
    auteur: 'Sophie Leroy',
    photo_url: 'https://picsum.photos/seed/bien004/400/300',
  },
  {
    id: 'bien_005',
    adresse: '8 allée des Roses',
    ville: 'Bordeaux',
    code_postal: '33000',
    type_bien: 'maison',
    surface: 130,
    nb_pieces: 5,
    etage: 0,
    dpe: 'D',
    statut_mandat: 'Mandat exclusif',
    auteur: 'Marc Dupont',
    photo_url: 'https://picsum.photos/seed/bien005/400/300',
  },
  {
    id: 'bien_006',
    adresse: '16 rue du Hameau',
    ville: 'Paris 15e',
    code_postal: '75015',
    type_bien: 'appartement',
    surface: 42,
    nb_pieces: 2,
    etage: 2,
    dpe: 'E',
    statut_mandat: 'Prospection',
    auteur: 'Sophie Leroy',
    photo_url: 'https://picsum.photos/seed/bien006/400/300',
  },
  {
    id: 'bien_007',
    adresse: '3 rue des Acacias',
    ville: 'Bordeaux',
    code_postal: '33200',
    type_bien: 'maison',
    surface: 95,
    nb_pieces: 4,
    etage: 0,
    dpe: 'C',
    statut_mandat: 'Mandat simple',
    auteur: 'Marc Dupont',
    photo_url: 'https://picsum.photos/seed/bien007/400/300',
  },
  {
    id: 'bien_008',
    adresse: '88 avenue Haussmann',
    ville: 'Paris 8e',
    code_postal: '75008',
    type_bien: 'appartement',
    surface: 120,
    nb_pieces: 5,
    etage: 6,
    dpe: 'D',
    statut_mandat: 'Mandat exclusif',
    auteur: 'Sophie Leroy',
    photo_url: 'https://picsum.photos/seed/bien008/400/300',
  },
  {
    id: 'bien_009',
    adresse: '7 rue Sala',
    ville: 'Lyon 2e',
    code_postal: '69002',
    type_bien: 'appartement',
    surface: 30,
    nb_pieces: 1,
    etage: 2,
    dpe: 'E',
    statut_mandat: 'Prospection',
    auteur: 'Jean Dubois',
    photo_url: 'https://picsum.photos/seed/bien009/400/300',
  },
  {
    id: 'bien_010',
    adresse: '50 rue de la Croix Nivert',
    ville: 'Paris 15e',
    code_postal: '75015',
    type_bien: 'appartement',
    surface: 63,
    nb_pieces: 3,
    etage: 3,
    dpe: 'D',
    statut_mandat: 'Mandat simple',
    auteur: 'Marc Dupont',
    photo_url: 'https://picsum.photos/seed/bien010/400/300',
  },
  {
    id: 'bien_011',
    adresse: '14 cours du Médoc',
    ville: 'Bordeaux',
    code_postal: '33300',
    type_bien: 'appartement',
    surface: 35,
    nb_pieces: 2,
    etage: 0,
    dpe: 'D',
    statut_mandat: 'Mandat exclusif',
    auteur: 'Jean Dubois',
    photo_url: 'https://picsum.photos/seed/bien011/400/300',
  },
  {
    id: 'bien_012',
    adresse: '30 rue de la Charité',
    ville: 'Lyon 2e',
    code_postal: '69002',
    type_bien: 'appartement',
    surface: 80,
    nb_pieces: 4,
    etage: 1,
    dpe: 'C',
    statut_mandat: 'Mandat simple',
    auteur: 'Sophie Leroy',
    photo_url: 'https://picsum.photos/seed/bien012/400/300',
  },
  {
    id: 'bien_013',
    adresse: '5 impasse des Lilas',
    ville: 'Lyon 6e',
    code_postal: '69006',
    type_bien: 'maison',
    surface: 150,
    nb_pieces: 6,
    etage: 0,
    dpe: 'G',
    statut_mandat: 'Prospection',
    auteur: 'Marc Dupont',
    photo_url: 'https://picsum.photos/seed/bien013/400/300',
  },
  {
    id: 'bien_014',
    adresse: '18 avenue Jean Jaurès',
    ville: 'Bordeaux',
    code_postal: '33000',
    type_bien: 'appartement',
    surface: 75,
    nb_pieces: 4,
    etage: 2,
    dpe: 'A',
    statut_mandat: 'Mandat exclusif',
    auteur: 'Jean Dubois',
    photo_url: 'https://picsum.photos/seed/bien014/400/300',
  },
  {
    id: 'bien_015',
    adresse: '2 rue Cler',
    ville: 'Paris 7e',
    code_postal: '75007',
    type_bien: 'appartement',
    surface: 45,
    nb_pieces: 2,
    etage: 3,
    dpe: 'C',
    statut_mandat: 'Mandat simple',
    auteur: 'Sophie Leroy',
    photo_url: 'https://picsum.photos/seed/bien015/400/300',
  },
  {
    id: 'bien_016',
    adresse: '28 rue Boileau',
    ville: 'Lyon 6e',
    code_postal: '69006',
    type_bien: 'appartement',
    surface: 110,
    nb_pieces: 5,
    etage: 2,
    dpe: 'B',
    statut_mandat: 'Mandat exclusif',
    auteur: 'Marc Dupont',
    photo_url: 'https://picsum.photos/seed/bien016/400/300',
  },
  {
    id: 'bien_017',
    adresse: '55 rue du Commerce',
    ville: 'Paris 15e',
    code_postal: '75015',
    type_bien: 'parking',
    surface: 15,
    nb_pieces: 0,
    etage: -1,
    dpe: 'inconnu',
    statut_mandat: 'Mandat simple',
    auteur: 'Sophie Leroy',
    photo_url: 'https://picsum.photos/seed/bien017/400/300',
  },
  {
    id: 'bien_018',
    adresse: '12 rue de la Paix',
    ville: 'Bordeaux',
    code_postal: '33800',
    type_bien: 'terrain',
    surface: 800,
    nb_pieces: 0,
    etage: 0,
    dpe: 'inconnu',
    statut_mandat: 'Prospection',
    auteur: 'Jean Dubois',
    photo_url: 'https://picsum.photos/seed/bien018/400/300',
  },
  {
    id: 'bien_019',
    adresse: '3 rue Victor Hugo',
    ville: 'Paris 11e',
    code_postal: '75011',
    type_bien: 'appartement',
    surface: 55,
    nb_pieces: 3,
    etage: 1,
    dpe: 'F',
    statut_mandat: 'Mandat exclusif',
    auteur: 'Marc Dupont',
    photo_url: 'https://picsum.photos/seed/bien019/400/300',
  },
  {
    id: 'bien_020',
    adresse: '9 allée du Parc',
    ville: 'Bordeaux',
    code_postal: '33100',
    type_bien: 'maison',
    surface: 160,
    nb_pieces: 7,
    etage: 0,
    dpe: 'B',
    statut_mandat: 'Mandat exclusif',
    auteur: 'Sophie Leroy',
    photo_url: 'https://picsum.photos/seed/bien020/400/300',
  },
];
