import { Estimation, EstimationFormData, AvmResult } from '../types';
import { computeAvm } from '../utils/avmEngine';

function mkBien(overrides: Partial<EstimationFormData>): EstimationFormData {
  return {
    adresse: '',
    ville: '',
    code_postal: '',
    lat: 0,
    lon: 0,
    type_bien: 'appartement',
    surface: 0,
    nb_pieces: 0,
    nb_chambres: 0,
    etage: 0,
    nb_etages: 0,
    surface_terrain: 0,
    annee_construction: 0,
    dpe: 'D',
    ges: 'D',
    etat: 'bon',
    exposition: '',
    caracteristiques: [],
    description: '',
    points_forts: [],
    points_defendre: [],
    charges_mensuelles: 0,
    taxe_fonciere: 0,
    ...overrides,
  };
}

function mkAvm(data: EstimationFormData): AvmResult {
  return (
    computeAvm(data) || {
      prix: { estimation: 0, fourchette_basse: 0, fourchette_haute: 0, prix_m2: 0, confiance: 0.5, confiance_label: 'faible' },
      loyer: { estimation: 0, fourchette_basse: 0, fourchette_haute: 0, loyer_m2: 0, rendement_brut: 0 },
      ajustements: [],
      comparables: [],
      marche_reference: { prix_m2_bas: 0, prix_m2_median: 0, prix_m2_haut: 0, ecart_vs_marche_pct: 0 },
    }
  );
}

const SIGNATURE_EXPERT = {
  nom: 'Sophie Leroy',
  qualification: 'Expert immobilier agréé',
  numero_agrement: 'RICS-FR-2018-2241',
};

export const MOCK_EXPERTISE: Estimation[] = [
  {
    id: 'exp_001',
    type: 'expertise_rics_tegova',
    statut: 'brouillon',
    source: 'manuel',
    version: 1,
    created_at: '2026-04-22T09:00:00Z',
    updated_at: '2026-04-22T15:30:00Z',
    auteur: 'Sophie Leroy',
    client: { civilite: 'Mme', nom: 'Bernard', prenom: 'Hélène', email: 'h.bernard@notaires-paris.fr', telephone: '01 42 60 12 34' },
    bien: mkBien({
      adresse: '47 avenue Mozart',
      ville: 'Paris',
      code_postal: '75016',
      lat: 48.853,
      lon: 2.275,
      surface: 128,
      nb_pieces: 5,
      nb_chambres: 3,
      etage: 4,
      nb_etages: 6,
      annee_construction: 1928,
      dpe: 'D',
      ges: 'D',
      etat: 'bon',
      exposition: 'Sud-Ouest',
      caracteristiques: ['ascenseur', 'cave', 'parking', 'balcon'],
      points_forts: ['Immeuble Haussmannien', 'Étage élevé', 'Double exposition'],
      charges_mensuelles: 480,
      taxe_fonciere: 3200,
    }),
    avm: mkAvm(
      mkBien({
        adresse: '47 avenue Mozart',
        ville: 'Paris',
        code_postal: '75016',
        surface: 128,
        nb_pieces: 5,
        etat: 'bon',
        dpe: 'D',
        type_bien: 'appartement',
      }),
    ),
    valeur_retenue: null,
    photo_url: 'https://picsum.photos/seed/exp001/800/600',
    expert: {
      referentiel: 'RICS_TEGOVA',
      methode_principale: 'comparaison_directe',
      methodes_complementaires: ['capitalisation_revenus'],
      finalite: 'succession',
      donneur_ordre: { civilite: 'Mme', nom: 'Bernard', prenom: 'Hélène', email: 'h.bernard@notaires-paris.fr', telephone: '01 42 60 12 34' },
      date_visite: '2026-04-20',
      date_valeur: '2026-04-22',
      numero_dossier: 'EXP-2026-0042',
      expert_signature: SIGNATURE_EXPERT,
      hypotheses_speciales: ['Bien occupé par les ayants-droit jusqu\'au partage'],
      declaration_independance: true,
    },
  },
  {
    id: 'exp_002',
    type: 'expertise_rics_tegova',
    statut: 'finalisee',
    source: 'bien_portefeuille',
    version: 1,
    created_at: '2026-04-15T08:30:00Z',
    updated_at: '2026-04-21T17:20:00Z',
    auteur: 'Sophie Leroy',
    client: { civilite: 'M.', nom: 'Vandenberghe', prenom: 'Pierre', email: 'p.vandenberghe@socgen.fr', telephone: '01 56 78 90 12' },
    bien: mkBien({
      adresse: '12 rue de la République',
      ville: 'Lyon',
      code_postal: '69002',
      lat: 45.764,
      lon: 4.832,
      surface: 215,
      nb_pieces: 7,
      nb_chambres: 4,
      etage: 0,
      nb_etages: 1,
      annee_construction: 1895,
      dpe: 'E',
      ges: 'F',
      etat: 'bon',
      caracteristiques: ['rdc commercial', 'cour', 'cave voûtée'],
      points_forts: ['Hyper-centre', 'Local commercial pied d\'immeuble', 'Façade classée'],
      charges_mensuelles: 0,
      taxe_fonciere: 8400,
    }),
    avm: mkAvm(
      mkBien({
        adresse: '12 rue de la République',
        ville: 'Lyon',
        code_postal: '69002',
        surface: 215,
        nb_pieces: 7,
        etat: 'bon',
        dpe: 'E',
        type_bien: 'maison',
      }),
    ),
    valeur_retenue: 1240000,
    valeur_retenue_detail: { prix: 1240000, honoraires_pct: 0, charge_honoraires: 'vendeur' },
    photo_url: 'https://picsum.photos/seed/exp002/800/600',
    expert: {
      referentiel: 'RICS',
      methode_principale: 'capitalisation_revenus',
      methodes_complementaires: ['comparaison_directe'],
      finalite: 'garantie_bancaire',
      donneur_ordre: { civilite: 'M.', nom: 'Vandenberghe', prenom: 'Pierre', email: 'p.vandenberghe@socgen.fr', telephone: '01 56 78 90 12' },
      date_visite: '2026-04-12',
      date_valeur: '2026-04-15',
      numero_dossier: 'EXP-2026-0038',
      expert_signature: SIGNATURE_EXPERT,
      hypotheses_speciales: ['Loyer commercial RDC : 38 000 € HT/an', 'Bail commercial expirant en 2031'],
      declaration_independance: true,
    },
  },
  {
    id: 'exp_003',
    type: 'expertise_rics_tegova',
    statut: 'envoyee',
    source: 'manuel',
    version: 2,
    versions_precedentes: ['exp_003_v1'],
    created_at: '2026-04-10T11:00:00Z',
    updated_at: '2026-04-19T14:45:00Z',
    auteur: 'Jean Dubois',
    client: { civilite: 'Mme', nom: 'Aubin', prenom: 'Catherine', email: 'c.aubin@cabinet-aubin.com', telephone: '04 91 56 78 90' },
    bien: mkBien({
      adresse: '8 boulevard Longchamp',
      ville: 'Marseille',
      code_postal: '13001',
      lat: 43.302,
      lon: 5.388,
      surface: 95,
      nb_pieces: 4,
      nb_chambres: 2,
      etage: 3,
      nb_etages: 5,
      annee_construction: 1875,
      dpe: 'F',
      ges: 'E',
      etat: 'a_renover',
      caracteristiques: ['parquet', 'moulures', 'cheminée'],
      charges_mensuelles: 220,
      taxe_fonciere: 1100,
    }),
    avm: mkAvm(
      mkBien({
        adresse: '8 boulevard Longchamp',
        ville: 'Marseille',
        code_postal: '13001',
        surface: 95,
        nb_pieces: 4,
        etat: 'a_renover',
        dpe: 'F',
        type_bien: 'appartement',
      }),
    ),
    valeur_retenue: 285000,
    valeur_retenue_detail: { prix: 285000, honoraires_pct: 0, charge_honoraires: 'vendeur' },
    photo_url: 'https://picsum.photos/seed/exp003/800/600',
    envoi: {
      envoye_le: '2026-04-19T14:45:00Z',
      email_destinataire: 'c.aubin@cabinet-aubin.com',
      nom_destinataire: 'Mme Catherine Aubin',
      objet: 'Rapport d\'expertise — 8 boulevard Longchamp, Marseille',
      message: 'Bonjour Maître, veuillez trouver ci-joint le rapport d\'expertise conforme RICS / TEGOVA.',
      ouvertures: [],
      token_public: 'exp_token_003',
    },
    expert: {
      referentiel: 'TEGOVA',
      methode_principale: 'comparaison_directe',
      methodes_complementaires: [],
      finalite: 'litige',
      donneur_ordre: { civilite: 'Mme', nom: 'Aubin', prenom: 'Catherine', email: 'c.aubin@cabinet-aubin.com', telephone: '04 91 56 78 90' },
      date_visite: '2026-04-12',
      date_valeur: '2026-04-15',
      numero_dossier: 'EXP-2026-0031',
      expert_signature: { nom: 'Jean Dubois', qualification: 'Expert TEGOVA REV', numero_agrement: 'TEGOVA-FR-2019-1108' },
      hypotheses_speciales: ['Bien évalué dans le cadre d\'une procédure de divorce'],
      declaration_independance: true,
    },
  },
  {
    id: 'exp_004',
    type: 'expertise_rics_tegova',
    statut: 'ouverte',
    source: 'manuel',
    version: 1,
    created_at: '2026-04-05T09:30:00Z',
    updated_at: '2026-04-18T10:00:00Z',
    auteur: 'Sophie Leroy',
    client: { civilite: 'M.', nom: 'Garnier', prenom: 'Antoine', email: 'a.garnier@invest-corp.fr', telephone: '01 45 67 89 10' },
    bien: mkBien({
      adresse: '34 cours Pasteur',
      ville: 'Bordeaux',
      code_postal: '33000',
      lat: 44.835,
      lon: -0.572,
      surface: 580,
      surface_terrain: 1200,
      nb_pieces: 18,
      etage: 0,
      nb_etages: 4,
      annee_construction: 2008,
      dpe: 'B',
      ges: 'B',
      etat: 'neuf',
      caracteristiques: ['ascenseur', 'parking sous-sol', 'climatisation'],
      points_forts: ['Immeuble de bureaux entièrement loué', 'Locataires investment-grade', 'Parking 18 places'],
      charges_mensuelles: 0,
      taxe_fonciere: 18500,
    }),
    avm: mkAvm(
      mkBien({
        adresse: '34 cours Pasteur',
        ville: 'Bordeaux',
        code_postal: '33000',
        surface: 580,
        nb_pieces: 18,
        etat: 'neuf',
        dpe: 'B',
        type_bien: 'maison',
      }),
    ),
    valeur_retenue: 4850000,
    valeur_retenue_detail: { prix: 4850000, honoraires_pct: 0, charge_honoraires: 'vendeur' },
    photo_url: 'https://picsum.photos/seed/exp004/800/600',
    envoi: {
      envoye_le: '2026-04-15T11:30:00Z',
      email_destinataire: 'a.garnier@invest-corp.fr',
      nom_destinataire: 'M. Antoine Garnier',
      objet: 'Rapport d\'expertise — Immeuble de bureaux, Bordeaux',
      message: 'Cher M. Garnier, veuillez trouver ci-joint le rapport d\'expertise.',
      ouvertures: [
        { date: '2026-04-15T16:42:00Z', user_agent: 'desktop' },
        { date: '2026-04-16T09:15:00Z', user_agent: 'mobile' },
        { date: '2026-04-18T10:00:00Z', user_agent: 'desktop' },
      ],
      derniere_ouverture: '2026-04-18T10:00:00Z',
      token_public: 'exp_token_004',
    },
    expert: {
      referentiel: 'RICS_TEGOVA',
      methode_principale: 'capitalisation_revenus',
      methodes_complementaires: ['comparaison_directe', 'cout_remplacement'],
      finalite: 'apport_societe',
      donneur_ordre: { civilite: 'M.', nom: 'Garnier', prenom: 'Antoine', email: 'a.garnier@invest-corp.fr', telephone: '01 45 67 89 10' },
      date_visite: '2026-04-08',
      date_valeur: '2026-04-15',
      numero_dossier: 'EXP-2026-0024',
      expert_signature: SIGNATURE_EXPERT,
      hypotheses_speciales: [
        'Loyer commercial annualisé : 412 000 € HT',
        'Taux de capitalisation retenu : 8,5 %',
        'Hypothèse de plein emploi sur la durée résiduelle des baux',
      ],
      declaration_independance: true,
    },
  },
  {
    id: 'exp_005',
    type: 'expertise_rics_tegova',
    statut: 'brouillon',
    source: 'estimation_rapide',
    parent_estimation_id: 'est_007',
    version: 1,
    created_at: '2026-04-23T14:00:00Z',
    updated_at: '2026-04-23T14:00:00Z',
    auteur: 'Sophie Leroy',
    client: null,
    bien: mkBien({
      adresse: '5 rue des Lilas',
      ville: 'Toulouse',
      code_postal: '31000',
      lat: 43.604,
      lon: 1.444,
      surface: 165,
      surface_terrain: 420,
      nb_pieces: 6,
      nb_chambres: 4,
      annee_construction: 1985,
      dpe: 'D',
      ges: 'D',
      etat: 'bon',
      caracteristiques: ['piscine', 'jardin', 'garage 2v'],
      taxe_fonciere: 2100,
    }),
    avm: mkAvm(
      mkBien({
        adresse: '5 rue des Lilas',
        ville: 'Toulouse',
        code_postal: '31000',
        surface: 165,
        nb_pieces: 6,
        etat: 'bon',
        dpe: 'D',
        type_bien: 'maison',
      }),
    ),
    valeur_retenue: null,
    photo_url: 'https://picsum.photos/seed/exp005/800/600',
    expert: {
      referentiel: 'RICS',
      methode_principale: 'comparaison_directe',
      methodes_complementaires: [],
      finalite: 'donation',
      donneur_ordre: null,
      date_visite: '2026-04-23',
      numero_dossier: 'EXP-2026-0049',
      expert_signature: SIGNATURE_EXPERT,
      hypotheses_speciales: [],
      declaration_independance: true,
    },
  },
  {
    id: 'exp_006',
    type: 'expertise_rics_tegova',
    statut: 'archivee',
    source: 'manuel',
    version: 1,
    created_at: '2025-11-10T10:00:00Z',
    updated_at: '2025-12-22T16:00:00Z',
    auteur: 'Jean Dubois',
    client: { civilite: 'M.', nom: 'Lefebvre', prenom: 'Olivier', email: 'o.lefebvre@gmail.com', telephone: '06 23 45 67 89' },
    bien: mkBien({
      adresse: '18 rue Saint-Michel',
      ville: 'Nantes',
      code_postal: '44000',
      lat: 47.218,
      lon: -1.553,
      surface: 78,
      nb_pieces: 3,
      nb_chambres: 2,
      etage: 1,
      nb_etages: 3,
      annee_construction: 1970,
      dpe: 'D',
      ges: 'D',
      etat: 'a_rafraichir',
      charges_mensuelles: 140,
      taxe_fonciere: 850,
    }),
    avm: mkAvm(
      mkBien({
        adresse: '18 rue Saint-Michel',
        ville: 'Nantes',
        code_postal: '44000',
        surface: 78,
        nb_pieces: 3,
        etat: 'a_rafraichir',
        dpe: 'D',
        type_bien: 'appartement',
      }),
    ),
    valeur_retenue: 248000,
    valeur_retenue_detail: { prix: 248000, honoraires_pct: 0, charge_honoraires: 'vendeur' },
    photo_url: 'https://picsum.photos/seed/exp006/800/600',
    expert: {
      referentiel: 'TEGOVA',
      methode_principale: 'comparaison_directe',
      methodes_complementaires: [],
      finalite: 'cession',
      donneur_ordre: { civilite: 'M.', nom: 'Lefebvre', prenom: 'Olivier', email: 'o.lefebvre@gmail.com', telephone: '06 23 45 67 89' },
      date_visite: '2025-11-08',
      date_valeur: '2025-11-10',
      numero_dossier: 'EXP-2025-0118',
      expert_signature: { nom: 'Jean Dubois', qualification: 'Expert TEGOVA REV', numero_agrement: 'TEGOVA-FR-2019-1108' },
      hypotheses_speciales: [],
      declaration_independance: true,
    },
  },
];
