import { BlocId, BlocDefinition, BlocConfig, RapportType } from './types';

export const BLOCS_REGISTRY: Record<BlocId, BlocDefinition> = {
  couverture: {
    id: 'couverture',
    label: 'Couverture',
    group: 'identity',
    defaultActiveBy: { avis_valeur: true, etude_locative: true, dossier_invest: true },
    editable: true,
    pageBreakBefore: true,
  },
  sommaire: {
    id: 'sommaire',
    label: 'Sommaire',
    group: 'identity',
    defaultActiveBy: {},
    editable: false,
  },
  agence: {
    id: 'agence',
    label: 'Présentation agence',
    group: 'identity',
    defaultActiveBy: { avis_valeur: true, etude_locative: true, dossier_invest: true },
    editable: true,
  },
  conseiller: {
    id: 'conseiller',
    label: 'Présentation conseiller',
    group: 'identity',
    defaultActiveBy: { avis_valeur: true, etude_locative: true, dossier_invest: true },
    editable: true,
  },
  bien: {
    id: 'bien',
    label: 'Présentation du bien',
    group: 'bien',
    defaultActiveBy: { avis_valeur: true, etude_locative: true, dossier_invest: true },
    editable: true,
  },
  photos: {
    id: 'photos',
    label: 'Photos du bien',
    group: 'bien',
    defaultActiveBy: { avis_valeur: true, etude_locative: true, dossier_invest: true },
    editable: true,
  },
  points: {
    id: 'points',
    label: 'Points forts / à défendre',
    group: 'bien',
    defaultActiveBy: { avis_valeur: true, etude_locative: true, dossier_invest: true },
    editable: true,
  },
  cadastre: { id: 'cadastre', label: 'Cadastre + parcelle', group: 'bien', defaultActiveBy: { dossier_invest: true }, editable: false },
  urbanisme: { id: 'urbanisme', label: 'Autorisations urbanisme', group: 'bien', defaultActiveBy: { dossier_invest: true }, editable: false },
  historique_ventes: { id: 'historique_ventes', label: 'Historique ventes adresse', group: 'bien', defaultActiveBy: { dossier_invest: true }, editable: false },
  socio_eco: {
    id: 'socio_eco',
    label: 'Éléments socio-économiques',
    group: 'socio',
    defaultActiveBy: { avis_valeur: true, etude_locative: true, dossier_invest: true },
    editable: false,
  },
  profil_cible: { id: 'profil_cible', label: 'Profil acquéreur / locataire cible', group: 'socio', defaultActiveBy: { avis_valeur: true, etude_locative: true, dossier_invest: true }, editable: false },
  budget_revenu: { id: 'budget_revenu', label: 'Budget / revenu nécessaire', group: 'socio', defaultActiveBy: { avis_valeur: true, etude_locative: true, dossier_invest: true }, editable: false },
  solvabilite: { id: 'solvabilite', label: 'Solvabilité (profondeur marché)', group: 'socio', defaultActiveBy: { avis_valeur: true, etude_locative: true, dossier_invest: true }, editable: false },
  score_emplacement: { id: 'score_emplacement', label: 'Score emplacement', group: 'marche', defaultActiveBy: { avis_valeur: true, etude_locative: true, dossier_invest: true }, editable: false },
  services_proximite: { id: 'services_proximite', label: 'Services de proximité', group: 'marche', defaultActiveBy: { avis_valeur: true, etude_locative: true, dossier_invest: true }, editable: false },
  repartition_logements: { id: 'repartition_logements', label: 'Répartition logements secteur', group: 'marche', defaultActiveBy: { avis_valeur: true, etude_locative: true, dossier_invest: true }, editable: false },
  prix_marche: {
    id: 'prix_marche',
    label: 'Prix du marché secteur',
    group: 'marche',
    defaultActiveBy: { avis_valeur: true, dossier_invest: true },
    editable: false,
  },
  evolution_prix: { id: 'evolution_prix', label: 'Évolution prix 6m / 1a / 2a', group: 'marche', defaultActiveBy: { avis_valeur: true, dossier_invest: true }, editable: false },
  loyers_marche: { id: 'loyers_marche', label: 'Loyers du marché secteur', group: 'marche', defaultActiveBy: { etude_locative: true, dossier_invest: true }, editable: false },
  evolution_loyers: { id: 'evolution_loyers', label: 'Évolution loyers', group: 'marche', defaultActiveBy: { etude_locative: true, dossier_invest: true }, editable: false },
  rendement: { id: 'rendement', label: 'Rendement locatif', group: 'marche', defaultActiveBy: { dossier_invest: true }, editable: false },
  tension: { id: 'tension', label: 'Tension marché', group: 'marche', defaultActiveBy: { avis_valeur: true, etude_locative: true, dossier_invest: true }, editable: false },
  delais: { id: 'delais', label: 'Délais de vente / location', group: 'marche', defaultActiveBy: { avis_valeur: true, etude_locative: true, dossier_invest: true }, editable: false },
  comp_vente: { id: 'comp_vente', label: 'Comparables en vente', group: 'comparables', defaultActiveBy: { avis_valeur: true, dossier_invest: true }, editable: true },
  comp_vendus: {
    id: 'comp_vendus',
    label: 'Comparables vendus (DVF)',
    group: 'comparables',
    defaultActiveBy: { avis_valeur: true, dossier_invest: true },
    editable: true,
  },
  comp_invendus: { id: 'comp_invendus', label: 'Comparables invendus', group: 'comparables', defaultActiveBy: {}, editable: true },
  comp_location: { id: 'comp_location', label: 'Comparables à louer', group: 'comparables', defaultActiveBy: { etude_locative: true, dossier_invest: true }, editable: true },
  comp_loues: { id: 'comp_loues', label: 'Comparables loués', group: 'comparables', defaultActiveBy: { etude_locative: true, dossier_invest: true }, editable: true },
  focus_comp: { id: 'focus_comp', label: 'Focus comparable', group: 'comparables', defaultActiveBy: {}, editable: true },
  synthese_3_methodes: {
    id: 'synthese_3_methodes',
    label: 'Synthèse 3 méthodes',
    group: 'synthese',
    defaultActiveBy: { avis_valeur: true, etude_locative: true, dossier_invest: true },
    editable: false,
    pageBreakBefore: true,
  },
  ajustements: { id: 'ajustements', label: 'Ajustements feature par feature', group: 'synthese', defaultActiveBy: { avis_valeur: true, etude_locative: true, dossier_invest: true }, editable: false },
  reglementations: { id: 'reglementations', label: 'Réglementations locatives', group: 'reglementations', defaultActiveBy: { etude_locative: true }, editable: false },
  projet_invest: { id: 'projet_invest', label: 'Projet investissement', group: 'invest', defaultActiveBy: { dossier_invest: true }, editable: true },
  analyse_financiere: { id: 'analyse_financiere', label: 'Analyse financière', group: 'invest', defaultActiveBy: { dossier_invest: true }, editable: false },
  fiscalite: { id: 'fiscalite', label: 'Fiscalité', group: 'invest', defaultActiveBy: { dossier_invest: true }, editable: false },
  simulation_renov: { id: 'simulation_renov', label: 'Simulation refait à neuf', group: 'invest', defaultActiveBy: {}, editable: false },
  conclusion: {
    id: 'conclusion',
    label: 'Conclusion + valeur retenue',
    group: 'conclusion',
    defaultActiveBy: { avis_valeur: true, etude_locative: true, dossier_invest: true },
    editable: true,
    pageBreakBefore: true,
  },
  annexes: { id: 'annexes', label: 'Annexes (DPE, diagnostics)', group: 'annexes', defaultActiveBy: { avis_valeur: true, etude_locative: true }, editable: true },
  footer: { id: 'footer', label: 'Footer / mentions légales', group: 'annexes', defaultActiveBy: { avis_valeur: true, etude_locative: true, dossier_invest: true }, editable: false },
};

const ALL_BLOCS_ORDER: BlocId[] = [
  'couverture',
  'sommaire',
  'agence',
  'conseiller',
  'bien',
  'photos',
  'points',
  'cadastre',
  'urbanisme',
  'historique_ventes',
  'socio_eco',
  'profil_cible',
  'budget_revenu',
  'solvabilite',
  'score_emplacement',
  'services_proximite',
  'repartition_logements',
  'prix_marche',
  'evolution_prix',
  'loyers_marche',
  'evolution_loyers',
  'rendement',
  'tension',
  'delais',
  'comp_vente',
  'comp_vendus',
  'comp_invendus',
  'comp_location',
  'comp_loues',
  'focus_comp',
  'synthese_3_methodes',
  'ajustements',
  'reglementations',
  'projet_invest',
  'analyse_financiere',
  'fiscalite',
  'simulation_renov',
  'conclusion',
  'annexes',
  'footer',
];

export const BLOC_GROUP_LABEL: Record<string, string> = {
  identity: 'Identité',
  bien: 'Le bien',
  socio: 'Socio-économie',
  marche: 'Marché local',
  comparables: 'Comparables',
  synthese: 'Synthèse',
  reglementations: 'Réglementations',
  invest: 'Investissement',
  conclusion: 'Conclusion',
  annexes: 'Annexes',
};

export function getDefaultConfig(type: RapportType): BlocConfig[] {
  return ALL_BLOCS_ORDER.map((id, idx) => ({
    id,
    active: BLOCS_REGISTRY[id].defaultActiveBy[type] === true,
    order: idx,
  }));
}

export function getBlocsOrdered(blocs: BlocConfig[]): BlocConfig[] {
  return [...blocs].sort((a, b) => a.order - b.order);
}
