export const proRoutes = {
  root: '/app',
  tableauDeBord: '/app/tableau-de-bord',
  activite: {
    root: '/app/activite',
    pilotage: '/app/activite/pilotage',
    leads: '/app/activite/leads',
    leadDetail: (id: string) => `/app/activite/leads/${id}`,
    performance: '/app/activite/performance',
  },
  biens: {
    root: '/app/biens',
    portefeuille: '/app/biens/portefeuille',
    annonces: '/app/biens/annonces',
    dvf: '/app/biens/dvf',
  },
  prospection: {
    root: '/app/prospection',
    radar: '/app/prospection/radar',
    signauxDvf: '/app/prospection/signaux-dvf',
    signauxDpe: '/app/prospection/signaux-dpe',
  },
  widgets: {
    root: '/app/widgets',
    estimationVendeur: '/app/widgets/estimation-vendeur',
    projetInvestisseur: '/app/widgets/projet-investisseur',
    detail: (slug: string) => `/app/widgets/${slug}`,
  },
  estimation: {
    root: '/app/estimation',
    rapide: '/app/estimation/rapide',
    rapideDetail: (id: string) => `/app/estimation/rapide/${id}`,
    avisValeur: '/app/estimation/avis-valeur',
    avisValeurDetail: (id: string) => `/app/estimation/avis-valeur/${id}`,
    etudeLocative: '/app/estimation/etude-locative',
    etudeLocativeDetail: (id: string) => `/app/estimation/etude-locative/${id}`,
    expert: '/app/estimation/expert',
    expertDetail: (id: string) => `/app/estimation/expert/${id}`,
  },
  investissement: {
    root: '/app/investissement',
    opportunites: '/app/investissement/opportunites',
    dossiers: '/app/investissement/dossiers',
    dossierDetail: (id: string) => `/app/investissement/dossiers/${id}`,
    projetDetail: (id: string) => `/app/investissement/dossiers/projets/${id}`,
  },
  observatoire: {
    root: '/app/observatoire',
    marche: '/app/observatoire/marche',
    tension: '/app/observatoire/tension',
    contexteLocal: '/app/observatoire/contexte-local',
  },
  veille: {
    root: '/app/veille',
    alertes: '/app/veille/alertes',
    notifications: '/app/veille/notifications',
    biensSuivis: '/app/veille/biens-suivis',
    agencesConcurrentes: '/app/veille/agences-concurrentes',
  },
  equipe: {
    root: '/app/equipe',
    vue: '/app/equipe/vue',
    activite: '/app/equipe/activite',
    portefeuille: '/app/equipe/portefeuille',
    agenda: '/app/equipe/agenda',
    performance: '/app/equipe/performance',
  },
  studioMarketing: {
    root: '/app/studio-marketing',
    vueDensemble: '/app/studio-marketing',
    annonces: '/app/studio-marketing/annonces',
    atelier: '/app/studio-marketing/atelier',
    diffusion: '/app/studio-marketing/diffusion',
    interactions: '/app/studio-marketing/interactions',
    performance: '/app/studio-marketing/performance',
    bibliotheque: '/app/studio-marketing/bibliotheque',
  },
  parametres: {
    root: '/app/parametres',
    compte: '/app/parametres/compte',
    organisation: '/app/parametres/organisation',
    membres: '/app/parametres/membres',
    facturation: '/app/parametres/facturation',
    widget: '/app/parametres/widget',
    integrations: '/app/parametres/integrations',
  },
} as const;

export const publicRoutes = {
  home: '/',
  pro: '/pro',
  prixImmobiliers: '/prix-immobiliers',
  annonces: '/annonces',
  estimation: '/estimation',
  investissement: '/investissement',
  investissementSimulateur: '/investissement/simulateur',
  ressources: '/ressources',
  ressourceArticle: (slug: string) => `/ressources/${slug}`,
  login: '/login',
  loginReset: '/login/reset',
  widgetEstimation: '/widget/estimation',
  widgetInvestissement: '/widget/investissement',
  rapport: (token: string) => `/rapport/${token}`,
} as const;
