import { SignalDPE } from '../types';

export const signauxDpe: SignalDPE[] = [
  {
    signal_id: 'sgn_dpe_001',
    source: 'dpe',
    type: 'bailleur_a_arbitrer',
    kind: 'business',
    support_types: ['passoire_thermique', 'risque_locatif'],
    title: 'Bailleur à arbitrer',
    subtitle: 'Appartement · 68 m²',
    geo_precision: 'exacte',
    lat: 48.9422,
    lon: 2.3481,
    adresse: '8 rue Carnot',
    ville: 'La Plaine Saint-Denis',
    code_postal: '93210',
    score: 89,
    score_breakdown: [
      { label: 'Risque locatif / réglementaire', contribution: 20, detail: 'Classe G : interdiction 2025' },
      { label: 'Potentiel commercial', contribution: 18, detail: 'Zone tendue + usage locatif probable' },
      { label: 'Potentiel revalorisation', contribution: 15, detail: 'Gain 2 classes possible' },
    ],
    priority: 'haute',
    status: 'a_qualifier',
    bien_id: 'bien_093_002',
    assignee_id: 'user_sophie',
    explanation_short: 'Décote locative -18% · DPE G · Travaux 28-35 k€',
    tags: ['a_qualifier'],
    dpe_payload: {
      classe_dpe: 'G',
      date_dpe: '2024-02-14',
      type_bien: 'appartement',
      surface_m2: 68,
      usage_probable: 'locatif',
      zone_tendue: true,
      potentiel_gain_classe: 2,
      loyer_ou_valeur_apres_travaux_pct: 22,
      risque_reglementaire: 'fort',
      conso_energie_kwh_m2_an: 512,
      ges_kgco2_m2_an: 76,
      travaux_estimes_euros: 32000,
    },
    detected_at: '2026-04-20T10:00:00Z',
    created_at: '2026-04-20T10:00:00Z',
    updated_at: '2026-04-22T09:00:00Z',
  },
  {
    signal_id: 'sgn_dpe_002',
    source: 'dpe',
    type: 'vendeur_probable',
    kind: 'business',
    title: 'Vendeur probable',
    subtitle: 'Appartement · 74 m²',
    geo_precision: 'exacte',
    lat: 48.9362,
    lon: 2.3574,
    adresse: '12 rue Gabriel Péri',
    ville: 'Saint-Denis',
    code_postal: '93200',
    score: 82,
    score_breakdown: [
      { label: 'Potentiel commercial', contribution: 20, detail: 'Baisse de prix -5% détectée' },
      { label: 'Risque locatif / réglementaire', contribution: 15, detail: 'DPE F' },
      { label: 'Qualité donnée', contribution: 10 },
    ],
    priority: 'haute',
    status: 'nouveau',
    bien_id: 'bien_093_001',
    assignee_id: 'user_paul',
    explanation_short: 'Baisse de prix -5% et DPE F — signal de mise en vente',
    tags: ['nouveau'],
    dpe_payload: {
      classe_dpe: 'F',
      date_dpe: '2022-09-10',
      type_bien: 'appartement',
      surface_m2: 74,
      usage_probable: 'residence_principale',
      zone_tendue: true,
      potentiel_gain_classe: 2,
      loyer_ou_valeur_apres_travaux_pct: 14,
      risque_reglementaire: 'moyen',
      conso_energie_kwh_m2_an: 362,
      ges_kgco2_m2_an: 58,
      travaux_estimes_euros: 22000,
    },
    detected_at: '2026-04-22T08:00:00Z',
    created_at: '2026-04-22T08:00:00Z',
    updated_at: '2026-04-23T10:00:00Z',
  },
  {
    signal_id: 'sgn_dpe_003',
    source: 'dpe',
    type: 'potentiel_renovation',
    kind: 'business',
    support_types: ['passoire_thermique', 'revalorisation_apres_travaux'],
    title: 'Potentiel rénovation',
    subtitle: 'Maison · 95 m²',
    geo_precision: 'exacte',
    lat: 48.9435,
    lon: 2.348,
    adresse: '15 rue de Strasbourg',
    ville: 'Saint-Denis',
    code_postal: '93200',
    score: 91,
    score_breakdown: [
      { label: 'Potentiel revalorisation', contribution: 22, detail: 'Gain 3 classes atteignable' },
      { label: 'Gravité énergétique', contribution: 15, detail: 'DPE G' },
      { label: 'Potentiel commercial', contribution: 18 },
    ],
    priority: 'haute',
    status: 'en_cours',
    bien_id: 'bien_093_003',
    assignee_id: 'user_thomas',
    explanation_short: 'Passoire énergétique avec potentiel de gain de 3 classes',
    tags: ['haute_priorite'],
    dpe_payload: {
      classe_dpe: 'G',
      date_dpe: '2023-06-18',
      type_bien: 'maison',
      surface_m2: 95,
      usage_probable: 'residence_principale',
      zone_tendue: false,
      potentiel_gain_classe: 3,
      loyer_ou_valeur_apres_travaux_pct: 18,
      risque_reglementaire: 'fort',
      conso_energie_kwh_m2_an: 498,
      ges_kgco2_m2_an: 82,
      travaux_estimes_euros: 34000,
    },
    detected_at: '2026-04-17T11:00:00Z',
    created_at: '2026-04-17T11:00:00Z',
    updated_at: '2026-04-23T09:00:00Z',
  },
  {
    signal_id: 'sgn_dpe_004',
    source: 'dpe',
    type: 'opportunite_investisseur',
    kind: 'business',
    support_types: ['revalorisation_apres_travaux'],
    title: 'Opportunité investisseur',
    subtitle: 'Appartement · 42 m²',
    geo_precision: 'exacte',
    lat: 48.9245,
    lon: 2.3526,
    adresse: '23 avenue Lénine',
    ville: 'Saint-Denis',
    code_postal: '93200',
    score: 63,
    score_breakdown: [
      { label: 'Potentiel commercial', contribution: 15, detail: 'Rendement post-travaux élevé' },
      { label: 'Potentiel revalorisation', contribution: 14 },
      { label: 'Qualité donnée', contribution: 10 },
    ],
    priority: 'moyenne',
    status: 'nouveau',
    bien_id: 'bien_093_004',
    assignee_id: 'user_emilie',
    explanation_short: 'Loyer sous marché · DPE F · secteur à tension forte',
    tags: ['nouveau'],
    dpe_payload: {
      classe_dpe: 'F',
      date_dpe: '2023-11-02',
      type_bien: 'appartement',
      surface_m2: 42,
      usage_probable: 'locatif',
      zone_tendue: true,
      potentiel_gain_classe: 2,
      loyer_ou_valeur_apres_travaux_pct: 16,
      risque_reglementaire: 'moyen',
      conso_energie_kwh_m2_an: 389,
      ges_kgco2_m2_an: 62,
      travaux_estimes_euros: 14000,
    },
    detected_at: '2026-04-14T09:00:00Z',
    created_at: '2026-04-14T09:00:00Z',
    updated_at: '2026-04-21T09:00:00Z',
  },
  {
    signal_id: 'sgn_dpe_005',
    source: 'dpe',
    type: 'bailleur_a_arbitrer',
    kind: 'business',
    support_types: ['passoire_thermique', 'risque_locatif'],
    title: 'Bailleur à arbitrer',
    subtitle: 'Maison · 110 m²',
    geo_precision: 'exacte',
    lat: 48.9148,
    lon: 2.3855,
    adresse: '56 rue Henri Barbusse',
    ville: 'Aubervilliers',
    code_postal: '93300',
    score: 93,
    score_breakdown: [
      { label: 'Risque locatif / réglementaire', contribution: 22, detail: 'Classe G · interdiction 2025' },
      { label: 'Potentiel revalorisation', contribution: 18, detail: 'Gain 2 classes' },
      { label: 'Potentiel commercial', contribution: 15 },
    ],
    priority: 'haute',
    status: 'a_qualifier',
    bien_id: 'bien_093_005',
    assignee_id: 'user_paul',
    explanation_short: 'Passoire énergétique DPE G · interdiction locative',
    tags: ['urgent'],
    dpe_payload: {
      classe_dpe: 'G',
      date_dpe: '2023-08-22',
      type_bien: 'maison',
      surface_m2: 110,
      usage_probable: 'locatif',
      zone_tendue: true,
      potentiel_gain_classe: 2,
      loyer_ou_valeur_apres_travaux_pct: 20,
      risque_reglementaire: 'fort',
      conso_energie_kwh_m2_an: 537,
      ges_kgco2_m2_an: 88,
      travaux_estimes_euros: 38000,
    },
    detected_at: '2026-04-12T09:00:00Z',
    created_at: '2026-04-12T09:00:00Z',
    updated_at: '2026-04-22T09:00:00Z',
  },
  {
    signal_id: 'sgn_dpe_006',
    source: 'dpe',
    type: 'vendeur_probable',
    kind: 'business',
    title: 'Vendeur probable',
    subtitle: 'Appartement · 55 m²',
    geo_precision: 'exacte',
    lat: 48.9097,
    lon: 2.3486,
    adresse: '7 bis rue Michelet',
    ville: 'Saint-Ouen',
    code_postal: '93400',
    score: 78,
    score_breakdown: [
      { label: 'Potentiel commercial', contribution: 18, detail: 'Baisse de prix -7%' },
      { label: 'Risque locatif / réglementaire', contribution: 12 },
      { label: 'Qualité donnée', contribution: 10 },
    ],
    priority: 'moyenne',
    status: 'nouveau',
    bien_id: 'bien_093_006',
    assignee_id: 'user_sophie',
    explanation_short: 'Baisse de prix -7% · DPE F',
    tags: ['nouveau'],
    dpe_payload: {
      classe_dpe: 'F',
      date_dpe: '2023-03-19',
      type_bien: 'appartement',
      surface_m2: 55,
      usage_probable: 'residence_principale',
      zone_tendue: true,
      potentiel_gain_classe: 2,
      loyer_ou_valeur_apres_travaux_pct: 12,
      risque_reglementaire: 'moyen',
      conso_energie_kwh_m2_an: 389,
      ges_kgco2_m2_an: 61,
      travaux_estimes_euros: 18000,
    },
    detected_at: '2026-04-11T09:00:00Z',
    created_at: '2026-04-11T09:00:00Z',
    updated_at: '2026-04-22T09:00:00Z',
  },
  {
    signal_id: 'sgn_dpe_007',
    source: 'dpe',
    type: 'bailleur_a_arbitrer',
    kind: 'business',
    support_types: ['risque_locatif'],
    title: 'Bailleur à arbitrer',
    subtitle: 'Appartement · 73 m²',
    geo_precision: 'exacte',
    lat: 48.8641,
    lon: 2.4384,
    adresse: '31 rue de Paris',
    ville: 'Montreuil',
    code_postal: '93100',
    score: 86,
    score_breakdown: [
      { label: 'Risque locatif / réglementaire', contribution: 20 },
      { label: 'Potentiel commercial', contribution: 15 },
      { label: 'Potentiel revalorisation', contribution: 12 },
    ],
    priority: 'haute',
    status: 'en_cours',
    bien_id: 'bien_093_007',
    assignee_id: 'user_thomas',
    explanation_short: 'Décote locative · DPE G · travaux à prévoir',
    tags: ['en_cours'],
    dpe_payload: {
      classe_dpe: 'G',
      date_dpe: '2023-12-05',
      type_bien: 'appartement',
      surface_m2: 73,
      usage_probable: 'locatif',
      zone_tendue: true,
      potentiel_gain_classe: 2,
      loyer_ou_valeur_apres_travaux_pct: 18,
      risque_reglementaire: 'fort',
      conso_energie_kwh_m2_an: 501,
      ges_kgco2_m2_an: 79,
      travaux_estimes_euros: 29000,
    },
    detected_at: '2026-04-09T09:00:00Z',
    created_at: '2026-04-09T09:00:00Z',
    updated_at: '2026-04-21T09:00:00Z',
  },
  {
    signal_id: 'sgn_dpe_008',
    source: 'dpe',
    type: 'opportunite_investisseur',
    kind: 'business',
    title: 'Opportunité investisseur',
    subtitle: 'Immeuble · 8 lots',
    geo_precision: 'exacte',
    lat: 48.9105,
    lon: 2.3493,
    adresse: '23 rue de Lorraine',
    ville: 'Saint-Ouen',
    code_postal: '93400',
    score: 81,
    score_breakdown: [
      { label: 'Potentiel commercial', contribution: 20, detail: 'Immeuble mal classé' },
      { label: 'Potentiel revalorisation', contribution: 18 },
      { label: 'Intensité marché zone', contribution: 12 },
    ],
    priority: 'haute',
    status: 'nouveau',
    bien_id: 'bien_093_008',
    assignee_id: 'user_mehdi',
    explanation_short: 'Immeuble collectif mal classé · angle arbitrage',
    tags: ['nouveau'],
    dpe_payload: {
      classe_dpe: 'F',
      date_dpe: '2023-04-01',
      type_bien: 'appartement',
      surface_m2: 520,
      usage_probable: 'locatif',
      zone_tendue: true,
      potentiel_gain_classe: 2,
      loyer_ou_valeur_apres_travaux_pct: 15,
      risque_reglementaire: 'moyen',
      conso_energie_kwh_m2_an: 362,
      ges_kgco2_m2_an: 58,
      travaux_estimes_euros: 180000,
    },
    detected_at: '2026-04-08T09:00:00Z',
    created_at: '2026-04-08T09:00:00Z',
    updated_at: '2026-04-20T09:00:00Z',
  },
];
