import { SignalDVF } from '../types';

// Fixtures DVF — couvrent les 7 types V1 sur Paris + petite couronne
export const signauxDvf: SignalDVF[] = [
  {
    signal_id: 'sgn_dvf_001',
    source: 'dvf',
    type: 'detention_longue',
    title: 'Détention longue',
    subtitle: 'Appartement · 145 m² · 5 pièces',
    geo_precision: 'exacte',
    lat: 48.8859,
    lon: 2.3419,
    adresse: '15 Rue de la Tour d\'Auvergne',
    ville: 'Paris 9e',
    code_postal: '75009',
    quartier: 'Faubourg-Montmartre',
    is_territorial: false,
    score: 92,
    score_breakdown: [
      { label: 'Fraîcheur du signal', contribution: 20, detail: 'Détecté il y a 1 jour' },
      { label: 'Intérêt du pattern', contribution: 20, detail: 'Détention > 15 ans' },
      { label: 'Intensité marché zone', contribution: 15, detail: 'Secteur en tension forte' },
      { label: 'Proximité portefeuille', contribution: 10, detail: '2 biens à < 500m' },
    ],
    priority: 'haute',
    status: 'nouveau',
    bien_id: 'bien_075_001',
    assignee_id: 'user_paul',
    explanation_short: 'Détention supérieure à 15 ans (4 ans 2 mois depuis dernière mutation)',
    explanation_long: 'Le bien a été détenu plus de 4 ans sans revente. Ce type de détention est statistiquement corrélé à une motivation accrue à la vente.',
    tags: ['chaud', 'nouveau'],
    dvf_payload: {
      date_vente: '2020-02-12',
      prix_vente: 1250000,
      prix_m2: 12345,
      surface_m2: 101,
      type_bien: 'appartement',
      type_acquereur: 'particulier',
      duree_detention_ans: 4,
      duree_detention_mois: 2,
      nb_mutations_10_ans: 1,
      ecart_vs_marche_pct: 5,
      prix_median_secteur: 11780,
      volume_mutations_30j: 42,
      delai_median_vente_j: 46,
    },
    detected_at: '2026-04-23T09:41:00Z',
    created_at: '2026-04-23T09:41:00Z',
    updated_at: '2026-04-24T08:30:00Z',
  },
  {
    signal_id: 'sgn_dvf_002',
    source: 'dvf',
    type: 'revente_rapide',
    title: 'Revente rapide',
    subtitle: 'Appartement · 54 m² · 2 pièces',
    geo_precision: 'exacte',
    lat: 48.9015,
    lon: 2.2475,
    adresse: '8 Avenue Jean Jaurès',
    ville: 'Clamart',
    code_postal: '92140',
    is_territorial: false,
    score: 85,
    score_breakdown: [
      { label: 'Fraîcheur du signal', contribution: 25, detail: 'Vente il y a 1 mois' },
      { label: 'Intérêt du pattern', contribution: 18, detail: 'Revente en 7 mois' },
      { label: 'Exploitabilité commerciale', contribution: 18, detail: 'Acquéreur particulier' },
      { label: 'Qualité donnée', contribution: 10 },
    ],
    priority: 'haute',
    status: 'nouveau',
    bien_id: 'bien_092_002',
    assignee_id: 'user_clara',
    explanation_short: 'Revente 7 mois après achat (flip probable)',
    tags: ['nouveau', 'flip'],
    dvf_payload: {
      date_vente: '2024-04-22',
      prix_vente: 610000,
      prix_m2: 11296,
      surface_m2: 54,
      type_bien: 'appartement',
      type_acquereur: 'particulier',
      duree_detention_ans: 0,
      duree_detention_mois: 7,
      nb_mutations_10_ans: 3,
      ecart_vs_marche_pct: 12,
      prix_median_secteur: 10080,
    },
    detected_at: '2026-04-20T14:10:00Z',
    created_at: '2026-04-20T14:10:00Z',
    updated_at: '2026-04-22T10:00:00Z',
  },
  {
    signal_id: 'sgn_dvf_003',
    source: 'dvf',
    type: 'ecart_marche',
    title: 'Écart vs marché',
    subtitle: 'Appartement · 68 m² · 3 pièces',
    geo_precision: 'exacte',
    lat: 48.8566,
    lon: 2.3833,
    adresse: '27 Boulevard Voltaire',
    ville: 'Paris 11e',
    code_postal: '75011',
    is_territorial: false,
    score: 78,
    score_breakdown: [
      { label: 'Intérêt du pattern', contribution: 20, detail: 'Décote -9% vs médiane' },
      { label: 'Intensité marché zone', contribution: 15, detail: 'Tension forte' },
      { label: 'Fraîcheur du signal', contribution: 15, detail: 'Vente < 60j' },
      { label: 'Proximité portefeuille', contribution: 10 },
    ],
    priority: 'moyenne',
    status: 'a_qualifier',
    bien_id: 'bien_075_003',
    assignee_id: 'user_mehdi',
    explanation_short: 'Prix -9% sous marché (secteur 10 588 €/m²) — sous-évalué',
    tags: ['a_analyser', 'decote'],
    dvf_payload: {
      date_vente: '2024-03-04',
      prix_vente: 720000,
      prix_m2: 10588,
      surface_m2: 68,
      type_bien: 'appartement',
      type_acquereur: 'particulier',
      duree_detention_ans: 3,
      duree_detention_mois: 1,
      nb_mutations_10_ans: 2,
      ecart_vs_marche_pct: -9,
      prix_median_secteur: 11640,
    },
    detected_at: '2026-04-18T11:22:00Z',
    created_at: '2026-04-18T11:22:00Z',
    updated_at: '2026-04-23T15:00:00Z',
  },
  {
    signal_id: 'sgn_dvf_004',
    source: 'dvf',
    type: 'detention_longue',
    title: 'Détention longue',
    subtitle: 'Maison · 98 m² · 4 pièces',
    geo_precision: 'exacte',
    lat: 48.9255,
    lon: 2.4622,
    adresse: '3 Rue du Général Leclerc',
    ville: 'Bois-Colombes',
    code_postal: '92270',
    is_territorial: false,
    score: 75,
    score_breakdown: [
      { label: 'Intérêt du pattern', contribution: 20, detail: 'Détention 14 ans' },
      { label: 'Intensité marché zone', contribution: 15 },
      { label: 'Qualité donnée', contribution: 10 },
    ],
    priority: 'moyenne',
    status: 'nouveau',
    bien_id: 'bien_092_004',
    assignee_id: 'user_alice',
    explanation_short: 'Dernière mutation il y a 14 ans',
    tags: ['nouveau'],
    dvf_payload: {
      date_vente: '2010-11-18',
      prix_vente: 980000,
      prix_m2: 8167,
      surface_m2: 98,
      type_bien: 'maison',
      type_acquereur: 'particulier',
      duree_detention_ans: 14,
      duree_detention_mois: 6,
      nb_mutations_10_ans: 0,
      ecart_vs_marche_pct: 2,
      prix_median_secteur: 7980,
    },
    detected_at: '2026-04-15T09:00:00Z',
    created_at: '2026-04-15T09:00:00Z',
    updated_at: '2026-04-21T09:00:00Z',
  },
  {
    signal_id: 'sgn_dvf_005',
    source: 'dvf',
    type: 'cycle_revente_regulier',
    title: 'Cycle régulier',
    subtitle: 'Appartement · 66 m² · 3 pièces',
    geo_precision: 'exacte',
    lat: 48.8198,
    lon: 2.3832,
    adresse: '12 Rue Danton',
    ville: 'Ivry-sur-Seine',
    code_postal: '94200',
    is_territorial: false,
    score: 72,
    score_breakdown: [
      { label: 'Intérêt du pattern', contribution: 18, detail: 'Cycle médian 3,6 ans' },
      { label: 'Fraîcheur du signal', contribution: 15 },
      { label: 'Qualité donnée', contribution: 10 },
    ],
    priority: 'moyenne',
    status: 'a_qualifier',
    bien_id: 'bien_094_005',
    assignee_id: 'user_sophie',
    explanation_short: '3 mutations en 10 ans — cycle de revente régulier',
    tags: ['a_analyser'],
    dvf_payload: {
      date_vente: '2023-05-12',
      prix_vente: 430000,
      prix_m2: 6515,
      surface_m2: 66,
      type_bien: 'appartement',
      type_acquereur: 'particulier',
      duree_detention_ans: 2,
      duree_detention_mois: 0,
      nb_mutations_10_ans: 3,
      ecart_vs_marche_pct: 3,
      prix_median_secteur: 6320,
    },
    detected_at: '2026-04-12T10:00:00Z',
    created_at: '2026-04-12T10:00:00Z',
    updated_at: '2026-04-22T09:00:00Z',
  },
  {
    signal_id: 'sgn_dvf_006',
    source: 'dvf',
    type: 'vente_proche',
    title: 'Vente proche',
    subtitle: 'Appartement · 60 m² · 3 pièces',
    geo_precision: 'exacte',
    lat: 48.848,
    lon: 2.3498,
    adresse: '5 Rue des Écoles',
    ville: 'Paris 5e',
    code_postal: '75005',
    is_territorial: false,
    score: 68,
    score_breakdown: [
      { label: 'Fraîcheur du signal', contribution: 25, detail: 'Vente il y a 2 mois' },
      { label: 'Intensité marché zone', contribution: 15 },
      { label: 'Qualité donnée', contribution: 10 },
    ],
    priority: 'moyenne',
    status: 'nouveau',
    bien_id: 'bien_075_006',
    assignee_id: 'user_thomas',
    explanation_short: 'Vente récente dans le secteur — comparable exploitable',
    tags: ['nouveau', 'comparable'],
    dvf_payload: {
      date_vente: '2025-02-05',
      prix_vente: 825000,
      prix_m2: 13750,
      surface_m2: 60,
      type_bien: 'appartement',
      type_acquereur: 'particulier',
      duree_detention_ans: 8,
      duree_detention_mois: 3,
      nb_mutations_10_ans: 1,
      ecart_vs_marche_pct: 7,
      prix_median_secteur: 12850,
    },
    detected_at: '2026-04-10T08:00:00Z',
    created_at: '2026-04-10T08:00:00Z',
    updated_at: '2026-04-20T09:00:00Z',
  },
  {
    signal_id: 'sgn_dvf_007',
    source: 'dvf',
    type: 'ecart_marche',
    title: 'Écart vs marché',
    subtitle: 'Appartement · 127 m² · 5 pièces',
    geo_precision: 'exacte',
    lat: 48.8436,
    lon: 2.4363,
    adresse: '41 Avenue Gambetta',
    ville: 'Vincennes',
    code_postal: '94300',
    is_territorial: false,
    score: 65,
    score_breakdown: [
      { label: 'Intérêt du pattern', contribution: 20, detail: 'Écart -4% vs médiane' },
      { label: 'Qualité donnée', contribution: 10 },
    ],
    priority: 'moyenne',
    status: 'en_cours',
    bien_id: 'bien_094_007',
    assignee_id: 'user_emilie',
    explanation_short: 'Prix légèrement sous marché (-4%)',
    tags: ['en_suivi'],
    dvf_payload: {
      date_vente: '2024-01-09',
      prix_vente: 1150000,
      prix_m2: 9055,
      surface_m2: 127,
      type_bien: 'appartement',
      type_acquereur: 'particulier',
      duree_detention_ans: 3,
      duree_detention_mois: 5,
      nb_mutations_10_ans: 2,
      ecart_vs_marche_pct: -4,
      prix_median_secteur: 9440,
    },
    detected_at: '2026-04-08T09:00:00Z',
    created_at: '2026-04-08T09:00:00Z',
    updated_at: '2026-04-20T09:00:00Z',
  },
  {
    signal_id: 'sgn_dvf_008',
    source: 'dvf',
    type: 'revente_rapide',
    title: 'Revente rapide',
    subtitle: 'Appartement · 69 m² · 3 pièces',
    geo_precision: 'exacte',
    lat: 48.7942,
    lon: 2.2386,
    adresse: '93 Rue de Silly',
    ville: 'Boulogne-Billancourt',
    code_postal: '92100',
    is_territorial: false,
    score: 64,
    score_breakdown: [
      { label: 'Fraîcheur du signal', contribution: 20 },
      { label: 'Intérêt du pattern', contribution: 14, detail: 'Revente 8 mois' },
      { label: 'Qualité donnée', contribution: 10 },
    ],
    priority: 'moyenne',
    status: 'nouveau',
    bien_id: 'bien_092_008',
    assignee_id: 'user_paul',
    explanation_short: 'Revente 8 mois après achat',
    tags: ['nouveau'],
    dvf_payload: {
      date_vente: '2025-02-28',
      prix_vente: 550000,
      prix_m2: 7971,
      surface_m2: 69,
      type_bien: 'appartement',
      type_acquereur: 'sci',
      duree_detention_ans: 0,
      duree_detention_mois: 8,
      nb_mutations_10_ans: 2,
      ecart_vs_marche_pct: 8,
      prix_median_secteur: 7380,
    },
    detected_at: '2026-04-07T09:00:00Z',
    created_at: '2026-04-07T09:00:00Z',
    updated_at: '2026-04-19T09:00:00Z',
  },
  {
    signal_id: 'sgn_dvf_009',
    source: 'dvf',
    type: 'detention_longue',
    title: 'Détention longue',
    subtitle: 'Maison · 125 m² · 5 pièces',
    geo_precision: 'exacte',
    lat: 48.7787,
    lon: 2.2131,
    adresse: '2 Allée des Tilleuls',
    ville: 'Sèvres',
    code_postal: '92310',
    is_territorial: false,
    score: 63,
    score_breakdown: [
      { label: 'Intérêt du pattern', contribution: 18, detail: 'Détention 5 ans' },
      { label: 'Qualité donnée', contribution: 10 },
    ],
    priority: 'moyenne',
    status: 'a_qualifier',
    bien_id: 'bien_092_009',
    assignee_id: 'user_clara',
    explanation_short: 'Détention 5 ans — signal de maturité potentielle',
    tags: ['a_contacter'],
    dvf_payload: {
      date_vente: '2020-01-07',
      prix_vente: 1480000,
      prix_m2: 11840,
      surface_m2: 125,
      type_bien: 'maison',
      type_acquereur: 'particulier',
      duree_detention_ans: 5,
      duree_detention_mois: 0,
      nb_mutations_10_ans: 1,
      ecart_vs_marche_pct: 1,
      prix_median_secteur: 11720,
    },
    detected_at: '2026-04-05T09:00:00Z',
    created_at: '2026-04-05T09:00:00Z',
    updated_at: '2026-04-20T09:00:00Z',
  },
  {
    signal_id: 'sgn_dvf_010',
    source: 'dvf',
    type: 'cycle_revente_regulier',
    title: 'Cycle régulier',
    subtitle: 'Appartement · 62 m² · 3 pièces',
    geo_precision: 'exacte',
    lat: 48.8797,
    lon: 2.4131,
    adresse: '18 Rue de Paris',
    ville: 'Les Lilas',
    code_postal: '93260',
    is_territorial: false,
    score: 61,
    score_breakdown: [
      { label: 'Intérêt du pattern', contribution: 16, detail: 'Cycle stable 2 ans' },
      { label: 'Qualité donnée', contribution: 10 },
    ],
    priority: 'moyenne',
    status: 'a_qualifier',
    bien_id: 'bien_093_010',
    assignee_id: 'user_mehdi',
    explanation_short: 'Cycle de revente stable, dernière mutation 2 ans',
    tags: ['a_analyser'],
    dvf_payload: {
      date_vente: '2023-06-23',
      prix_vente: 395000,
      prix_m2: 6371,
      surface_m2: 62,
      type_bien: 'appartement',
      type_acquereur: 'particulier',
      duree_detention_ans: 2,
      duree_detention_mois: 1,
      nb_mutations_10_ans: 4,
      ecart_vs_marche_pct: 0,
      prix_median_secteur: 6380,
    },
    detected_at: '2026-04-03T09:00:00Z',
    created_at: '2026-04-03T09:00:00Z',
    updated_at: '2026-04-18T09:00:00Z',
  },
  {
    signal_id: 'sgn_dvf_011',
    source: 'dvf',
    type: 'zone_rotation_forte',
    title: 'Zone à rotation forte',
    subtitle: 'Secteur · 11e arrondissement · Roquette',
    geo_precision: 'iris',
    lat: 48.8556,
    lon: 2.3798,
    adresse: undefined,
    ville: 'Paris 11e',
    code_postal: '75011',
    quartier: 'Roquette',
    is_territorial: true,
    score: 84,
    score_breakdown: [
      { label: 'Intensité marché zone', contribution: 25, detail: 'Rotation 23% / an' },
      { label: 'Fraîcheur du signal', contribution: 18 },
      { label: 'Intérêt du pattern', contribution: 15 },
    ],
    priority: 'haute',
    status: 'nouveau',
    assignee_id: 'user_paul',
    explanation_short: '156 mutations sur 12 mois · +28% vs moyenne Paris',
    tags: ['zone', 'chaud'],
    dvf_payload: {
      volume_mutations_30j: 42,
      prix_median_secteur: 9420,
      ecart_vs_marche_pct: 18,
    },
    detected_at: '2026-04-22T09:00:00Z',
    created_at: '2026-04-22T09:00:00Z',
    updated_at: '2026-04-24T08:00:00Z',
  },
  {
    signal_id: 'sgn_dvf_012',
    source: 'dvf',
    type: 'comparables_denses',
    title: 'Comparables denses',
    subtitle: 'Secteur · Boulogne-Billancourt centre',
    geo_precision: 'iris',
    lat: 48.8351,
    lon: 2.2412,
    adresse: undefined,
    ville: 'Boulogne-Billancourt',
    code_postal: '92100',
    is_territorial: true,
    score: 62,
    score_breakdown: [
      { label: 'Intensité marché zone', contribution: 18, detail: '127 comparables / 500m' },
      { label: 'Qualité donnée', contribution: 10 },
    ],
    priority: 'moyenne',
    status: 'nouveau',
    assignee_id: 'user_emilie',
    explanation_short: '127 comparables sur 500m — liquidité élevée',
    tags: ['zone', 'comparables'],
    dvf_payload: {
      volume_mutations_30j: 23,
      prix_median_secteur: 9200,
    },
    detected_at: '2026-04-19T09:00:00Z',
    created_at: '2026-04-19T09:00:00Z',
    updated_at: '2026-04-22T09:00:00Z',
  },
];
