import { ZoneRadar } from '../types';

export const zonesRadar: ZoneRadar[] = [
  {
    zone_id: 'zone_93200_centre',
    label: 'Saint-Denis Centre',
    type: 'quartier',
    ville: 'Saint-Denis',
    code_postal: '93200',
    score_zone: 92,
    nb_signaux_total: 92,
    nb_signaux_annonce: 24,
    nb_signaux_dvf: 36,
    nb_signaux_dpe: 32,
    nb_biens_concernes: 68,
    tendance_7j: 'hausse',
    tendance_30j: 'hausse',
    evolution_pct: 14,
    priorite: 'chaude',
    reasons: [
      'Forte dynamique de mutations sur les 30 derniers jours',
      'Hausse des nouveaux DPE défavorables (+18%)',
      'Demande locative soutenue',
      'Prix au m² en progression',
    ],
    centroid_lat: 48.9362,
    centroid_lon: 2.3574,
  },
  {
    zone_id: 'zone_93300_sud',
    label: 'Aubervilliers Sud',
    type: 'quartier',
    ville: 'Aubervilliers',
    code_postal: '93300',
    score_zone: 67,
    nb_signaux_total: 67,
    nb_signaux_annonce: 14,
    nb_signaux_dvf: 28,
    nb_signaux_dpe: 25,
    nb_biens_concernes: 48,
    tendance_7j: 'hausse',
    tendance_30j: 'stable',
    evolution_pct: 6,
    priorite: 'interessante',
    reasons: [
      'Volume mutations élevé',
      'Poche de passoires thermiques',
      'Projets urbains en cours',
    ],
    centroid_lat: 48.9148,
    centroid_lon: 2.3855,
  },
  {
    zone_id: 'zone_75011_roquette',
    label: 'Roquette (11e)',
    type: 'quartier',
    ville: 'Paris 11e',
    code_postal: '75011',
    score_zone: 48,
    nb_signaux_total: 48,
    nb_signaux_annonce: 18,
    nb_signaux_dvf: 20,
    nb_signaux_dpe: 10,
    nb_biens_concernes: 40,
    tendance_7j: 'stable',
    tendance_30j: 'hausse',
    evolution_pct: 9,
    priorite: 'interessante',
    reasons: [
      'Rotation forte (23%/an)',
      'Prix/m² en progression',
      'Baisses de prix fréquentes sur annonces',
    ],
    centroid_lat: 48.8556,
    centroid_lon: 2.3798,
  },
  {
    zone_id: 'zone_93400_centre',
    label: 'Saint-Ouen Centre',
    type: 'quartier',
    ville: 'Saint-Ouen',
    code_postal: '93400',
    score_zone: 31,
    nb_signaux_total: 31,
    nb_signaux_annonce: 9,
    nb_signaux_dvf: 12,
    nb_signaux_dpe: 10,
    nb_biens_concernes: 26,
    tendance_7j: 'hausse',
    tendance_30j: 'stable',
    evolution_pct: 4,
    priorite: 'interessante',
    reasons: ['Secteur en renouveau', 'Mutations ponctuelles exploitables'],
    centroid_lat: 48.9105,
    centroid_lon: 2.3493,
  },
  {
    zone_id: 'zone_92100_centre',
    label: 'Boulogne-Billancourt Centre',
    type: 'quartier',
    ville: 'Boulogne-Billancourt',
    code_postal: '92100',
    score_zone: 24,
    nb_signaux_total: 24,
    nb_signaux_annonce: 6,
    nb_signaux_dvf: 12,
    nb_signaux_dpe: 6,
    nb_biens_concernes: 20,
    tendance_7j: 'stable',
    tendance_30j: 'stable',
    evolution_pct: 1,
    priorite: 'froide',
    reasons: ['Marché liquide mais peu de signaux chauds'],
    centroid_lat: 48.8351,
    centroid_lon: 2.2412,
  },
  {
    zone_id: 'zone_93100_centre',
    label: 'Montreuil',
    type: 'quartier',
    ville: 'Montreuil',
    code_postal: '93100',
    score_zone: 21,
    nb_signaux_total: 21,
    nb_signaux_annonce: 7,
    nb_signaux_dvf: 8,
    nb_signaux_dpe: 6,
    nb_biens_concernes: 18,
    tendance_7j: 'stable',
    tendance_30j: 'hausse',
    evolution_pct: 3,
    priorite: 'froide',
    reasons: ['Quelques DPE critiques', 'Faible activité DVF'],
    centroid_lat: 48.8641,
    centroid_lon: 2.4384,
  },
];
