import { AgenceConcurrente } from '../types';

const now = new Date('2026-04-24T14:00:00Z');
const hoursAgo = (h: number) => new Date(now.getTime() - h * 3_600_000).toISOString();
const daysAgo = (d: number) => new Date(now.getTime() - d * 86_400_000).toISOString();

export const AGENCES: AgenceConcurrente[] = [
  {
    id: 'ag_001',
    name: 'Agence Métropole',
    siren: '523489612',
    carte_t: 'CPI 7501 2018 000 034 567',
    adresse: '36 rue de Vaugirard',
    ville: 'Paris 15e',
    code_postal: '75015',
    latitude: 48.8466,
    longitude: 2.3125,
    logo_initials: 'AM',
    logo_color: '#7C3AED',
    zones: [
      { zone_id: 'z_15', label: 'Paris 15e', strength: 'forte', stock_actif: 86, part_de_marche: 0.12, evolution_part_30d: 1.2 },
      { zone_id: 'z_16', label: 'Paris 16e', strength: 'moyenne', stock_actif: 42, part_de_marche: 0.08, evolution_part_30d: 0 },
      { zone_id: 'z_7', label: 'Paris 7e', strength: 'faible', stock_actif: 14, part_de_marche: 0.04, evolution_part_30d: -0.3 },
      { zone_id: 'z_6', label: 'Paris 6e', strength: 'faible', stock_actif: 10, part_de_marche: 0.03, evolution_part_30d: 0.1 },
    ],
    zone_principale: 'Paris 15e',
    stock_actif: 126,
    nouvelles_annonces_7d: 8,
    nouvelles_annonces_30d: 31,
    baisses_prix_30d: 4,
    annonces_anciennes_count: 12,
    delai_moyen_jours: 34,
    prix_moyen_m2: 8420,
    loyer_moyen_m2: 27,
    types_biens_dominants: ['T2', 'T3', 'Studios'],
    biens_similaires_count: 18,
    mandats_simples_concurrents_count: 3,
    has_mandat_simple_sous_pression: true,
    followed: true,
    status_suivi: 'Mandat simple sous pression',
    alertes_actives: ['al_017'],
    last_event_at: hoursAgo(3),
    last_event_type: 'price_drop',
    last_event_label: 'Baisse de prix',
    created_at: daysAgo(54),
    updated_at: hoursAgo(3),
  },
  {
    id: 'ag_002',
    name: 'Haussmann & Belliard',
    siren: '401235987',
    adresse: '12 rue Belliard',
    ville: 'Paris 16e',
    code_postal: '75116',
    latitude: 48.8617,
    longitude: 2.2727,
    logo_initials: 'HB',
    logo_color: '#F59E0B',
    zones: [
      { zone_id: 'z_16', label: 'Paris 16e', strength: 'forte', stock_actif: 72, part_de_marche: 0.14, evolution_part_30d: 0.8 },
      { zone_id: 'z_17', label: 'Paris 17e', strength: 'moyenne', stock_actif: 22, part_de_marche: 0.05, evolution_part_30d: 0.2 },
      { zone_id: 'z_8', label: 'Paris 8e', strength: 'faible', stock_actif: 4, part_de_marche: 0.02, evolution_part_30d: 0 },
    ],
    zone_principale: 'Paris 16e',
    stock_actif: 98,
    nouvelles_annonces_7d: 6,
    nouvelles_annonces_30d: 24,
    baisses_prix_30d: 2,
    annonces_anciennes_count: 10,
    delai_moyen_jours: 42,
    prix_moyen_m2: 9150,
    types_biens_dominants: ['T3', 'T4', 'Appartements Haussmanniens'],
    biens_similaires_count: 12,
    mandats_simples_concurrents_count: 1,
    has_mandat_simple_sous_pression: false,
    followed: true,
    status_suivi: 'Concurrent détecté',
    alertes_actives: [],
    last_event_at: daysAgo(1),
    last_event_type: 'new_listing',
    last_event_label: 'Nouvelle annonce',
    created_at: daysAgo(42),
    updated_at: daysAgo(1),
  },
  {
    id: 'ag_003',
    name: 'Rive Left Immobilier',
    siren: '389412356',
    adresse: '8 rue des Saints-Pères',
    ville: 'Paris 7e',
    code_postal: '75007',
    latitude: 48.8556,
    longitude: 2.3301,
    logo_initials: 'RL',
    logo_color: '#EF4444',
    zones: [
      { zone_id: 'z_7', label: 'Paris 7e', strength: 'forte', stock_actif: 55, part_de_marche: 0.09, evolution_part_30d: 0.5 },
      { zone_id: 'z_6', label: 'Paris 6e', strength: 'moyenne', stock_actif: 15, part_de_marche: 0.04, evolution_part_30d: 0 },
      { zone_id: 'z_15', label: 'Paris 15e', strength: 'faible', stock_actif: 5, part_de_marche: 0.01, evolution_part_30d: -0.1 },
    ],
    zone_principale: 'Paris 7e',
    stock_actif: 75,
    nouvelles_annonces_7d: 5,
    nouvelles_annonces_30d: 18,
    baisses_prix_30d: 1,
    annonces_anciennes_count: 6,
    delai_moyen_jours: 28,
    prix_moyen_m2: 9820,
    types_biens_dominants: ['T2', 'T3'],
    biens_similaires_count: 9,
    mandats_simples_concurrents_count: 0,
    has_mandat_simple_sous_pression: false,
    followed: true,
    status_suivi: 'Sous surveillance',
    alertes_actives: [],
    last_event_at: daysAgo(1),
    last_event_type: 'price_drop',
    last_event_label: 'Baisse de prix',
    created_at: daysAgo(30),
    updated_at: daysAgo(1),
  },
  {
    id: 'ag_004',
    name: 'Bastille & Voltaire',
    siren: '522178456',
    adresse: '11 bd Voltaire',
    ville: 'Paris 11e',
    code_postal: '75011',
    latitude: 48.8573,
    longitude: 2.3785,
    logo_initials: 'BV',
    logo_color: '#10B981',
    zones: [
      { zone_id: 'z_11', label: 'Paris 11e', strength: 'forte', stock_actif: 48, part_de_marche: 0.11, evolution_part_30d: 0.7 },
      { zone_id: 'z_12', label: 'Paris 12e', strength: 'moyenne', stock_actif: 12, part_de_marche: 0.04, evolution_part_30d: 0 },
      { zone_id: 'z_20', label: 'Paris 20e', strength: 'faible', stock_actif: 4, part_de_marche: 0.02, evolution_part_30d: 0.1 },
    ],
    zone_principale: 'Paris 11e',
    stock_actif: 64,
    nouvelles_annonces_7d: 4,
    nouvelles_annonces_30d: 14,
    baisses_prix_30d: 2,
    annonces_anciennes_count: 5,
    delai_moyen_jours: 31,
    prix_moyen_m2: 8210,
    types_biens_dominants: ['T2', 'Studios'],
    biens_similaires_count: 7,
    mandats_simples_concurrents_count: 0,
    has_mandat_simple_sous_pression: false,
    followed: true,
    status_suivi: 'Sous surveillance',
    alertes_actives: [],
    last_event_at: daysAgo(2),
    last_event_type: 'price_drop',
    last_event_label: 'Baisse de prix',
    created_at: daysAgo(25),
    updated_at: daysAgo(2),
  },
  {
    id: 'ag_005',
    name: 'Boulogne Gestion',
    siren: '789234561',
    adresse: '44 rue du Château',
    ville: 'Boulogne-Billancourt',
    code_postal: '92100',
    latitude: 48.8345,
    longitude: 2.2407,
    logo_initials: 'BG',
    logo_color: '#3B82F6',
    zones: [
      { zone_id: 'z_boulogne', label: 'Boulogne', strength: 'forte', stock_actif: 60, part_de_marche: 0.13, evolution_part_30d: 0.9 },
      { zone_id: 'z_16', label: 'Paris 16e', strength: 'faible', stock_actif: 8, part_de_marche: 0.02, evolution_part_30d: 0 },
    ],
    zone_principale: 'Boulogne-Billancourt',
    stock_actif: 83,
    nouvelles_annonces_7d: 6,
    nouvelles_annonces_30d: 22,
    baisses_prix_30d: 3,
    annonces_anciennes_count: 9,
    delai_moyen_jours: 35,
    prix_moyen_m2: 7950,
    types_biens_dominants: ['T3', 'T4', 'Maisons'],
    biens_similaires_count: 11,
    mandats_simples_concurrents_count: 1,
    has_mandat_simple_sous_pression: false,
    followed: true,
    status_suivi: 'Concurrent détecté',
    alertes_actives: [],
    last_event_at: daysAgo(2),
    last_event_type: 'new_listing',
    last_event_label: 'Nouvelle annonce',
    created_at: daysAgo(60),
    updated_at: daysAgo(2),
  },
  {
    id: 'ag_006',
    name: 'Lyon Confluence Immo',
    siren: '311458922',
    ville: 'Lyon 2e',
    code_postal: '69002',
    latitude: 45.7489,
    longitude: 4.8255,
    logo_initials: 'LC',
    logo_color: '#8B5CF6',
    zones: [
      { zone_id: 'z_lyon2', label: 'Lyon 2e', strength: 'forte', stock_actif: 62, part_de_marche: 0.15, evolution_part_30d: 1.5 },
      { zone_id: 'z_lyon3', label: 'Lyon 3e', strength: 'moyenne', stock_actif: 30, part_de_marche: 0.06, evolution_part_30d: 0.4 },
      { zone_id: 'z_lyon7', label: 'Lyon 7e', strength: 'faible', stock_actif: 20, part_de_marche: 0.04, evolution_part_30d: 0 },
    ],
    zone_principale: 'Lyon 2e',
    stock_actif: 112,
    nouvelles_annonces_7d: 9,
    nouvelles_annonces_30d: 35,
    baisses_prix_30d: 3,
    annonces_anciennes_count: 14,
    delai_moyen_jours: 37,
    prix_moyen_m2: 5630,
    types_biens_dominants: ['T2', 'T3'],
    biens_similaires_count: 14,
    mandats_simples_concurrents_count: 2,
    has_mandat_simple_sous_pression: true,
    followed: true,
    status_suivi: 'Mandat simple sous pression',
    alertes_actives: [],
    last_event_at: hoursAgo(6),
    last_event_type: 'price_drop',
    last_event_label: 'Baisse de prix',
    created_at: daysAgo(38),
    updated_at: hoursAgo(6),
  },
  {
    id: 'ag_007',
    name: 'Lyon Patrimoine',
    siren: '522789456',
    ville: 'Lyon 6e',
    code_postal: '69006',
    latitude: 45.7707,
    longitude: 4.8521,
    logo_initials: 'LP',
    logo_color: '#EC4899',
    zones: [
      { zone_id: 'z_lyon6', label: 'Lyon 6e', strength: 'forte', stock_actif: 42, part_de_marche: 0.1, evolution_part_30d: 0.6 },
      { zone_id: 'z_lyon3', label: 'Lyon 3e', strength: 'moyenne', stock_actif: 16, part_de_marche: 0.04, evolution_part_30d: 0 },
      { zone_id: 'z_lyon9', label: 'Lyon 9e', strength: 'faible', stock_actif: 9, part_de_marche: 0.03, evolution_part_30d: 0 },
    ],
    zone_principale: 'Lyon 6e',
    stock_actif: 67,
    nouvelles_annonces_7d: 3,
    nouvelles_annonces_30d: 12,
    baisses_prix_30d: 1,
    annonces_anciennes_count: 5,
    delai_moyen_jours: 40,
    prix_moyen_m2: 6120,
    types_biens_dominants: ['T3', 'Appartements anciens'],
    biens_similaires_count: 8,
    mandats_simples_concurrents_count: 0,
    has_mandat_simple_sous_pression: false,
    followed: true,
    status_suivi: 'Sous surveillance',
    alertes_actives: [],
    last_event_at: daysAgo(3),
    last_event_type: 'price_drop',
    last_event_label: 'Baisse de prix',
    created_at: daysAgo(28),
    updated_at: daysAgo(3),
  },
  {
    id: 'ag_008',
    name: 'Bordeaux Actifs',
    siren: '422156789',
    ville: 'Bordeaux Chartrons',
    code_postal: '33000',
    latitude: 44.8512,
    longitude: -0.5702,
    logo_initials: 'BA',
    logo_color: '#DC2626',
    zones: [
      { zone_id: 'z_bdx_chart', label: 'Chartrons', strength: 'forte', stock_actif: 48, part_de_marche: 0.12, evolution_part_30d: 0.9 },
      { zone_id: 'z_bdx_caud', label: 'Caudéran', strength: 'moyenne', stock_actif: 18, part_de_marche: 0.05, evolution_part_30d: 0.2 },
      { zone_id: 'z_bdx_bast', label: 'Bastide', strength: 'faible', stock_actif: 5, part_de_marche: 0.02, evolution_part_30d: 0 },
    ],
    zone_principale: 'Chartrons',
    stock_actif: 71,
    nouvelles_annonces_7d: 5,
    nouvelles_annonces_30d: 17,
    baisses_prix_30d: 2,
    annonces_anciennes_count: 6,
    delai_moyen_jours: 33,
    prix_moyen_m2: 4870,
    types_biens_dominants: ['T2', 'T3'],
    biens_similaires_count: 9,
    mandats_simples_concurrents_count: 0,
    has_mandat_simple_sous_pression: false,
    followed: true,
    status_suivi: 'Sous surveillance',
    alertes_actives: [],
    last_event_at: daysAgo(4),
    last_event_type: 'new_listing',
    last_event_label: 'Nouvelle annonce',
    created_at: daysAgo(22),
    updated_at: daysAgo(4),
  },
  {
    id: 'ag_009',
    name: 'Immo Garonne',
    siren: '698745321',
    ville: 'Bordeaux Saint-Seurin',
    code_postal: '33000',
    latitude: 44.8412,
    longitude: -0.5872,
    logo_initials: 'IG',
    logo_color: '#059669',
    zones: [
      { zone_id: 'z_stseurin', label: 'Saint-Seurin', strength: 'moyenne', stock_actif: 35, part_de_marche: 0.08, evolution_part_30d: 0 },
      { zone_id: 'z_bdx_centre', label: 'Centre', strength: 'faible', stock_actif: 12, part_de_marche: 0.03, evolution_part_30d: 0.1 },
    ],
    zone_principale: 'Saint-Seurin',
    stock_actif: 58,
    nouvelles_annonces_7d: 3,
    nouvelles_annonces_30d: 11,
    baisses_prix_30d: 1,
    annonces_anciennes_count: 4,
    delai_moyen_jours: 39,
    prix_moyen_m2: 4420,
    types_biens_dominants: ['T3'],
    biens_similaires_count: 6,
    mandats_simples_concurrents_count: 0,
    has_mandat_simple_sous_pression: false,
    followed: true,
    status_suivi: 'Sous surveillance',
    alertes_actives: [],
    last_event_at: daysAgo(5),
    last_event_type: 'price_drop',
    last_event_label: 'Baisse de prix',
    created_at: daysAgo(18),
    updated_at: daysAgo(5),
  },
  {
    id: 'ag_010',
    name: 'Monceau Opéra',
    siren: '741852963',
    ville: 'Paris 8e',
    code_postal: '75008',
    latitude: 48.8789,
    longitude: 2.3256,
    logo_initials: 'MO',
    logo_color: '#6366F1',
    zones: [
      { zone_id: 'z_8', label: 'Paris 8e', strength: 'forte', stock_actif: 30, part_de_marche: 0.07, evolution_part_30d: 0.2 },
      { zone_id: 'z_17', label: 'Paris 17e', strength: 'faible', stock_actif: 10, part_de_marche: 0.03, evolution_part_30d: 0 },
      { zone_id: 'z_9', label: 'Paris 9e', strength: 'faible', stock_actif: 6, part_de_marche: 0.02, evolution_part_30d: 0 },
    ],
    zone_principale: 'Paris 8e',
    stock_actif: 46,
    nouvelles_annonces_7d: 2,
    nouvelles_annonces_30d: 9,
    baisses_prix_30d: 0,
    annonces_anciennes_count: 3,
    delai_moyen_jours: 29,
    prix_moyen_m2: 9760,
    types_biens_dominants: ['T3', 'T4'],
    biens_similaires_count: 5,
    mandats_simples_concurrents_count: 0,
    has_mandat_simple_sous_pression: false,
    followed: true,
    status_suivi: 'Sous surveillance',
    alertes_actives: [],
    last_event_at: daysAgo(6),
    last_event_type: 'new_listing',
    last_event_label: 'Nouvelle annonce',
    created_at: daysAgo(14),
    updated_at: daysAgo(6),
  },
];

export const SIRENE_RESULTS = [
  {
    siren: '523489612',
    name: 'Agence Métropole',
    adresse: '36 rue de Vaugirard',
    ville: 'Paris 15e',
    code_postal: '75015',
    naf: '6831Z Agences immobilières',
    carte_t: 'CPI 7501 2018 000 034 567',
  },
  {
    siren: '401235987',
    name: 'Haussmann & Belliard',
    adresse: '12 rue Belliard',
    ville: 'Paris 16e',
    code_postal: '75116',
    naf: '6831Z Agences immobilières',
  },
  {
    siren: '845612378',
    name: 'Orpi Convention',
    adresse: '45 rue de la Convention',
    ville: 'Paris 15e',
    code_postal: '75015',
    naf: '6831Z Agences immobilières',
  },
  {
    siren: '712345689',
    name: 'Century 21 Grenelle',
    adresse: '8 rue de Grenelle',
    ville: 'Paris 15e',
    code_postal: '75015',
    naf: '6831Z Agences immobilières',
  },
  {
    siren: '988756412',
    name: 'Guy Hoquet Vaugirard',
    adresse: '120 rue Vaugirard',
    ville: 'Paris 15e',
    code_postal: '75015',
    naf: '6831Z Agences immobilières',
  },
];

export const DISCOVER_AGENCES: AgenceConcurrente[] = [
  {
    id: 'ag_discover_001',
    name: 'Orpi Convention',
    siren: '845612378',
    ville: 'Paris 15e',
    code_postal: '75015',
    logo_initials: 'OC',
    logo_color: '#F59E0B',
    zones: [{ zone_id: 'z_15', label: 'Paris 15e', strength: 'forte', stock_actif: 86, part_de_marche: 0.12, evolution_part_30d: 1.5 }],
    zone_principale: 'Paris 15e',
    stock_actif: 86,
    nouvelles_annonces_7d: 7,
    nouvelles_annonces_30d: 25,
    baisses_prix_30d: 3,
    annonces_anciennes_count: 8,
    delai_moyen_jours: 32,
    prix_moyen_m2: 8350,
    types_biens_dominants: ['T2', 'T3'],
    biens_similaires_count: 0,
    mandats_simples_concurrents_count: 0,
    has_mandat_simple_sous_pression: false,
    followed: false,
    status_suivi: 'Sous surveillance',
    alertes_actives: [],
    created_at: now.toISOString(),
    updated_at: now.toISOString(),
  },
  {
    id: 'ag_discover_002',
    name: 'Century 21 Grenelle',
    siren: '712345689',
    ville: 'Paris 15e',
    code_postal: '75015',
    logo_initials: 'C21',
    logo_color: '#DC2626',
    zones: [{ zone_id: 'z_15', label: 'Paris 15e', strength: 'moyenne', stock_actif: 54, part_de_marche: 0.07, evolution_part_30d: 0.5 }],
    zone_principale: 'Paris 15e',
    stock_actif: 54,
    nouvelles_annonces_7d: 4,
    nouvelles_annonces_30d: 18,
    baisses_prix_30d: 1,
    annonces_anciennes_count: 6,
    delai_moyen_jours: 38,
    prix_moyen_m2: 8280,
    types_biens_dominants: ['T3'],
    biens_similaires_count: 0,
    mandats_simples_concurrents_count: 0,
    has_mandat_simple_sous_pression: false,
    followed: false,
    status_suivi: 'Sous surveillance',
    alertes_actives: [],
    created_at: now.toISOString(),
    updated_at: now.toISOString(),
  },
  {
    id: 'ag_discover_003',
    name: 'Guy Hoquet Vaugirard',
    siren: '988756412',
    ville: 'Paris 15e',
    code_postal: '75015',
    logo_initials: 'GH',
    logo_color: '#3B82F6',
    zones: [{ zone_id: 'z_15', label: 'Paris 15e', strength: 'moyenne', stock_actif: 38, part_de_marche: 0.05, evolution_part_30d: 0.2 }],
    zone_principale: 'Paris 15e',
    stock_actif: 38,
    nouvelles_annonces_7d: 3,
    nouvelles_annonces_30d: 13,
    baisses_prix_30d: 2,
    annonces_anciennes_count: 5,
    delai_moyen_jours: 40,
    prix_moyen_m2: 8120,
    types_biens_dominants: ['T2', 'Studios'],
    biens_similaires_count: 0,
    mandats_simples_concurrents_count: 0,
    has_mandat_simple_sous_pression: false,
    followed: false,
    status_suivi: 'Sous surveillance',
    alertes_actives: [],
    created_at: now.toISOString(),
    updated_at: now.toISOString(),
  },
];
