import { Alerte } from '../types';

const now = new Date('2026-04-24T12:00:00Z');
const hoursAgo = (h: number) => new Date(now.getTime() - h * 3_600_000).toISOString();
const daysAgo = (d: number) => new Date(now.getTime() - d * 86_400_000).toISOString();

export const ALERTES: Alerte[] = [
  {
    id: 'al_001',
    created_by: 'user_001',
    assigned_to: 'user_001',
    name: 'T2 Paris 15e sous 550k',
    description: 'Opportunités pour profil acheteur Dupont',
    domain: 'prix',
    target_type: 'zone',
    target_id: 'zone_paris_15',
    target_label: 'Paris 15e · Appartement T2',
    target_secondary_label: '35–60 m² · 2 pièces',
    conditions: [
      { field: 'prix', operator: 'less_than', value: 550000, label: 'prix < 550 000 €' },
      { field: 'surface', operator: 'between', value: [35, 60], label: '35–60 m²' },
    ],
    frequency: 'immediate',
    channels: ['in_app', 'email'],
    priority: 'moyenne',
    status: 'active',
    last_triggered_at: hoursAgo(2),
    last_trigger_label: 'il y a 2h',
    triggers_count_7d: 12,
    triggers_count_30d: 48,
    treated_rate_30d: 0.83,
    avg_treatment_time_hours: 18,
    source_module: 'veille',
    health_status: 'healthy',
    created_at: daysAgo(42),
    updated_at: hoursAgo(2),
  },
  {
    id: 'al_002',
    created_by: 'user_001',
    assigned_to: 'user_002',
    name: 'Baisses prix biens suivis',
    domain: 'prix',
    target_type: 'bien',
    target_id: 'portefeuille_biens_suivis',
    target_label: 'Tous mes biens suivis',
    conditions: [{ field: 'prix', operator: 'decreased_by', value: 3, label: 'baisse ≥ 3 %' }],
    frequency: 'immediate',
    channels: ['in_app', 'email'],
    priority: 'haute',
    status: 'active',
    last_triggered_at: daysAgo(1),
    last_trigger_label: 'hier',
    triggers_count_7d: 8,
    triggers_count_30d: 31,
    treated_rate_30d: 0.7,
    avg_treatment_time_hours: 22,
    source_module: 'biens',
    health_status: 'healthy',
    created_at: daysAgo(60),
    updated_at: daysAgo(1),
  },
  {
    id: 'al_003',
    created_by: 'user_001',
    assigned_to: 'user_001',
    name: 'Mandats simples sous pression',
    domain: 'concurrence',
    target_type: 'agence',
    target_id: 'portefeuille_mandats',
    target_label: 'Portefeuille · Mandats simples',
    conditions: [
      { field: 'concurrent', operator: 'changed', value: null, label: 'concurrent détecté' },
      { field: 'prix_concurrent', operator: 'less_than', value: 'mandat', label: 'prix concurrent inférieur' },
    ],
    frequency: 'daily',
    channels: ['in_app', 'email'],
    priority: 'haute',
    status: 'active',
    last_triggered_at: daysAgo(3),
    last_trigger_label: 'il y a 3j',
    triggers_count_7d: 5,
    triggers_count_30d: 14,
    treated_rate_30d: 0.6,
    avg_treatment_time_hours: 36,
    source_module: 'biens',
    health_status: 'healthy',
    created_at: daysAgo(35),
    updated_at: daysAgo(3),
  },
  {
    id: 'al_004',
    created_by: 'user_003',
    name: 'DPE G détectés',
    domain: 'dpe',
    target_type: 'zone',
    target_id: 'zone_paris_15',
    target_label: 'Paris 15e · Tous usages',
    conditions: [{ field: 'dpe_classe', operator: 'equals', value: 'G', label: 'classe DPE = G' }],
    frequency: 'daily',
    channels: ['in_app'],
    priority: 'moyenne',
    status: 'active',
    last_triggered_at: daysAgo(1),
    last_trigger_label: 'il y a 1j',
    triggers_count_7d: 9,
    triggers_count_30d: 28,
    treated_rate_30d: 0.5,
    avg_treatment_time_hours: 42,
    source_module: 'prospection',
    health_status: 'healthy',
    created_at: daysAgo(28),
    updated_at: daysAgo(1),
  },
  {
    id: 'al_005',
    created_by: 'user_001',
    assigned_to: 'user_004',
    name: 'PC déposés 15e',
    domain: 'urbanisme',
    target_type: 'zone',
    target_id: 'zone_paris_15',
    target_label: 'Paris 15e',
    conditions: [{ field: 'urbanisme', operator: 'in', value: ['PC', 'DP', 'PA'], label: 'PC, DP, PA déposés' }],
    frequency: 'daily',
    channels: ['in_app', 'email'],
    priority: 'moyenne',
    status: 'active',
    last_triggered_at: daysAgo(1),
    last_trigger_label: 'hier',
    triggers_count_7d: 14,
    triggers_count_30d: 52,
    treated_rate_30d: 0.4,
    avg_treatment_time_hours: 72,
    source_module: 'observatoire',
    health_status: 'noisy',
    created_at: daysAgo(50),
    updated_at: daysAgo(1),
  },
  {
    id: 'al_006',
    created_by: 'user_001',
    assigned_to: 'user_001',
    name: 'Studios < 250k',
    domain: 'prix',
    target_type: 'zone',
    target_id: 'zone_paris_14',
    target_label: 'Paris 15e · Studio',
    target_secondary_label: '< 30 m²',
    conditions: [
      { field: 'prix', operator: 'less_than', value: 250000, label: 'prix < 250 000 €' },
      { field: 'type', operator: 'equals', value: 'studio', label: 'type = Studio' },
    ],
    frequency: 'immediate',
    channels: ['in_app', 'email'],
    priority: 'info',
    status: 'active',
    last_triggered_at: hoursAgo(5),
    last_trigger_label: 'il y a 5h',
    triggers_count_7d: 7,
    triggers_count_30d: 21,
    treated_rate_30d: 0.9,
    avg_treatment_time_hours: 8,
    source_module: 'veille',
    health_status: 'healthy',
    created_at: daysAgo(18),
    updated_at: hoursAgo(5),
  },
  {
    id: 'al_007',
    created_by: 'user_002',
    assigned_to: 'user_002',
    name: 'Biens sans photos',
    domain: 'annonce',
    target_type: 'zone',
    target_id: 'zone_paris_15',
    target_label: 'Tous portails (SeLoger, Leboncoin...)',
    conditions: [{ field: 'photos_count', operator: 'equals', value: 0, label: 'photos = 0' }],
    frequency: 'daily',
    channels: ['in_app'],
    priority: 'info',
    status: 'active',
    last_triggered_at: daysAgo(2),
    last_trigger_label: 'il y a 2j',
    triggers_count_7d: 11,
    triggers_count_30d: 39,
    treated_rate_30d: 0.3,
    avg_treatment_time_hours: 96,
    source_module: 'veille',
    health_status: 'healthy',
    created_at: daysAgo(25),
    updated_at: daysAgo(2),
  },
  {
    id: 'al_008',
    created_by: 'user_001',
    assigned_to: 'user_001',
    name: 'Concurrents 15e',
    domain: 'concurrence',
    target_type: 'zone',
    target_id: 'zone_paris_15',
    target_label: 'Paris 15e · Agences ciblées',
    conditions: [{ field: 'mandat', operator: 'changed', value: null, label: 'nouveau mandat gagnant' }],
    frequency: 'daily',
    channels: ['in_app', 'email'],
    priority: 'haute',
    status: 'paused',
    last_triggered_at: daysAgo(1),
    last_trigger_label: 'il y a 1j',
    triggers_count_7d: 6,
    triggers_count_30d: 18,
    treated_rate_30d: 0.55,
    avg_treatment_time_hours: 48,
    source_module: 'veille',
    health_status: 'healthy',
    created_at: daysAgo(12),
    updated_at: hoursAgo(10),
  },
  {
    id: 'al_009',
    created_by: 'user_005',
    name: 'Tension zone Boulogne',
    domain: 'marche',
    target_type: 'zone',
    target_id: 'zone_boulogne',
    target_label: 'Boulogne-Billancourt',
    conditions: [{ field: 'tension', operator: 'less_than', value: 60, label: 'tension < 60' }],
    frequency: 'weekly',
    channels: ['in_app'],
    priority: 'info',
    status: 'active',
    last_triggered_at: daysAgo(5),
    last_trigger_label: 'il y a 5j',
    triggers_count_7d: 1,
    triggers_count_30d: 4,
    treated_rate_30d: 1,
    source_module: 'observatoire',
    health_status: 'healthy',
    created_at: daysAgo(70),
    updated_at: daysAgo(5),
  },
  {
    id: 'al_010',
    created_by: 'user_001',
    assigned_to: 'user_003',
    name: 'DPE F Paris 14e',
    domain: 'dpe',
    target_type: 'zone',
    target_id: 'zone_paris_14',
    target_label: 'Paris 14e · Tous biens',
    conditions: [{ field: 'dpe_classe', operator: 'equals', value: 'F', label: 'classe DPE = F' }],
    frequency: 'daily',
    channels: ['in_app'],
    priority: 'info',
    status: 'active',
    last_triggered_at: daysAgo(38),
    last_trigger_label: 'il y a 1m',
    triggers_count_7d: 0,
    triggers_count_30d: 1,
    treated_rate_30d: 0,
    source_module: 'veille',
    health_status: 'silent',
    created_at: daysAgo(90),
    updated_at: daysAgo(38),
  },
  {
    id: 'al_011',
    created_by: 'user_001',
    assigned_to: 'user_001',
    name: 'Recherche Paris rive gauche',
    domain: 'annonce',
    target_type: 'recherche',
    target_id: 'recherche_001',
    target_label: 'Paris 5e/6e/7e · 3-4 pièces',
    conditions: [{ field: 'annonce', operator: 'changed', value: null, label: 'nouvelle annonce correspondante' }],
    frequency: 'immediate',
    channels: ['in_app', 'email'],
    priority: 'haute',
    status: 'active',
    last_triggered_at: daysAgo(1),
    last_trigger_label: 'hier',
    triggers_count_7d: 4,
    triggers_count_30d: 17,
    treated_rate_30d: 0.75,
    avg_treatment_time_hours: 12,
    source_module: 'biens',
    health_status: 'healthy',
    created_at: daysAgo(22),
    updated_at: daysAgo(1),
  },
  {
    id: 'al_012',
    created_by: 'user_001',
    assigned_to: 'user_002',
    name: 'Stock zone 16e',
    domain: 'marche',
    target_type: 'zone',
    target_id: 'zone_paris_16',
    target_label: 'Paris 16e',
    conditions: [{ field: 'stock_zone', operator: 'increased_by', value: 15, label: 'stock +15%' }],
    frequency: 'weekly',
    channels: ['in_app', 'email'],
    priority: 'moyenne',
    status: 'active',
    last_triggered_at: daysAgo(4),
    last_trigger_label: 'il y a 4j',
    triggers_count_7d: 1,
    triggers_count_30d: 3,
    treated_rate_30d: 1,
    source_module: 'observatoire',
    health_status: 'healthy',
    created_at: daysAgo(45),
    updated_at: daysAgo(4),
  },
  {
    id: 'al_013',
    created_by: 'user_003',
    assigned_to: 'user_003',
    name: 'Baisses Lyon 3e',
    domain: 'prix',
    target_type: 'zone',
    target_id: 'zone_lyon_3',
    target_label: 'Lyon 3e · Appartements',
    conditions: [{ field: 'prix', operator: 'decreased_by', value: 5, label: 'baisse ≥ 5 %' }],
    frequency: 'immediate',
    channels: ['in_app'],
    priority: 'moyenne',
    status: 'active',
    last_triggered_at: hoursAgo(8),
    last_trigger_label: 'il y a 8h',
    triggers_count_7d: 3,
    triggers_count_30d: 11,
    treated_rate_30d: 0.8,
    source_module: 'veille',
    health_status: 'healthy',
    created_at: daysAgo(15),
    updated_at: hoursAgo(8),
  },
  {
    id: 'al_014',
    created_by: 'user_001',
    name: 'PC 16e',
    domain: 'urbanisme',
    target_type: 'zone',
    target_id: 'zone_paris_16',
    target_label: 'Paris 16e',
    conditions: [{ field: 'urbanisme', operator: 'in', value: ['PC'], label: 'PC déposé' }],
    frequency: 'daily',
    channels: ['in_app'],
    priority: 'info',
    status: 'paused',
    last_triggered_at: daysAgo(10),
    last_trigger_label: 'il y a 1s',
    triggers_count_7d: 0,
    triggers_count_30d: 2,
    treated_rate_30d: 0,
    source_module: 'observatoire',
    health_status: 'healthy',
    created_at: daysAgo(40),
    updated_at: daysAgo(10),
  },
  {
    id: 'al_015',
    created_by: 'user_001',
    assigned_to: 'user_005',
    name: 'Nouvelles ventes DVF 15e',
    domain: 'marche',
    target_type: 'zone',
    target_id: 'zone_paris_15',
    target_label: 'Paris 15e · DVF',
    conditions: [{ field: 'dvf', operator: 'changed', value: null, label: 'nouvelle vente comparable' }],
    frequency: 'weekly',
    channels: ['in_app'],
    priority: 'moyenne',
    status: 'active',
    last_triggered_at: daysAgo(2),
    last_trigger_label: 'il y a 2j',
    triggers_count_7d: 2,
    triggers_count_30d: 8,
    treated_rate_30d: 0.5,
    source_module: 'prospection',
    health_status: 'healthy',
    created_at: daysAgo(30),
    updated_at: daysAgo(2),
  },
  {
    id: 'al_016',
    created_by: 'user_002',
    assigned_to: 'user_002',
    name: 'Biens anciens',
    domain: 'annonce',
    target_type: 'zone',
    target_id: 'portefeuille_biens_suivis',
    target_label: 'Mes biens suivis',
    conditions: [{ field: 'anciennete', operator: 'greater_than', value: 90, label: 'annonce > 90j' }],
    frequency: 'weekly',
    channels: ['in_app'],
    priority: 'info',
    status: 'active',
    last_triggered_at: daysAgo(6),
    last_trigger_label: 'il y a 6j',
    triggers_count_7d: 1,
    triggers_count_30d: 5,
    treated_rate_30d: 0.4,
    source_module: 'biens',
    health_status: 'healthy',
    created_at: daysAgo(60),
    updated_at: daysAgo(6),
  },
  {
    id: 'al_017',
    created_by: 'user_004',
    assigned_to: 'user_004',
    name: 'Agence Métropole',
    domain: 'concurrence',
    target_type: 'agence',
    target_id: 'ag_m1n2o3',
    target_label: 'Agence Métropole · Paris 15e',
    conditions: [{ field: 'mandat', operator: 'changed', value: null, label: 'nouvelle annonce agence' }],
    frequency: 'immediate',
    channels: ['in_app', 'email'],
    priority: 'haute',
    status: 'active',
    last_triggered_at: hoursAgo(14),
    last_trigger_label: 'il y a 14h',
    triggers_count_7d: 4,
    triggers_count_30d: 17,
    treated_rate_30d: 0.65,
    source_module: 'veille',
    health_status: 'healthy',
    created_at: daysAgo(20),
    updated_at: hoursAgo(14),
  },
  {
    id: 'al_018',
    created_by: 'user_001',
    name: 'Rendement > 5% Paris 18e',
    domain: 'marche',
    target_type: 'zone',
    target_id: 'zone_paris_18',
    target_label: 'Paris 18e · Appartements locatifs',
    conditions: [{ field: 'rendement', operator: 'greater_than', value: 5, label: 'rendement > 5 %' }],
    frequency: 'weekly',
    channels: ['in_app', 'email'],
    priority: 'moyenne',
    status: 'active',
    last_triggered_at: daysAgo(3),
    last_trigger_label: 'il y a 3j',
    triggers_count_7d: 2,
    triggers_count_30d: 6,
    treated_rate_30d: 0.5,
    source_module: 'investissement',
    health_status: 'healthy',
    created_at: daysAgo(38),
    updated_at: daysAgo(3),
  },
  {
    id: 'al_019',
    created_by: 'user_001',
    name: 'Pipeline DPE erreur',
    domain: 'dpe',
    target_type: 'zone',
    target_id: 'zone_marseille_2',
    target_label: 'Marseille 2e',
    conditions: [{ field: 'dpe_classe', operator: 'in', value: ['F', 'G'], label: 'DPE F ou G' }],
    frequency: 'daily',
    channels: ['in_app'],
    priority: 'info',
    status: 'active',
    triggers_count_7d: 0,
    triggers_count_30d: 0,
    treated_rate_30d: 0,
    source_module: 'veille',
    health_status: 'error',
    created_at: daysAgo(15),
    updated_at: daysAgo(8),
  },
  {
    id: 'al_020',
    created_by: 'user_001',
    assigned_to: 'user_001',
    name: 'Analyses invest MAJ',
    domain: 'prix',
    target_type: 'bien',
    target_id: 'portefeuille_biens_suivis',
    target_label: 'Biens avec analyse ouverte',
    conditions: [{ field: 'analyse', operator: 'changed', value: null, label: 'MAJ analyse' }],
    frequency: 'immediate',
    channels: ['in_app'],
    priority: 'moyenne',
    status: 'active',
    last_triggered_at: hoursAgo(6),
    last_trigger_label: 'il y a 6h',
    triggers_count_7d: 3,
    triggers_count_30d: 12,
    treated_rate_30d: 0.85,
    source_module: 'investissement',
    health_status: 'healthy',
    created_at: daysAgo(10),
    updated_at: hoursAgo(6),
  },
  {
    id: 'al_021',
    created_by: 'user_002',
    name: 'Nouveaux PC 18e',
    domain: 'urbanisme',
    target_type: 'zone',
    target_id: 'zone_paris_18',
    target_label: 'Paris 18e',
    conditions: [{ field: 'urbanisme', operator: 'in', value: ['PC', 'DP'], label: 'PC/DP déposé' }],
    frequency: 'weekly',
    channels: ['in_app', 'email'],
    priority: 'info',
    status: 'active',
    last_triggered_at: daysAgo(4),
    last_trigger_label: 'il y a 4j',
    triggers_count_7d: 2,
    triggers_count_30d: 9,
    treated_rate_30d: 0.3,
    source_module: 'observatoire',
    health_status: 'healthy',
    created_at: daysAgo(55),
    updated_at: daysAgo(4),
  },
  {
    id: 'al_022',
    created_by: 'user_001',
    assigned_to: 'user_001',
    name: 'Rapports ouverts',
    domain: 'annonce',
    target_type: 'recherche',
    target_id: 'rapports_envoyes',
    target_label: 'Rapports récents envoyés',
    conditions: [{ field: 'rapport', operator: 'changed', value: null, label: 'rapport ouvert par client' }],
    frequency: 'immediate',
    channels: ['in_app'],
    priority: 'moyenne',
    status: 'active',
    last_triggered_at: hoursAgo(16),
    last_trigger_label: 'il y a 16h',
    triggers_count_7d: 5,
    triggers_count_30d: 22,
    treated_rate_30d: 0.8,
    source_module: 'estimation',
    health_status: 'healthy',
    created_at: daysAgo(20),
    updated_at: hoursAgo(16),
  },
  {
    id: 'al_023',
    created_by: 'user_005',
    assigned_to: 'user_005',
    name: 'Remises en ligne',
    domain: 'annonce',
    target_type: 'bien',
    target_id: 'portefeuille_biens_suivis',
    target_label: 'Biens suivis',
    conditions: [{ field: 'annonce', operator: 'in', value: ['republished'], label: 'remise en ligne' }],
    frequency: 'immediate',
    channels: ['in_app'],
    priority: 'moyenne',
    status: 'active',
    last_triggered_at: daysAgo(1),
    last_trigger_label: 'hier',
    triggers_count_7d: 1,
    triggers_count_30d: 4,
    treated_rate_30d: 0.5,
    source_module: 'biens',
    health_status: 'healthy',
    created_at: daysAgo(12),
    updated_at: daysAgo(1),
  },
  {
    id: 'al_024',
    created_by: 'user_001',
    assigned_to: 'user_001',
    name: 'Délai > 75j Paris 7e',
    domain: 'marche',
    target_type: 'zone',
    target_id: 'zone_paris_7',
    target_label: 'Paris 7e',
    conditions: [{ field: 'delai_vente', operator: 'greater_than', value: 75, label: 'délai > 75j' }],
    frequency: 'weekly',
    channels: ['in_app'],
    priority: 'info',
    status: 'paused',
    last_triggered_at: daysAgo(7),
    last_trigger_label: 'il y a 1s',
    triggers_count_7d: 0,
    triggers_count_30d: 1,
    treated_rate_30d: 0,
    source_module: 'observatoire',
    health_status: 'healthy',
    created_at: daysAgo(90),
    updated_at: daysAgo(7),
  },
];
