import { BienSuivi } from '../types';

const now = new Date('2026-04-24T14:00:00Z');
const hoursAgo = (h: number) => new Date(now.getTime() - h * 3_600_000).toISOString();
const daysAgo = (d: number) => new Date(now.getTime() - d * 86_400_000).toISOString();

const IMG = {
  t2: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?q=80&w=640&auto=format&fit=crop',
  t3: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?q=80&w=640&auto=format&fit=crop',
  studio: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?q=80&w=640&auto=format&fit=crop',
  maison: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?q=80&w=640&auto=format&fit=crop',
  loft: 'https://images.unsplash.com/photo-1505691938895-1758d7feb511?q=80&w=640&auto=format&fit=crop',
  appart: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=640&auto=format&fit=crop',
};

export const BIENS_SUIVIS: BienSuivi[] = [
  {
    id: 'bs_001',
    bien_id: 'bien_001',
    followed_by: 'user_001',
    assigned_to: 'user_001',
    source: 'annonces',
    source_portail: 'SeLoger',
    source_id: 'annonce_1234',
    source_label: 'Annonce SeLoger',
    type_bien: 'Appartement',
    pieces: 3,
    surface: 60,
    etage: '3/6',
    annee_construction: 1965,
    charges_mois: 220,
    adresse: '45 rue Lecourbe',
    ville: 'Paris 15e',
    code_postal: '75015',
    latitude: 48.8434,
    longitude: 2.3094,
    dpe: 'D',
    prix_actuel: 540000,
    prix_precedent: 560000,
    variation_pct: -3.6,
    variation_eur: -20000,
    prix_m2: 9000,
    statut_annonce: 'Baisse',
    photo_url: IMG.t3,
    reason: 'Profil acheteur Dupont',
    status: 'active',
    alertes_actives: ['al_001'],
    notifications_unread_count: 2,
    last_event_at: minutes_ish(12),
    last_event_type: 'baisse_prix',
    last_event_label: 'Baisse de prix -3,6 %',
    score_interet: 82,
    score_label: 'forte_opportunite',
    score_breakdown: [
      { key: 'variation_prix', label: 'Variation de prix', contribution: 30, detail: 'Baisse -3,6 % en 6j' },
      { key: 'tension_zone', label: 'Tension de zone', contribution: 20, detail: 'Paris 15e · tension 80' },
      { key: 'anciennete_annonce', label: 'Ancienneté annonce', contribution: 7, detail: 'Annonce 45j' },
      { key: 'pression_concurrent', label: 'Pression concurrent', contribution: 25, detail: 'Agence X détectée' },
    ],
    estimation_valeur: 540000,
    analyse_tri_pct: 8.2,
    leads_count: 2,
    dossier_name: 'Acquisition T3',
    created_at: daysAgo(42),
    updated_at: hoursAgo(2),
  },
  {
    id: 'bs_002',
    bien_id: 'bien_002',
    followed_by: 'user_001',
    source: 'annonces',
    source_portail: 'Leboncoin',
    source_label: 'Annonce Leboncoin',
    type_bien: 'Appartement',
    pieces: 2,
    surface: 38,
    etage: '2/4',
    annee_construction: 1978,
    charges_mois: 150,
    adresse: '7 rue des Plantes',
    ville: 'Paris 15e',
    code_postal: '75015',
    latitude: 48.8323,
    longitude: 2.3151,
    dpe: 'E',
    prix_actuel: 312000,
    prix_precedent: 320000,
    variation_pct: -2.5,
    variation_eur: -8000,
    prix_m2: 8210,
    statut_annonce: 'Baisse',
    photo_url: IMG.t2,
    status: 'active',
    alertes_actives: ['al_002'],
    notifications_unread_count: 1,
    last_event_at: hoursAgo(22),
    last_event_type: 'baisse_prix',
    last_event_label: 'Baisse -2,5 %',
    score_interet: 68,
    score_label: 'a_surveiller',
    score_breakdown: [
      { key: 'variation_prix', label: 'Variation de prix', contribution: 20, detail: '-2,5 % en 4j' },
      { key: 'tension_zone', label: 'Tension de zone', contribution: 18, detail: 'Paris 15e · tension 72' },
      { key: 'anciennete_annonce', label: 'Ancienneté', contribution: 15, detail: '95j de publication' },
      { key: 'pression_concurrent', label: 'Pression', contribution: 15, detail: 'Concurrents actifs' },
    ],
    estimation_valeur: 315000,
    leads_count: 1,
    created_at: daysAgo(30),
    updated_at: hoursAgo(22),
  },
  {
    id: 'bs_003',
    bien_id: 'bien_003',
    followed_by: 'user_001',
    assigned_to: 'user_002',
    source: 'annonces',
    source_portail: 'SeLoger',
    source_label: 'Annonce SeLoger',
    type_bien: 'Appartement',
    pieces: 4,
    surface: 100,
    etage: '5/7',
    annee_construction: 1928,
    charges_mois: 380,
    adresse: '112 av. Félix Faure',
    ville: 'Paris 15e',
    code_postal: '75015',
    latitude: 48.8389,
    longitude: 2.2933,
    dpe: 'C',
    prix_actuel: 890000,
    prix_precedent: 870000,
    variation_pct: 2.3,
    variation_eur: 20000,
    prix_m2: 8900,
    statut_annonce: 'Actif',
    photo_url: IMG.t3,
    status: 'active',
    alertes_actives: [],
    notifications_unread_count: 1,
    last_event_at: hoursAgo(29),
    last_event_type: 'hausse_prix',
    last_event_label: 'Hausse +2,3 %',
    score_interet: 61,
    score_label: 'a_surveiller',
    score_breakdown: [
      { key: 'variation_prix', label: 'Variation de prix', contribution: 0, detail: 'Hausse récente' },
      { key: 'tension_zone', label: 'Tension de zone', contribution: 22, detail: 'Tension forte 88' },
      { key: 'anciennete_annonce', label: 'Ancienneté', contribution: 18, detail: '115j' },
      { key: 'pression_concurrent', label: 'Pression', contribution: 21, detail: 'Mandat concurrent' },
    ],
    analyse_tri_pct: 5.1,
    leads_count: 1,
    created_at: daysAgo(20),
    updated_at: hoursAgo(29),
  },
  {
    id: 'bs_004',
    bien_id: 'bien_004',
    followed_by: 'user_001',
    assigned_to: 'user_003',
    source: 'prospection',
    source_portail: "Bien'ici",
    source_label: "Annonce Bien'ici",
    type_bien: 'Maison',
    pieces: 5,
    surface: 150,
    annee_construction: 1910,
    charges_mois: 0,
    adresse: '18 rue de Bellevue',
    ville: 'Boulogne-Billancourt',
    code_postal: '92100',
    latitude: 48.8365,
    longitude: 2.2407,
    dpe: 'D',
    prix_actuel: 1250000,
    prix_precedent: 1300000,
    variation_pct: -3.8,
    variation_eur: -50000,
    prix_m2: 8333,
    statut_annonce: 'Baisse',
    photo_url: IMG.maison,
    status: 'active',
    alertes_actives: ['al_002'],
    notifications_unread_count: 2,
    last_event_at: hoursAgo(30),
    last_event_type: 'baisse_prix',
    last_event_label: 'Baisse -3,8 %',
    score_interet: 88,
    score_label: 'forte_opportunite',
    score_breakdown: [
      { key: 'variation_prix', label: 'Variation de prix', contribution: 30, detail: '-3,8 %' },
      { key: 'tension_zone', label: 'Tension de zone', contribution: 23, detail: 'Tension 92' },
      { key: 'anciennete_annonce', label: 'Ancienneté', contribution: 20, detail: '145j' },
      { key: 'pression_concurrent', label: 'Pression', contribution: 15, detail: 'Concurrents' },
    ],
    estimation_valeur: 1300000,
    analyse_tri_pct: 7.4,
    leads_count: 2,
    dossier_name: 'Invest Boulogne',
    created_at: daysAgo(55),
    updated_at: hoursAgo(30),
  },
  {
    id: 'bs_005',
    bien_id: 'bien_005',
    followed_by: 'user_001',
    source: 'dvf',
    source_label: 'DVF',
    type_bien: 'Appartement',
    pieces: 3,
    surface: 60,
    etage: '1/5',
    adresse: '56 rue de Lyon',
    ville: 'Paris 12e',
    code_postal: '75012',
    latitude: 48.8446,
    longitude: 2.3776,
    dpe: 'C',
    prix_actuel: 575000,
    prix_precedent: 575000,
    variation_pct: 0,
    variation_eur: 0,
    prix_m2: 9583,
    statut_annonce: 'Actif',
    photo_url: IMG.appart,
    status: 'active',
    alertes_actives: [],
    notifications_unread_count: 1,
    last_event_at: daysAgo(14),
    last_event_type: 'nouvelle_source',
    last_event_label: 'Nouvelle source',
    score_interet: 55,
    score_label: 'a_surveiller',
    score_breakdown: [
      { key: 'variation_prix', label: 'Variation de prix', contribution: 0, detail: 'Stable' },
      { key: 'tension_zone', label: 'Tension de zone', contribution: 18, detail: 'Tension 72' },
      { key: 'anciennete_annonce', label: 'Ancienneté', contribution: 12, detail: '72j' },
      { key: 'pression_concurrent', label: 'Pression', contribution: 25, detail: 'Mandat concurrent' },
    ],
    leads_count: 0,
    created_at: daysAgo(60),
    updated_at: daysAgo(10),
  },
  {
    id: 'bs_006',
    bien_id: 'bien_006',
    followed_by: 'user_001',
    assigned_to: 'user_001',
    source: 'annonces',
    source_portail: 'Leboncoin',
    source_label: 'Annonce Leboncoin',
    type_bien: 'Appartement',
    pieces: 2,
    surface: 35,
    etage: 'RDC/4',
    annee_construction: 1998,
    charges_mois: 130,
    adresse: '33 cours Franklin Roosevelt',
    ville: 'Lyon 3e',
    code_postal: '69003',
    latitude: 45.7594,
    longitude: 4.8636,
    dpe: 'E',
    prix_actuel: 239000,
    prix_precedent: 249000,
    variation_pct: -4,
    variation_eur: -10000,
    prix_m2: 6828,
    statut_annonce: 'Baisse',
    photo_url: IMG.t2,
    status: 'active',
    alertes_actives: ['al_013'],
    notifications_unread_count: 3,
    last_event_at: daysAgo(1),
    last_event_type: 'baisse_prix',
    last_event_label: 'Baisse -4 %',
    score_interet: 73,
    score_label: 'a_surveiller',
    score_breakdown: [
      { key: 'variation_prix', label: 'Variation de prix', contribution: 20, detail: '-4 %' },
      { key: 'tension_zone', label: 'Tension de zone', contribution: 15, detail: 'Tension 60' },
      { key: 'anciennete_annonce', label: 'Ancienneté', contribution: 18, detail: '110j' },
      { key: 'pression_concurrent', label: 'Pression', contribution: 20, detail: 'Concurrents' },
    ],
    leads_count: 1,
    created_at: daysAgo(35),
    updated_at: daysAgo(1),
  },
  {
    id: 'bs_007',
    bien_id: 'bien_007',
    followed_by: 'user_001',
    source: 'estimation',
    source_portail: "Bien'ici",
    source_label: 'Avis de valeur',
    type_bien: 'Appartement',
    pieces: 3,
    surface: 100,
    etage: '4/6',
    annee_construction: 1970,
    charges_mois: 250,
    adresse: '2 quai de la Mégisserie',
    ville: 'Lyon 1er',
    code_postal: '69001',
    latitude: 45.7673,
    longitude: 4.8357,
    dpe: 'B',
    prix_actuel: 770000,
    prix_precedent: 755000,
    variation_pct: 2,
    variation_eur: 15000,
    prix_m2: 7700,
    statut_annonce: 'Actif',
    photo_url: IMG.appart,
    status: 'active',
    alertes_actives: [],
    notifications_unread_count: 1,
    last_event_at: daysAgo(1),
    last_event_type: 'hausse_prix',
    last_event_label: 'Hausse +2 %',
    score_interet: 64,
    score_label: 'a_surveiller',
    score_breakdown: [
      { key: 'variation_prix', label: 'Variation de prix', contribution: 0, detail: 'Hausse' },
      { key: 'tension_zone', label: 'Tension de zone', contribution: 20, detail: 'Tension 80' },
      { key: 'anciennete_annonce', label: 'Ancienneté', contribution: 20, detail: '130j' },
      { key: 'pression_concurrent', label: 'Pression', contribution: 24, detail: 'Mandat pression' },
    ],
    estimation_valeur: 755000,
    analyse_tri_pct: 6.3,
    leads_count: 0,
    created_at: daysAgo(80),
    updated_at: daysAgo(1),
  },
  {
    id: 'bs_008',
    bien_id: 'bien_008',
    followed_by: 'user_001',
    assigned_to: 'user_004',
    source: 'annonces',
    source_portail: 'SeLoger',
    source_label: 'Annonce SeLoger',
    type_bien: 'Appartement',
    pieces: 2,
    surface: 42,
    etage: '3/5',
    annee_construction: 1982,
    charges_mois: 180,
    adresse: '88 rue Saint-Dominique',
    ville: 'Paris 7e',
    code_postal: '75007',
    latitude: 48.8588,
    longitude: 2.3056,
    dpe: 'D',
    prix_actuel: 495000,
    prix_precedent: 510000,
    variation_pct: -2.9,
    variation_eur: -15000,
    prix_m2: 11786,
    statut_annonce: 'Remis en ligne',
    photo_url: IMG.t2,
    status: 'active',
    alertes_actives: ['al_023'],
    notifications_unread_count: 1,
    last_event_at: daysAgo(1),
    last_event_type: 'remise_en_ligne',
    last_event_label: 'Remis en ligne -2,9 %',
    score_interet: 57,
    score_label: 'a_surveiller',
    score_breakdown: [
      { key: 'variation_prix', label: 'Variation de prix', contribution: 10, detail: '-2,9 %' },
      { key: 'tension_zone', label: 'Tension de zone', contribution: 22, detail: 'Tension 88' },
      { key: 'anciennete_annonce', label: 'Ancienneté', contribution: 10, detail: '60j' },
      { key: 'pression_concurrent', label: 'Pression', contribution: 15, detail: 'Modérée' },
    ],
    leads_count: 1,
    created_at: daysAgo(25),
    updated_at: daysAgo(1),
  },
  {
    id: 'bs_009',
    bien_id: 'bien_009',
    followed_by: 'user_001',
    source: 'observatoire',
    source_portail: 'PAP',
    source_label: 'PAP',
    type_bien: 'Studio',
    pieces: 1,
    surface: 22,
    etage: '5/7',
    annee_construction: 2002,
    charges_mois: 95,
    adresse: '14 rue Daguerre',
    ville: 'Paris 14e',
    code_postal: '75014',
    latitude: 48.8331,
    longitude: 2.3281,
    dpe: 'C',
    prix_actuel: 238000,
    prix_precedent: 242000,
    variation_pct: -1.7,
    variation_eur: -4000,
    prix_m2: 10818,
    statut_annonce: 'Actif',
    photo_url: IMG.studio,
    status: 'active',
    alertes_actives: ['al_006'],
    notifications_unread_count: 0,
    last_event_at: daysAgo(3),
    last_event_type: 'variation_marche',
    last_event_label: 'Marché stable',
    score_interet: 42,
    score_label: 'faible_priorite',
    score_breakdown: [
      { key: 'variation_prix', label: 'Variation de prix', contribution: 10, detail: '-1,7 %' },
      { key: 'tension_zone', label: 'Tension de zone', contribution: 17, detail: 'Tension 68' },
      { key: 'anciennete_annonce', label: 'Ancienneté', contribution: 5, detail: '32j' },
      { key: 'pression_concurrent', label: 'Pression', contribution: 10, detail: 'Faible' },
    ],
    leads_count: 0,
    created_at: daysAgo(40),
    updated_at: daysAgo(3),
  },
  {
    id: 'bs_010',
    bien_id: 'bien_010',
    followed_by: 'user_001',
    assigned_to: 'user_001',
    source: 'investissement',
    source_portail: 'SeLoger',
    source_label: 'Opportunité invest',
    type_bien: 'Loft',
    pieces: 2,
    surface: 75,
    etage: 'RDC',
    annee_construction: 2015,
    charges_mois: 140,
    adresse: '3 rue du Faubourg Saint-Denis',
    ville: 'Paris 10e',
    code_postal: '75010',
    latitude: 48.8701,
    longitude: 2.3534,
    dpe: 'B',
    prix_actuel: 670000,
    prix_precedent: 695000,
    variation_pct: -3.6,
    variation_eur: -25000,
    prix_m2: 8933,
    statut_annonce: 'Baisse',
    photo_url: IMG.loft,
    status: 'active',
    alertes_actives: ['al_018'],
    notifications_unread_count: 1,
    last_event_at: hoursAgo(6),
    last_event_type: 'baisse_prix',
    last_event_label: 'Baisse -3,6 %',
    score_interet: 79,
    score_label: 'forte_opportunite',
    score_breakdown: [
      { key: 'variation_prix', label: 'Variation de prix', contribution: 25, detail: '-3,6 %' },
      { key: 'tension_zone', label: 'Tension de zone', contribution: 22, detail: 'Tension 88' },
      { key: 'anciennete_annonce', label: 'Ancienneté', contribution: 10, detail: '60j' },
      { key: 'pression_concurrent', label: 'Pression', contribution: 22, detail: 'Concurrents actifs' },
    ],
    estimation_valeur: 680000,
    analyse_tri_pct: 7.1,
    leads_count: 2,
    dossier_name: 'Invest Paris 10e',
    created_at: daysAgo(22),
    updated_at: hoursAgo(6),
  },
  {
    id: 'bs_011',
    bien_id: 'bien_011',
    followed_by: 'user_001',
    source: 'annonces',
    source_portail: 'Logic Immo',
    source_label: 'Annonce Logic Immo',
    type_bien: 'Appartement',
    pieces: 3,
    surface: 72,
    etage: '2/5',
    annee_construction: 1955,
    charges_mois: 210,
    adresse: '9 rue Saint-Ferdinand',
    ville: 'Paris 17e',
    code_postal: '75017',
    latitude: 48.8786,
    longitude: 2.288,
    dpe: 'F',
    prix_actuel: 612000,
    prix_precedent: 612000,
    variation_pct: 0,
    variation_eur: 0,
    prix_m2: 8500,
    statut_annonce: 'Actif',
    photo_url: IMG.appart,
    status: 'active',
    alertes_actives: [],
    notifications_unread_count: 0,
    last_event_at: daysAgo(6),
    last_event_type: 'dpe_detecte',
    last_event_label: 'DPE F détecté',
    score_interet: 48,
    score_label: 'faible_priorite',
    score_breakdown: [
      { key: 'variation_prix', label: 'Variation de prix', contribution: 0, detail: 'Stable' },
      { key: 'tension_zone', label: 'Tension de zone', contribution: 18, detail: 'Tension 72' },
      { key: 'anciennete_annonce', label: 'Ancienneté', contribution: 15, detail: '88j' },
      { key: 'pression_concurrent', label: 'Pression', contribution: 15, detail: 'Concurrents' },
    ],
    leads_count: 0,
    created_at: daysAgo(50),
    updated_at: daysAgo(6),
  },
  {
    id: 'bs_012',
    bien_id: 'bien_012',
    followed_by: 'user_001',
    assigned_to: 'user_005',
    source: 'annonces',
    source_portail: 'SeLoger',
    source_label: 'Annonce SeLoger',
    type_bien: 'Maison',
    pieces: 6,
    surface: 180,
    annee_construction: 1985,
    adresse: '45 rue du Général Leclerc',
    ville: 'Versailles',
    code_postal: '78000',
    latitude: 48.8044,
    longitude: 2.1301,
    dpe: 'C',
    prix_actuel: 980000,
    prix_precedent: 1020000,
    variation_pct: -3.9,
    variation_eur: -40000,
    prix_m2: 5444,
    statut_annonce: 'Baisse',
    photo_url: IMG.maison,
    status: 'active',
    alertes_actives: [],
    notifications_unread_count: 2,
    last_event_at: daysAgo(2),
    last_event_type: 'baisse_prix',
    last_event_label: 'Baisse -3,9 %',
    score_interet: 85,
    score_label: 'forte_opportunite',
    score_breakdown: [
      { key: 'variation_prix', label: 'Variation de prix', contribution: 30, detail: '-3,9 %' },
      { key: 'tension_zone', label: 'Tension de zone', contribution: 20, detail: 'Tension 80' },
      { key: 'anciennete_annonce', label: 'Ancienneté', contribution: 15, detail: '95j' },
      { key: 'pression_concurrent', label: 'Pression', contribution: 20, detail: 'Concurrents' },
    ],
    estimation_valeur: 1000000,
    analyse_tri_pct: 6.8,
    leads_count: 3,
    created_at: daysAgo(48),
    updated_at: daysAgo(2),
  },
  {
    id: 'bs_013',
    bien_id: 'bien_013',
    followed_by: 'user_001',
    source: 'annonces',
    source_portail: "Bien'ici",
    source_label: "Bien'ici",
    type_bien: 'Appartement',
    pieces: 4,
    surface: 95,
    etage: '4/4',
    annee_construction: 1967,
    charges_mois: 310,
    adresse: '17 rue de Fleurus',
    ville: 'Paris 6e',
    code_postal: '75006',
    latitude: 48.8463,
    longitude: 2.3308,
    dpe: 'D',
    prix_actuel: 1380000,
    prix_precedent: 1380000,
    variation_pct: 0,
    variation_eur: 0,
    prix_m2: 14526,
    statut_annonce: 'Actif',
    photo_url: IMG.t3,
    status: 'active',
    alertes_actives: ['al_011'],
    notifications_unread_count: 0,
    last_event_at: daysAgo(8),
    last_event_type: 'nouvelle_annonce',
    last_event_label: 'Nouvelle annonce',
    score_interet: 52,
    score_label: 'a_surveiller',
    score_breakdown: [
      { key: 'variation_prix', label: 'Variation de prix', contribution: 0, detail: 'Stable' },
      { key: 'tension_zone', label: 'Tension de zone', contribution: 23, detail: 'Tension 92' },
      { key: 'anciennete_annonce', label: 'Ancienneté', contribution: 12, detail: '72j' },
      { key: 'pression_concurrent', label: 'Pression', contribution: 17, detail: 'Modérée' },
    ],
    leads_count: 1,
    created_at: daysAgo(20),
    updated_at: daysAgo(8),
  },
  {
    id: 'bs_014',
    bien_id: 'bien_014',
    followed_by: 'user_001',
    source: 'annonces',
    source_portail: 'Leboncoin',
    source_label: 'Leboncoin',
    type_bien: 'Appartement',
    pieces: 2,
    surface: 48,
    etage: '1/3',
    annee_construction: 1925,
    charges_mois: 160,
    adresse: '22 rue du Clos',
    ville: 'Paris 20e',
    code_postal: '75020',
    latitude: 48.8627,
    longitude: 2.4016,
    dpe: 'E',
    prix_actuel: 358000,
    prix_precedent: 372000,
    variation_pct: -3.8,
    variation_eur: -14000,
    prix_m2: 7458,
    statut_annonce: 'Baisse',
    photo_url: IMG.t2,
    status: 'active',
    alertes_actives: [],
    notifications_unread_count: 1,
    last_event_at: hoursAgo(18),
    last_event_type: 'baisse_prix',
    last_event_label: 'Baisse -3,8 %',
    score_interet: 76,
    score_label: 'forte_opportunite',
    score_breakdown: [
      { key: 'variation_prix', label: 'Variation de prix', contribution: 25, detail: '-3,8 %' },
      { key: 'tension_zone', label: 'Tension de zone', contribution: 15, detail: 'Tension 60' },
      { key: 'anciennete_annonce', label: 'Ancienneté', contribution: 18, detail: '105j' },
      { key: 'pression_concurrent', label: 'Pression', contribution: 18, detail: 'Concurrents' },
    ],
    leads_count: 1,
    created_at: daysAgo(15),
    updated_at: hoursAgo(18),
  },
];

function minutes_ish(m: number) {
  return new Date(now.getTime() - m * 60_000).toISOString();
}
