import { NotificationVeille } from '../types';

const now = new Date('2026-04-24T14:00:00Z');
const minAgo = (m: number) => new Date(now.getTime() - m * 60_000).toISOString();
const hoursAgo = (h: number) => new Date(now.getTime() - h * 3_600_000).toISOString();
const daysAgo = (d: number) => new Date(now.getTime() - d * 86_400_000).toISOString();

export const NOTIFICATIONS: NotificationVeille[] = [
  {
    id: 'nt_001',
    user_id: 'user_001',
    source_type: 'alerte',
    source_id: 'al_001',
    object_type: 'bien',
    object_id: 'bs_001',
    title: 'Baisse de prix détectée',
    message: 'Le prix de vente a baissé de 530 000 € à 510 000 € soit -20 000 € (-3,8 %).',
    explanation: "Passe 2 % sous la médiane DVF du quartier et sous votre fourchette haute d'estimation.",
    business_impact: "Bonne opportunité d'achat. Probabilité de vente +18 % et compétitivité améliorée.",
    priority: 'haute',
    status: 'unread',
    recommended_action: 'ouvrir_bien',
    secondary_actions: ['creer_action', 'mettre_a_jour_suivi'],
    freshness_label: 'il y a 25 min',
    event_at: minAgo(25),
    created_at: minAgo(25),
    is_aggregated: false,
    triggering_alertes: ['al_001'],
    metadata: {
      prix_avant: 530000,
      prix_apres: 510000,
      variation_pct: -3.8,
      prix_m2: 9273,
      surface: 55,
      dpe: 'D',
      adresse: '45 rue Lecourbe · 75015 Paris',
      portail: 'SeLoger',
      type_bien: 'Appartement T2',
      zone: 'Paris 15e',
    },
    links: [
      { label: 'Ouvrir le bien', route: '/app/veille/biens-suivis?bien=bs_001', module: 'biens' },
      { label: "Voir l'alerte liée", route: '/app/veille/alertes?alerte=al_001', module: 'veille' },
      { label: 'Comparer sur observatoire', route: '/app/observatoire/marche', module: 'observatoire' },
    ],
  },
  {
    id: 'nt_002',
    user_id: 'user_001',
    source_type: 'agence_concurrente',
    source_id: 'ag_001',
    object_type: 'bien',
    object_id: 'bien_mandat_001',
    title: 'Mandat simple sous pression',
    message: 'Concurrent · Orpi Convention. Prix affiché : 490 000 € (vs 515 000 € votre mandat).',
    explanation: 'Écart -4,9 % sur bien similaire. Risque de perte du mandat client.',
    business_impact: 'Préparer un point vendeur avec argumentaire de repositionnement.',
    priority: 'haute',
    status: 'unread',
    recommended_action: 'creer_action',
    secondary_actions: ['preparer_message'],
    freshness_label: 'il y a 1h',
    event_at: hoursAgo(1),
    created_at: hoursAgo(1),
    is_aggregated: false,
    triggering_alertes: ['al_003'],
    metadata: {
      agence_concurrente: 'Orpi Convention',
      prix_mandat: 515000,
      prix_concurrent: 490000,
      ecart_pct: -4.9,
      bien: 'Studio 24m² · Paris 15e',
    },
    links: [
      { label: 'Voir le mandat', route: '/app/biens/portefeuille', module: 'biens' },
      { label: "Voir l'agence", route: '/app/veille/agences-concurrentes?agence=ag_001', module: 'veille' },
    ],
  },
  {
    id: 'nt_003',
    user_id: 'user_001',
    source_type: 'observatoire',
    source_id: 'obs_zone_15',
    object_type: 'zone',
    object_id: 'zone_paris_15',
    title: 'Stock en hausse sur votre zone',
    message: "+18 % d'annonces sur Paris 15e vs semaine précédente.",
    explanation: 'Tension du marché en baisse.',
    business_impact: 'Élargir vos critères prix pour capter les opportunités.',
    priority: 'moyenne',
    status: 'unread',
    recommended_action: 'ouvrir_observatoire',
    secondary_actions: ['creer_action'],
    freshness_label: 'il y a 2h',
    event_at: hoursAgo(2),
    created_at: hoursAgo(2),
    is_aggregated: false,
    triggering_alertes: ['al_012'],
    metadata: { zone: 'Paris 15e', variation_pct: 18, stock_avant: 420, stock_apres: 496 },
    links: [{ label: 'Ouvrir Observatoire', route: '/app/observatoire/marche', module: 'observatoire' }],
  },
  {
    id: 'nt_004',
    user_id: 'user_001',
    source_type: 'alerte',
    source_id: 'al_001',
    object_type: 'zone',
    object_id: 'zone_paris_15',
    title: '3 baisses de prix sur Paris 15e',
    message: '3 événements agrégés ce matin. Baisse moyenne : -3,2 %.',
    explanation: 'Le volume de baisses sur la zone suggère une tension acheteur en évolution.',
    business_impact: 'Potentiel de négociation à observer sur votre portefeuille Paris 15e.',
    priority: 'moyenne',
    status: 'unread',
    recommended_action: 'ouvrir_observatoire',
    secondary_actions: ['creer_action'],
    freshness_label: 'ce matin',
    event_at: hoursAgo(5),
    created_at: hoursAgo(5),
    is_aggregated: true,
    aggregate_count: 3,
    triggering_alertes: ['al_001'],
    metadata: { bien_ids: ['bs_001', 'bs_002', 'bs_003'], variation_moyenne_pct: -3.2 },
    links: [
      { label: 'Voir les 3 biens', route: '/app/veille/biens-suivis', module: 'veille', count: 3 },
      { label: 'Observatoire Paris 15e', route: '/app/observatoire/marche', module: 'observatoire' },
    ],
  },
  {
    id: 'nt_005',
    user_id: 'user_001',
    source_type: 'estimation',
    source_id: 'estim_001',
    object_type: 'rapport',
    object_id: 'rap_001',
    title: 'Avis de valeur ouvert',
    message: 'M. Dupont · Paris 15e. Ouvert depuis 2 jours.',
    explanation: 'Relance recommandée pour qualifier le projet.',
    business_impact: 'Convertir en mandat exclusif.',
    priority: 'moyenne',
    status: 'todo',
    recommended_action: 'preparer_message',
    secondary_actions: ['creer_action'],
    freshness_label: 'hier',
    event_at: daysAgo(1),
    created_at: daysAgo(1),
    is_aggregated: false,
    triggering_alertes: ['al_022'],
    metadata: { client: 'M. Dupont', rapport_type: 'Avis de valeur', zone: 'Paris 15e' },
    links: [{ label: 'Ouvrir le rapport', route: '/app/estimation/avis-valeur', module: 'estimation' }],
  },
  {
    id: 'nt_006',
    user_id: 'user_001',
    source_type: 'investissement',
    source_id: 'inv_001',
    object_type: 'opportunite',
    object_id: 'bs_002',
    title: 'Bien suivi devenu opportunité',
    message: 'Appartement T3 · Paris 15e. Prix -5 % depuis dernier passage.',
    explanation: 'Rentabilité locative estimée à 3,9 %.',
    business_impact: "Opportunité d'acquisition pour projet investisseur.",
    priority: 'info',
    status: 'todo',
    recommended_action: 'ouvrir_analyse',
    secondary_actions: ['creer_dossier'],
    freshness_label: 'hier',
    event_at: daysAgo(1),
    created_at: daysAgo(1),
    is_aggregated: false,
    triggering_alertes: ['al_018'],
    metadata: { bien: 'Appartement T3 · Paris 15e', rendement_pct: 3.9, variation_pct: -5 },
    links: [{ label: 'Ouvrir analyse', route: '/app/investissement/opportunites', module: 'investissement' }],
  },
  {
    id: 'nt_007',
    user_id: 'user_001',
    source_type: 'alerte',
    source_id: 'al_011',
    object_type: 'alerte',
    object_id: 'al_011',
    title: 'Nouvelle alerte correspondante',
    message: '3 nouveaux biens correspondent à votre recherche.',
    explanation: '1 bien dépasse votre seuil de qualité.',
    business_impact: 'Ouvrir les biens et décider si on les suit.',
    priority: 'haute',
    status: 'todo',
    recommended_action: 'ouvrir_bien',
    secondary_actions: ['creer_action'],
    freshness_label: 'il y a 3j',
    event_at: daysAgo(3),
    created_at: daysAgo(3),
    is_aggregated: true,
    aggregate_count: 3,
    triggering_alertes: ['al_011'],
    metadata: { biens_count: 3, budget: '< 500 000 €' },
    links: [{ label: 'Voir les biens', route: '/app/biens/annonces', module: 'biens' }],
  },
  {
    id: 'nt_008',
    user_id: 'user_001',
    source_type: 'observatoire',
    source_id: 'obs_biens_sim',
    object_type: 'zone',
    object_id: 'zone_paris_15',
    title: 'Biens similaires en baisse',
    message: 'Analyse comparables · Paris 15e. -2,3 % en moyenne sur 15 biens.',
    explanation: 'Tendance cumulative sur les 30 derniers jours.',
    business_impact: 'Argumentaire de repositionnement possible sur vos mandats.',
    priority: 'moyenne',
    status: 'done',
    recommended_action: 'ouvrir_observatoire',
    secondary_actions: [],
    freshness_label: 'il y a 4j',
    event_at: daysAgo(4),
    created_at: daysAgo(4),
    done_at: daysAgo(3),
    is_aggregated: false,
    triggering_alertes: ['al_012'],
    metadata: { variation_moyenne: -2.3, biens_count: 15 },
    links: [{ label: 'Voir le rapport', route: '/app/observatoire/marche', module: 'observatoire' }],
  },
  {
    id: 'nt_009',
    user_id: 'user_001',
    source_type: 'alerte',
    source_id: 'al_004',
    object_type: 'bien',
    object_id: 'bien_dpe_g_001',
    title: 'DPE G détecté',
    message: 'Maison · Paris 15e · 120 m² · DPE G détecté sur annonce Leboncoin.',
    explanation: 'Pression réglementaire 2028 — risque de retrait locatif.',
    business_impact: "Opportunité d'approche propriétaire pour rénovation / vente.",
    priority: 'moyenne',
    status: 'unread',
    recommended_action: 'ouvrir_annonce',
    secondary_actions: ['creer_lead'],
    freshness_label: 'il y a 6h',
    event_at: hoursAgo(6),
    created_at: hoursAgo(6),
    is_aggregated: false,
    triggering_alertes: ['al_004'],
    metadata: { dpe: 'G', type_bien: 'Maison', surface: 120, zone: 'Paris 15e' },
    links: [{ label: "Ouvrir l'annonce", route: '#', module: 'biens' }],
  },
  {
    id: 'nt_010',
    user_id: 'user_001',
    source_type: 'alerte',
    source_id: 'al_005',
    object_type: 'zone',
    object_id: 'zone_paris_15',
    title: '2 nouveaux permis de construire',
    message: 'PC + DP déposés rue Cambronne · Paris 15e.',
    explanation: 'Projet de surélévation (5 logements prévus).',
    business_impact: 'Anticiper les mutations à venir dans le quartier.',
    priority: 'info',
    status: 'read',
    recommended_action: 'ouvrir_zone',
    secondary_actions: [],
    freshness_label: 'il y a 2j',
    event_at: daysAgo(2),
    created_at: daysAgo(2),
    read_at: daysAgo(1),
    is_aggregated: true,
    aggregate_count: 2,
    triggering_alertes: ['al_005'],
    metadata: { zone: 'Paris 15e', adresse: 'rue Cambronne' },
    links: [{ label: 'Voir sur Observatoire', route: '/app/observatoire/contexte-local', module: 'observatoire' }],
  },
  {
    id: 'nt_011',
    user_id: 'user_001',
    source_type: 'prospection',
    source_id: 'prosp_001',
    object_type: 'bien',
    object_id: 'bs_004',
    title: 'Signal Prospection haute priorité',
    message: 'Bien en vente sur votre zone de prospection · Score 87/100.',
    explanation: 'Vendeur identifiable via fichier SIREN.',
    business_impact: 'Prise de contact prioritaire.',
    priority: 'haute',
    status: 'unread',
    recommended_action: 'creer_lead',
    secondary_actions: ['creer_action'],
    freshness_label: 'il y a 4h',
    event_at: hoursAgo(4),
    created_at: hoursAgo(4),
    is_aggregated: false,
    triggering_alertes: [],
    metadata: { score: 87, zone: 'Paris 15e' },
    links: [{ label: 'Ouvrir Radar', route: '/app/prospection/radar', module: 'prospection' }],
  },
  {
    id: 'nt_012',
    user_id: 'user_001',
    source_type: 'bien_suivi',
    source_id: 'bs_005',
    object_type: 'bien',
    object_id: 'bs_005',
    title: 'Nouvelle source détectée',
    message: "Appartement T2 · Paris 12e republié sur Bien'ici.",
    explanation: 'Annonce déjà suivie sur SeLoger. Deuxième source = signal de changement de stratégie.',
    business_impact: 'Possible changement de mandataire.',
    priority: 'info',
    status: 'read',
    recommended_action: 'ouvrir_annonce',
    secondary_actions: [],
    freshness_label: 'hier',
    event_at: daysAgo(1),
    created_at: daysAgo(1),
    read_at: daysAgo(1),
    is_aggregated: false,
    triggering_alertes: [],
    metadata: { portail: "Bien'ici" },
    links: [{ label: 'Ouvrir le bien', route: '/app/veille/biens-suivis?bien=bs_005', module: 'veille' }],
  },
  {
    id: 'nt_013',
    user_id: 'user_001',
    source_type: 'alerte',
    source_id: 'al_002',
    object_type: 'bien',
    object_id: 'bs_006',
    title: 'Baisse de prix',
    message: 'Appartement T2 · Paris 15e. -8 000 € (-2,5 %).',
    explanation: "Passe sous la fourchette haute d'estimation.",
    business_impact: "Relancer l'acquéreur potentiel.",
    priority: 'moyenne',
    status: 'read',
    recommended_action: 'ouvrir_bien',
    secondary_actions: ['creer_action'],
    freshness_label: 'hier',
    event_at: daysAgo(1),
    created_at: daysAgo(1),
    read_at: daysAgo(1),
    is_aggregated: false,
    triggering_alertes: ['al_002'],
    metadata: { prix_avant: 320000, prix_apres: 312000, variation_pct: -2.5 },
    links: [{ label: 'Ouvrir le bien', route: '/app/veille/biens-suivis?bien=bs_006', module: 'veille' }],
  },
  {
    id: 'nt_014',
    user_id: 'user_001',
    source_type: 'alerte',
    source_id: 'al_006',
    object_type: 'annonce',
    object_id: 'ann_studio_001',
    title: 'Studio sous 250 k€',
    message: 'Studio · Paris 15e · 24 m². Prix 245 000 €.',
    explanation: 'Bien conforme à votre profil acheteur.',
    business_impact: 'Planifier visite rapidement.',
    priority: 'info',
    status: 'todo',
    recommended_action: 'creer_action',
    secondary_actions: ['ouvrir_bien'],
    freshness_label: 'il y a 5h',
    event_at: hoursAgo(5),
    created_at: hoursAgo(5),
    is_aggregated: false,
    triggering_alertes: ['al_006'],
    metadata: { prix: 245000, surface: 24 },
    links: [{ label: 'Ouvrir annonce', route: '#', module: 'biens' }],
  },
  {
    id: 'nt_015',
    user_id: 'user_001',
    source_type: 'observatoire',
    source_id: 'obs_delai_07',
    object_type: 'zone',
    object_id: 'zone_paris_7',
    title: 'Délai de vente en hausse',
    message: 'Paris 7e · délai moyen 78j (+12j vs M-1).',
    explanation: 'Marché en décélération modérée.',
    business_impact: 'Ajuster stratégie de prix sur vos mandats.',
    priority: 'info',
    status: 'ignored',
    recommended_action: 'ouvrir_observatoire',
    secondary_actions: [],
    freshness_label: 'il y a 5j',
    event_at: daysAgo(5),
    created_at: daysAgo(5),
    ignored_at: daysAgo(5),
    is_aggregated: false,
    triggering_alertes: ['al_024'],
    metadata: { zone: 'Paris 7e', delai_actuel: 78 },
    links: [{ label: 'Ouvrir Observatoire', route: '/app/observatoire/tension', module: 'observatoire' }],
  },
  {
    id: 'nt_016',
    user_id: 'user_001',
    source_type: 'alerte',
    source_id: 'al_013',
    object_type: 'bien',
    object_id: 'bs_007',
    title: 'Baisse Lyon 3e',
    message: 'Appartement T3 · Lyon 3e. -18 000 € (-5,2 %).',
    explanation: "Sous fourchette basse d'estimation.",
    business_impact: "Signaler à l'acheteur enregistré sur ce profil.",
    priority: 'moyenne',
    status: 'unread',
    recommended_action: 'ouvrir_bien',
    secondary_actions: ['creer_action'],
    freshness_label: 'il y a 8h',
    event_at: hoursAgo(8),
    created_at: hoursAgo(8),
    is_aggregated: false,
    triggering_alertes: ['al_013'],
    metadata: { variation_pct: -5.2 },
    links: [{ label: 'Ouvrir le bien', route: '/app/veille/biens-suivis', module: 'veille' }],
  },
];

export const UNREAD_COUNT = NOTIFICATIONS.filter(n => n.status === 'unread').length;
