import type { WidgetInstance, WidgetStep, ResultField } from '../types';

export const MOCK_WIDGETS: WidgetInstance[] = [
  {
    id: 'wdg_estimation_vendeur',
    type: 'estimation_vendeur',
    slug: 'estimation-vendeur',
    title: 'Widget estimation vendeur',
    domain: 'estimation.maisondexception.fr',
    domainUrl: 'https://estimation.maisondexception.fr',
    status: 'active',
    version: 'v1.2',
    leadsLast30d: 872,
    conversionRate: 11.8,
    lastActivity: "Aujourd'hui à 09:41",
    previewThumb: 'seller',
  },
  {
    id: 'wdg_projet_investisseur',
    type: 'projet_investisseur',
    slug: 'projet-investisseur',
    title: 'Widget projet investisseur',
    domain: 'invest.maisondexception.fr',
    domainUrl: 'https://invest.maisondexception.fr',
    status: 'active',
    version: 'v1.0',
    leadsLast30d: 371,
    conversionRate: 9.6,
    lastActivity: 'Hier à 16:32',
    previewThumb: 'investor',
  },
];

export const SELLER_STEPS: WidgetStep[] = [
  { id: 'intro', index: 1, name: 'Intro', subtitle: 'Présentation du parcours', active: true, complete: true },
  { id: 'adresse', index: 2, name: 'Adresse', subtitle: 'Saisie de l’adresse BAN', active: true, complete: true, formFields: ['address'] },
  {
    id: 'bien',
    index: 3,
    name: 'Bien',
    subtitle: 'Type, surface, pièces',
    active: true,
    complete: true,
    formFields: ['property_type', 'surface', 'rooms', 'bedrooms', 'floor'],
  },
  {
    id: 'details',
    index: 4,
    name: 'Détails',
    subtitle: 'Année, état, DPE',
    active: true,
    complete: true,
    formFields: ['year_built', 'condition', 'dpe', 'equipment'],
  },
  {
    id: 'resultat',
    index: 5,
    name: 'Résultat',
    subtitle: 'Estimation indicative',
    active: true,
    complete: true,
  },
  {
    id: 'contact',
    index: 6,
    name: 'Contact',
    subtitle: 'Coordonnées et consentement',
    active: true,
    complete: true,
    formFields: ['first_name', 'last_name', 'email', 'phone', 'project', 'timeline', 'contact_preference', 'consent'],
  },
  { id: 'confirmation', index: 7, name: 'Confirmation', subtitle: 'Merci et prochaines étapes', active: true, complete: true },
];

export const INVESTOR_STEPS: WidgetStep[] = [
  { id: 'intro', index: 1, name: 'Intro', subtitle: 'Présentation du parcours', active: true, complete: true },
  {
    id: 'projet',
    index: 2,
    name: 'Projet',
    subtitle: 'Objectif et horizon',
    active: true,
    complete: true,
    formFields: ['goal', 'horizon', 'support_level'],
  },
  {
    id: 'budget',
    index: 3,
    name: 'Budget',
    subtitle: 'Enveloppe et financement',
    active: true,
    complete: true,
    formFields: ['budget', 'down_payment', 'target_yield', 'monthly_effort'],
  },
  {
    id: 'zone-type',
    index: 4,
    name: 'Zone & type',
    subtitle: 'Préférences géographiques',
    active: true,
    complete: true,
    formFields: ['zones', 'property_types', 'rental_type'],
  },
  {
    id: 'strategie',
    index: 5,
    name: 'Stratégie',
    subtitle: 'Recommandation ML',
    active: true,
    complete: true,
  },
  {
    id: 'contact',
    index: 6,
    name: 'Contact',
    subtitle: 'Coordonnées et consentement',
    active: true,
    complete: true,
    formFields: ['first_name', 'last_name', 'email', 'phone', 'contact_preference', 'availability', 'consent'],
  },
  { id: 'confirmation', index: 7, name: 'Confirmation', subtitle: 'Merci et prochaines étapes', active: true, complete: true },
];

export const SELLER_RESULT_FIELDS: ResultField[] = [
  { id: 'price_range', label: 'Fourchette de prix', visiblePublic: true, visibleAgent: true },
  { id: 'price_per_sqm', label: 'Prix au m²', visiblePublic: false, visibleAgent: true },
  { id: 'confidence', label: 'Indice de confiance (pill)', visiblePublic: true, visibleAgent: true },
  { id: 'reassurance', label: 'Texte de réassurance', visiblePublic: true, visibleAgent: false },
  { id: 'days_on_market', label: 'Délai de vente estimé', visiblePublic: false, visibleAgent: true },
  { id: 'market_trend', label: 'Marché local', visiblePublic: true, visibleAgent: true },
  { id: 'recent_sales', label: 'Ventes récentes à proximité', visiblePublic: true, visibleAgent: true },
  { id: 'comparables', label: 'Comparables détaillés', visiblePublic: false, visibleAgent: true },
  { id: 'conversation_angle', label: 'Angle de conversation recommandé', visiblePublic: false, visibleAgent: true },
  { id: 'maturity', label: 'Maturité vendeur estimée', visiblePublic: false, visibleAgent: true },
  { id: 'tension', label: 'Tension locale', visiblePublic: false, visibleAgent: true },
  { id: 'strength', label: 'Point fort principal', visiblePublic: false, visibleAgent: true },
  { id: 'warning', label: 'Point de vigilance', visiblePublic: false, visibleAgent: true },
];

export const INVESTOR_RESULT_FIELDS: ResultField[] = [
  { id: 'strategy_primary', label: 'Stratégie principale (carte)', visiblePublic: true, visibleAgent: true },
  { id: 'scenarios', label: 'Scénarios alternatifs (2)', visiblePublic: true, visibleAgent: true },
  { id: 'target_rent', label: 'Loyer cible', visiblePublic: true, visibleAgent: true },
  { id: 'gross_yield', label: 'Rendement brut estimé', visiblePublic: true, visibleAgent: true },
  { id: 'rental_tension', label: 'Tension locative', visiblePublic: true, visibleAgent: true },
  { id: 'key_points', label: 'Points clés (budget, vigilance, vacance)', visiblePublic: true, visibleAgent: true },
  { id: 'assumptions', label: 'Hypothèses détaillées du calcul', visiblePublic: false, visibleAgent: true },
  { id: 'expert_comparables', label: 'Comparables experts', visiblePublic: false, visibleAgent: true },
  { id: 'financing', label: 'Montage financier détaillé', visiblePublic: false, visibleAgent: true },
  { id: 'risk_scoring', label: 'Scoring risque/rendement', visiblePublic: false, visibleAgent: true },
  { id: 'conversation_angle', label: 'Angle de conversation recommandé', visiblePublic: false, visibleAgent: true },
  { id: 'project_maturity', label: 'Maturité projet', visiblePublic: false, visibleAgent: true },
  { id: 'next_best_action', label: 'Prochaine meilleure action', visiblePublic: false, visibleAgent: true },
];
