import type {
  DashboardAlertItem,
  DashboardKpi,
  DashboardPortfolioHealth,
  DashboardPriorityItem,
  DashboardPulseMarket,
  DashboardQuickAction,
  DashboardRapportItem,
  DashboardSummary,
  DashboardTerritoryItem,
} from '../types';

export const MOCK_KPIS: DashboardKpi[] = [
  {
    id: 'ca_realise_mois',
    label: 'CA réalisé',
    value: '74 200 €',
    delta: { value: '+12%', trend: 'up', is_positive: true },
    context: 'vs objectif : 78%',
    source_module: 'performance',
    href: '/app/activite/performance?period=mois',
    action_label: 'Voir le reporting',
    icon: 'TrendingUp',
  },
  {
    id: 'mandats_signes',
    label: 'Mandats signés',
    value: 17,
    delta: { value: '+2', trend: 'up', is_positive: true },
    context: 'dont 6 exclusifs',
    source_module: 'leads',
    href: '/app/activite/leads?stage=mandat&period=mois',
    action_label: 'Voir les mandats',
    icon: 'FileSignature',
  },
  {
    id: 'ca_pipe_pondere',
    label: 'CA pipe pondéré',
    value: '286 450 €',
    delta: { value: '+18%', trend: 'up', is_positive: true },
    context: 'sur 90 jours',
    source_module: 'performance',
    href: '/app/activite/performance?view=pipe',
    action_label: 'Voir le pipe',
    icon: 'Wallet',
  },
  {
    id: 'taux_transformation',
    label: 'Taux transformation',
    value: '21%',
    delta: { value: '+2 pts', trend: 'up', is_positive: true },
    context: 'lead → mandat',
    source_module: 'performance',
    href: '/app/activite/performance?view=funnel',
    action_label: 'Voir le funnel',
    icon: 'Filter',
  },
  {
    id: 'part_marche',
    label: 'Part de marché',
    value: '0,87%',
    delta: { value: '+0,12 pt', trend: 'up', is_positive: true },
    context: 'Paris 15e · potentiel 2,5%',
    source_module: 'performance',
    href: '/app/activite/performance?view=marche',
    action_label: 'Voir le potentiel',
    icon: 'Target',
  },
];

export const MOCK_PRIORITIES: DashboardPriorityItem[] = [
  {
    id: 'P-001',
    rank: 1,
    type: 'action_en_retard',
    urgency: 'en_retard',
    urgency_label: 'En retard 3j',
    title: 'Relancer M. Dupont',
    subtitle: 'Mandat expire dans 12j',
    source_module: 'estimation',
    source_label: 'Estimation',
    linked_object_type: 'lead',
    linked_object_id: 'L-421',
    priority_score: 92,
    cta_primary: { label: 'Appeler', action: 'open_drawer', drawer_ref: 'lead:L-421' },
    cta_secondary: { label: 'Reporter', action: 'open_modal' },
  },
  {
    id: 'P-002',
    rank: 2,
    type: 'rdv_du_jour',
    urgency: 'aujourdhui',
    urgency_label: '14h30',
    title: 'RDV estimation',
    subtitle: '45 rue Lecourbe',
    source_module: 'agenda',
    source_label: 'Agenda',
    linked_object_type: 'rdv',
    linked_object_id: 'RDV-112',
    priority_score: 88,
    cta_primary: { label: 'Brief', action: 'open_drawer', drawer_ref: 'rdv:RDV-112' },
  },
  {
    id: 'P-003',
    rank: 3,
    type: 'signature_imminente',
    urgency: 'aujourdhui',
    urgency_label: "Aujourd'hui",
    title: 'Signer compromis Dossier Lyon',
    subtitle: 'Projet Pinel · Lyon 3e',
    source_module: 'investissement',
    source_label: 'Invest',
    linked_object_type: 'dossier',
    linked_object_id: 'D-102',
    priority_score: 86,
    cta_primary: { label: 'Ouvrir', action: 'open_route', href: '/app/investissement/dossiers/D-102' },
  },
  {
    id: 'P-004',
    rank: 4,
    type: 'rdv_a_preparer',
    urgency: 'cette_semaine',
    urgency_label: 'Cette semaine',
    title: 'Visite T3 rue Vaugirard',
    subtitle: 'M. et Mme Duval',
    source_module: 'leads',
    source_label: 'Leads',
    linked_object_type: 'lead',
    linked_object_id: 'L-512',
    priority_score: 64,
    cta_primary: { label: 'Préparer', action: 'open_drawer', drawer_ref: 'lead:L-512' },
  },
];

export const MOCK_ALERTS: DashboardAlertItem[] = [
  {
    id: 'A-001',
    rank: 1,
    type: 'bien_suivi_baisse_prix',
    icon: 'TrendingDown',
    title: 'Baisse -4,2% sur bien suivi',
    subtitle: 'Appartement 3 pièces · 65 m² · 75015',
    source_module: 'veille',
    source_label: 'Observatoire',
    linked_object_type: 'bien_suivi',
    linked_object_id: 'BS-331',
    zone_label: 'Paris 15e',
    occurred_at: '2026-04-24T08:15:00Z',
    impact_score: 88,
    cta_primary: { label: 'Voir', action: 'open_drawer', drawer_ref: 'bien:B-331' },
    is_unread: true,
  },
  {
    id: 'A-002',
    rank: 2,
    type: 'agence_concurrente_mandat',
    icon: 'Building2',
    title: '3 nouveaux mandats agence concurrente',
    subtitle: 'Dans votre zone de chasse',
    source_module: 'veille',
    source_label: 'Concurrence',
    zone_label: 'Paris 15e',
    occurred_at: '2026-04-24T07:00:00Z',
    impact_score: 80,
    cta_primary: { label: 'Voir', action: 'open_route', href: '/app/veille/agences-concurrentes' },
    is_unread: true,
  },
  {
    id: 'A-003',
    rank: 3,
    type: 'rapport_rouvert_multiple',
    icon: 'FileText',
    title: 'Avis de valeur rouvert 3 fois',
    subtitle: 'M. Bernard · 12 rue Desnouettes',
    source_module: 'estimation',
    source_label: 'Estimation',
    linked_object_type: 'rapport',
    linked_object_id: 'R-914',
    occurred_at: '2026-04-23T18:00:00Z',
    impact_score: 75,
    cta_primary: { label: 'Relancer', action: 'open_drawer', drawer_ref: 'rapport:R-914' },
    is_unread: false,
  },
  {
    id: 'A-004',
    rank: 4,
    type: 'signal_dpe',
    icon: 'Zap',
    title: 'Signal DPE · 2 lots concernés',
    subtitle: 'Immeuble · 8 lots · DPE F/G',
    source_module: 'prospection',
    source_label: 'Réglementaire',
    linked_object_type: 'bien',
    linked_object_id: 'B-555',
    zone_label: 'Paris 15e',
    occurred_at: '2026-04-23T12:00:00Z',
    impact_score: 70,
    cta_primary: { label: 'Voir', action: 'open_modal', href: '/app/activite/leads?action=create&bien=B-555' },
    is_unread: false,
  },
  {
    id: 'A-005',
    rank: 5,
    type: 'marche_zone_variation',
    icon: 'BarChart3',
    title: 'Prix médian 75015 +1,2% ce mois',
    subtitle: 'Évolution vs mois précédent',
    source_module: 'observatoire',
    source_label: 'Marché',
    zone_label: 'Paris 15e',
    occurred_at: '2026-04-22T00:00:00Z',
    impact_score: 48,
    cta_primary: { label: 'Détails', action: 'open_route', href: '/app/observatoire/marche?zone=paris-15' },
    is_unread: false,
  },
];

export const MOCK_RAPPORTS: DashboardRapportItem[] = [
  {
    id: 'RE-001',
    rapport_id: 'R-911',
    type: 'avis_valeur',
    type_label: 'Avis de valeur',
    client: { name: 'Mme Martin', linked_lead_id: 'L-201' },
    sent_at: '2026-04-19T14:00:00Z',
    sent_label: '27 mai 2025',
    opens_count: 3,
    last_opened_at: '2026-04-23T18:00:00Z',
    last_opened_label: '29 mai 2025',
    engagement_state: 'chaud',
    relance_status: 'jamais',
    priority_engagement_score: 85,
    cta_primary: { label: 'Relancer', action: 'open_drawer', drawer_ref: 'rapport:R-911' },
  },
  {
    id: 'RE-002',
    rapport_id: 'R-914',
    type: 'etude_locative',
    type_label: 'Étude de marché',
    client: { name: 'M. Prévost', linked_lead_id: 'L-214' },
    sent_at: '2026-04-12T10:30:00Z',
    sent_label: '26 mai 2025',
    opens_count: 2,
    last_opened_at: '2026-04-24T10:00:00Z',
    last_opened_label: '28 mai 2025',
    engagement_state: 'ouvert_passif',
    relance_status: 'jamais',
    priority_engagement_score: 70,
    cta_primary: { label: 'Appeler', action: 'open_drawer', drawer_ref: 'rapport:R-914' },
  },
  {
    id: 'RE-003',
    rapport_id: 'R-920',
    type: 'dossier_invest',
    type_label: 'Analyse investissement',
    client: { name: 'Durand SAS', linked_lead_id: 'L-230' },
    sent_at: '2026-04-21T09:00:00Z',
    sent_label: '24 mai 2025',
    opens_count: 1,
    last_opened_at: '2026-04-23T14:00:00Z',
    last_opened_label: '24 mai 2025',
    engagement_state: 'ouvert_passif',
    relance_status: 'jamais',
    priority_engagement_score: 55,
    cta_primary: { label: 'Relancer', action: 'open_drawer', drawer_ref: 'rapport:R-920' },
  },
  {
    id: 'RE-004',
    rapport_id: 'R-930',
    type: 'dossier_invest',
    type_label: "Sélection d'opportunités",
    client: { name: 'Projet Lyon', linked_lead_id: 'L-301' },
    sent_at: '2026-04-22T11:00:00Z',
    sent_label: '22 mai 2025',
    opens_count: 4,
    last_opened_at: '2026-04-24T09:00:00Z',
    last_opened_label: '25 mai 2025',
    engagement_state: 'tres_chaud',
    relance_status: 'jamais',
    priority_engagement_score: 92,
    cta_primary: { label: 'Archiver', action: 'open_drawer', drawer_ref: 'rapport:R-930' },
  },
];

export const MOCK_PORTFOLIO_HEALTH: DashboardPortfolioHealth = {
  total_mandats_actifs: 23,
  health_score: 72,
  trend_30d: 'stable',
  health_categories: [
    {
      id: 'expirant_court_terme',
      severity: 'critical',
      icon: 'CalendarX',
      label: 'Mandats expirant < 15j',
      count: 6,
      excerpt: 'À relancer en priorité',
      linked_bien_ids: ['B-101', 'B-102', 'B-103'],
      cta: { label: 'Voir tous', action: 'open_route', href: '/app/biens/portefeuille?filter=expirant-15j' },
    },
    {
      id: 'sans_mouvement_long',
      severity: 'warning',
      icon: 'Clock',
      label: 'Mandats sans mouvement > 60j',
      count: 11,
      excerpt: 'Risque de décroissance',
      linked_bien_ids: ['B-110', 'B-111', 'B-112'],
      cta: { label: 'Voir tous', action: 'open_route', href: '/app/biens/portefeuille?filter=sans-mouvement' },
    },
    {
      id: 'overpricing',
      severity: 'warning',
      icon: 'AlertTriangle',
      label: 'Overpricing vs marché',
      count: 7,
      excerpt: 'Prix > marché de +7%',
      linked_bien_ids: ['B-120', 'B-121'],
      cta: { label: 'Voir détails', action: 'open_route', href: '/app/biens/portefeuille?filter=overpricing' },
    },
    {
      id: 'mandat_simple_candidat_exclusif',
      severity: 'opportunity',
      icon: 'Sparkles',
      label: 'Mandats simples à convertir',
      count: 9,
      excerpt: "Forte demande vs offre",
      linked_bien_ids: ['B-130', 'B-131'],
      cta: { label: 'Stratégie', action: 'open_drawer', drawer_ref: 'portfolio-strategy' },
    },
  ],
};

export const MOCK_PULSE_MARKET: DashboardPulseMarket = {
  zone_id: 'paris-15',
  zone_label: 'Paris 15e',
  period: '30j',
  cells: [
    { scope: 'mon_portefeuille', indicator: 'nouveaux', value: 12, href: '/app/biens/portefeuille?filter=nouveau&period=30j' },
    { scope: 'mon_portefeuille', indicator: 'baisses_prix', value: 8, href: '/app/biens/portefeuille?filter=baisse-prix&period=30j' },
    { scope: 'mon_portefeuille', indicator: 'expires', value: 5, href: '/app/biens/portefeuille?filter=expire&period=30j' },
    { scope: 'mon_portefeuille', indicator: 'vendus', value: 7, href: '/app/biens/portefeuille?filter=vendu&period=30j' },

    { scope: 'biens_suivis', indicator: 'nouveaux', value: 28, href: '/app/veille/biens-suivis?filter=nouveau&period=30j' },
    { scope: 'biens_suivis', indicator: 'baisses_prix', value: 16, href: '/app/veille/biens-suivis?filter=baisse-prix&period=30j' },
    { scope: 'biens_suivis', indicator: 'expires', value: 10, href: '/app/veille/biens-suivis?filter=expire&period=30j' },
    { scope: 'biens_suivis', indicator: 'vendus', value: 12, href: '/app/veille/biens-suivis?filter=vendu&period=30j' },

    { scope: 'annonces_particuliers', indicator: 'nouveaux', value: 45, href: '/app/biens/annonces?source=particulier&filter=nouveau&period=30j&zone=paris-15' },
    { scope: 'annonces_particuliers', indicator: 'baisses_prix', value: 22, href: '/app/biens/annonces?source=particulier&filter=baisse-prix&period=30j&zone=paris-15' },
    { scope: 'annonces_particuliers', indicator: 'expires', value: 18, href: '/app/biens/annonces?source=particulier&filter=expire&period=30j&zone=paris-15' },
    { scope: 'annonces_particuliers', indicator: 'vendus', value: 9, href: '/app/biens/annonces?source=particulier&filter=vendu&period=30j&zone=paris-15' },

    { scope: 'annonces_agences', indicator: 'nouveaux', value: 45, href: '/app/biens/annonces?source=agence&filter=nouveau&period=30j&zone=paris-15' },
    { scope: 'annonces_agences', indicator: 'baisses_prix', value: 31, href: '/app/biens/annonces?source=agence&filter=baisse-prix&period=30j&zone=paris-15' },
    { scope: 'annonces_agences', indicator: 'expires', value: 24, href: '/app/biens/annonces?source=agence&filter=expire&period=30j&zone=paris-15' },
    { scope: 'annonces_agences', indicator: 'vendus', value: 14, href: '/app/biens/annonces?source=agence&filter=vendu&period=30j&zone=paris-15' },

    { scope: 'dvf_vendus', indicator: 'nouveaux', value: 37, href: '/app/biens/dvf?zone=paris-15&period=30j' },
    { scope: 'dvf_vendus', indicator: 'baisses_prix', value: null, href: '' },
    { scope: 'dvf_vendus', indicator: 'expires', value: null, href: '' },
    { scope: 'dvf_vendus', indicator: 'vendus', value: 41, href: '/app/biens/dvf?zone=paris-15&period=30j' },
  ],
  synthese: {
    prix_median_m2: 9420,
    evolution_12m_pct: 2.8,
    tension: 'Forte',
    volume_dvf_12m: 842,
    confidence: 'forte',
  },
};

export const MOCK_TERRITORY: DashboardTerritoryItem[] = [
  {
    id: 'T-001',
    side: 'opportunites',
    rank: 1,
    type: 'opportunite_invest',
    title: 'T2 Paris 15e',
    subtitle: '60 m² · Balcon · Étage élevé',
    score: 92,
    metric_label: 'Rentabilité 4,1%',
    badge: { label: 'Invest', tone: 'violet' },
    source_module: 'investissement',
    linked_object_type: 'opportunite',
    linked_object_id: 'O-201',
    cta_primary: { label: 'Analyser', action: 'open_route', href: '/app/investissement/opportunites?analyse=O-201' },
  },
  {
    id: 'T-002',
    side: 'opportunites',
    rank: 2,
    type: 'bien_suivi_mouvement',
    title: 'Maison Boulogne',
    subtitle: '130 m² · Jardin · Calme',
    score: 87,
    metric_label: 'Rentabilité 3,8%',
    badge: { label: 'Invest', tone: 'violet' },
    source_module: 'veille',
    linked_object_type: 'bien_suivi',
    linked_object_id: 'BS-410',
    cta_primary: { label: 'Analyser', action: 'open_drawer', drawer_ref: 'bien:B-410' },
  },
  {
    id: 'T-003',
    side: 'opportunites',
    rank: 3,
    type: 'opportunite_invest',
    title: 'Studio 75015',
    subtitle: '24 m² · Loué · Dernier étage',
    score: 78,
    metric_label: 'Rentabilité 4,6%',
    badge: { label: 'Invest', tone: 'violet' },
    source_module: 'investissement',
    linked_object_type: 'opportunite',
    linked_object_id: 'O-215',
    cta_primary: { label: 'Analyser', action: 'open_route', href: '/app/investissement/opportunites?analyse=O-215' },
  },
  {
    id: 'T-004',
    side: 'signaux',
    rank: 1,
    type: 'signal_radar',
    title: 'Mandat expire 15 rue Péclet',
    subtitle: 'Fin le 10/06 · Client à risque',
    badge: { label: 'Urgent', tone: 'red' },
    source_module: 'prospection',
    linked_object_type: 'bien',
    linked_object_id: 'B-505',
    cta_primary: { label: 'Voir', action: 'open_drawer', drawer_ref: 'signal:S-333' },
  },
  {
    id: 'T-005',
    side: 'signaux',
    rank: 2,
    type: 'signal_dpe',
    title: 'Propriétaire âgé + 2 héritiers',
    subtitle: 'Situation détectée · Potentiel de vente',
    badge: { label: 'À surveiller', tone: 'amber' },
    source_module: 'prospection',
    linked_object_type: 'bien',
    linked_object_id: 'B-520',
    cta_primary: { label: 'Détails', action: 'open_modal', href: '/app/activite/leads?action=create&bien=B-520' },
  },
  {
    id: 'T-006',
    side: 'signaux',
    rank: 3,
    type: 'signal_marche',
    title: 'Hausse prix médian +1,5%',
    subtitle: 'Paris 15e · vs trimestre précédent',
    badge: { label: 'Positif', tone: 'green' },
    source_module: 'observatoire',
    linked_object_type: 'zone',
    linked_object_id: 'paris-15',
    cta_primary: { label: 'Voir', action: 'open_route', href: '/app/observatoire/marche?zone=paris-15' },
  },
];

export const MOCK_QUICK_ACTIONS: DashboardQuickAction[] = [
  { id: 'qa_estim', label: 'Créer une estimation rapide', icon: 'Calculator', href: '/app/estimation/rapide', source_module: 'estimation' },
  { id: 'qa_lead', label: 'Créer un lead', icon: 'UserPlus', href: '/app/activite/leads', source_module: 'leads' },
  { id: 'qa_bien', label: 'Ajouter un bien', icon: 'Home', href: '/app/biens/portefeuille', source_module: 'biens' },
  { id: 'qa_invest', label: 'Lancer une analyse investissement', icon: 'LineChart', href: '/app/investissement/opportunites', source_module: 'investissement' },
  { id: 'qa_alerte', label: 'Créer une alerte', icon: 'Bell', href: '/app/veille/alertes', source_module: 'veille' },
  { id: 'qa_doss', label: 'Créer un dossier', icon: 'FolderPlus', href: '/app/investissement/dossiers', source_module: 'investissement' },
];

export const MOCK_DASHBOARD_SUMMARY: DashboardSummary = {
  meta: {
    user_id: 'U-001',
    organization_id: 'ORG-001',
    persona: 'agent',
    scope: 'me',
    period: '30j',
    zone_id: 'paris-15',
    zone_label: 'Paris 15e',
    generated_at: '2026-04-24T09:00:00Z',
  },
  kpis: MOCK_KPIS,
  priorities: MOCK_PRIORITIES,
  alerts: MOCK_ALERTS,
  rapports: MOCK_RAPPORTS,
  portfolio_health: MOCK_PORTFOLIO_HEALTH,
  pulse_market: MOCK_PULSE_MARKET,
  territory: MOCK_TERRITORY,
  counts: {
    total_priorities: 14,
    total_alerts_unread: 47,
    total_rapports_90j: 23,
    total_opportunities: 12,
  },
  quick_actions: MOCK_QUICK_ACTIONS,
};
