import { Bien } from '../types';

const img = (seed: string, w = 800, h = 600) => `https://picsum.photos/seed/${seed}/${w}/${h}`;

export const MOCK_BIENS: Bien[] = [
  {
    id: 'bien_001',
    source_principale: 'portefeuille',
    adresse: '10 Rue des Bateliers',
    code_postal: '75013',
    ville: 'Paris 13e',
    latitude: 48.8265,
    longitude: 2.3547,
    geocoding_confidence: 'exact',
    type: 'appartement',
    surface_m2: 60,
    pieces: 3,
    etage: 2,
    nb_etages: 6,
    annee_construction: 1900,
    dpe: 'D',
    statut_commercial: 'mandat_exclusif',
    responsable_nom: 'Thomas Martin',
    responsable_avatar: 'https://i.pravatar.cc/80?u=thomas',
    proprietaire_nom: 'M. & Mme Dupont',
    proprietaire_lead_ref: 'Lead #1234',
    reference_mandat: 'MDT-2024-00142',
    annonces: [
      {
        id: 'ann_001_1',
        bien_id: 'bien_001',
        source: 'seloger',
        url_source: 'https://seloger.com/xxx',
        prix_affiche: 260000,
        prix_m2: 4333,
        publiee_le: '2026-04-22T16:20:00Z',
        statut: 'active',
        evolution_prix: [
          { date: '2026-04-22', prix: 260000 },
        ],
        photos: [img('bat1'), img('bat2'), img('bat3')],
        description: 'Appartement T2 lumineux, 3e étage, proche métro.',
      },
    ],
    ventes_dvf_ids: ['dvf_001'],
    estimations_count: 2,
    avis_valeur_count: 1,
    etudes_locatives_count: 0,
    opportunites_count: 1,
    dossier_ref: null,
    leads_count: 1,
    actions_count: 3,
    alertes_count: 2,
    suivi: true,
    avm: {
      prix_estime: 258000,
      fourchette_basse: 245000,
      fourchette_haute: 275000,
      loyer_estime: 1150,
      loyer_fourchette: [1050, 1250],
      score_confiance: 87,
      features_contributives: [
        { feature: 'Proximité métro Glacière', impact: 'positif', poids: 0.12 },
        { feature: 'DPE D', impact: 'negatif', poids: -0.05 },
        { feature: '3e étage sans asc.', impact: 'negatif', poids: -0.04 },
      ],
      comparables_utilises: ['dvf_001', 'dvf_005', 'dvf_016'],
    },
    photo_principale: img('bat1'),
    photos: [img('bat1'), img('bat2'), img('bat3'), img('bat4')],
    prochaine_action: { libelle: 'Estimation', date: '2026-04-28' },
    flag: null,
    publie_il_y_a: '2h',
    signaux: ['hot', 'nouvelle_annonce'],
    derniere_maj: '2026-04-24T11:24:00Z',
    evenements: [
      { id: 'e1', bien_id: 'bien_001', type: 'annonce_detectee', date: '2026-04-22T16:20:00Z', user: null, titre: 'Annonce détectée sur Seloger' },
      { id: 'e2', bien_id: 'bien_001', type: 'estimation_creee', date: '2026-04-15T10:00:00Z', user: 'Thomas Martin', titre: 'Estimation créée' },
      { id: 'e3', bien_id: 'bien_001', type: 'ajout_portefeuille', date: '2026-04-10T09:00:00Z', user: 'Thomas Martin', titre: 'Ajouté au portefeuille' },
    ],
    created_at: '2026-04-10T09:00:00Z',
    updated_at: '2026-04-24T11:24:00Z',
  },
  {
    id: 'bien_002',
    source_principale: 'portefeuille',
    adresse: '12 Pas Brechon',
    code_postal: '75002',
    ville: 'Paris 2e',
    latitude: 48.8677,
    longitude: 2.3444,
    geocoding_confidence: 'exact',
    type: 'maison',
    surface_m2: 61,
    pieces: 3,
    etage: 0,
    nb_etages: 2,
    annee_construction: 1920,
    dpe: 'C',
    statut_commercial: 'sous_compromis',
    responsable_nom: 'Camille Bernard',
    responsable_avatar: 'https://i.pravatar.cc/80?u=camille',
    proprietaire_nom: 'Mme Martin',
    proprietaire_lead_ref: 'Lead #1241',
    reference_mandat: 'MDT-2024-00141',
    annonces: [],
    ventes_dvf_ids: [],
    estimations_count: 1,
    avis_valeur_count: 1,
    etudes_locatives_count: 0,
    opportunites_count: 0,
    dossier_ref: 'DOS-2024-0077',
    leads_count: 1,
    actions_count: 2,
    alertes_count: 0,
    suivi: false,
    avm: {
      prix_estime: 165000,
      fourchette_basse: 155000,
      fourchette_haute: 175000,
      loyer_estime: 980,
      loyer_fourchette: [900, 1050],
      score_confiance: 74,
      features_contributives: [
        { feature: 'Centre-ville', impact: 'positif', poids: 0.08 },
        { feature: 'Petite surface', impact: 'negatif', poids: -0.03 },
      ],
      comparables_utilises: ['dvf_002'],
    },
    photo_principale: img('bre1'),
    photos: [img('bre1'), img('bre2')],
    prochaine_action: { libelle: 'Relance notaire', date: '2026-06-03' },
    flag: null,
    publie_il_y_a: null,
    signaux: ['echeance'],
    derniere_maj: '2026-04-23T16:08:00Z',
    evenements: [
      { id: 'e1', bien_id: 'bien_002', type: 'dossier_cree', date: '2026-04-05T14:00:00Z', user: 'Camille Bernard', titre: 'Dossier compromis créé' },
    ],
    created_at: '2026-03-28T09:00:00Z',
    updated_at: '2026-04-23T16:08:00Z',
  },
  {
    id: 'bien_003',
    source_principale: 'portefeuille',
    adresse: '103 Rue Bongarde',
    code_postal: '75009',
    ville: 'Paris 9e',
    latitude: 48.8775,
    longitude: 2.3401,
    geocoding_confidence: 'exact',
    type: 'local',
    surface_m2: 4039,
    pieces: null,
    etage: 0,
    nb_etages: 1,
    annee_construction: 1970,
    dpe: null,
    statut_commercial: 'prospection',
    responsable_nom: 'Lucas Morel',
    responsable_avatar: 'https://i.pravatar.cc/80?u=lucas',
    proprietaire_nom: 'SCI Horizon',
    proprietaire_lead_ref: 'Lead #1102',
    reference_mandat: null,
    annonces: [],
    ventes_dvf_ids: ['dvf_003'],
    estimations_count: 0,
    avis_valeur_count: 0,
    etudes_locatives_count: 0,
    opportunites_count: 0,
    dossier_ref: null,
    leads_count: 1,
    actions_count: 1,
    alertes_count: 0,
    suivi: false,
    avm: null,
    photo_principale: img('bon1'),
    photos: [img('bon1')],
    prochaine_action: { libelle: 'Appel', date: '2026-05-27' },
    flag: null,
    publie_il_y_a: null,
    signaux: [],
    derniere_maj: '2026-04-22T09:42:00Z',
    evenements: [],
    created_at: '2026-04-01T10:00:00Z',
    updated_at: '2026-04-22T09:42:00Z',
  },
  {
    id: 'bien_004',
    source_principale: 'annonce',
    adresse: '12 Rue des Bateliers',
    code_postal: '75013',
    ville: 'Paris 13e',
    latitude: 48.8266,
    longitude: 2.355,
    geocoding_confidence: 'exact',
    type: 'appartement',
    surface_m2: 60,
    pieces: 2,
    etage: 3,
    nb_etages: 6,
    annee_construction: 1900,
    dpe: 'D',
    statut_commercial: null,
    responsable_nom: null,
    responsable_avatar: null,
    proprietaire_nom: null,
    proprietaire_lead_ref: null,
    reference_mandat: null,
    annonces: [
      {
        id: 'ann_004_1',
        bien_id: 'bien_004',
        source: 'seloger',
        url_source: 'https://seloger.com/004-1',
        prix_affiche: 260000,
        prix_m2: 4333,
        publiee_le: '2026-04-23T14:00:00Z',
        statut: 'active',
        evolution_prix: [{ date: '2026-04-23', prix: 260000 }],
        photos: [img('a4a'), img('a4b')],
        description: 'Appartement T2 rénové, 3e étage.',
      },
    ],
    ventes_dvf_ids: [],
    estimations_count: 0,
    avis_valeur_count: 0,
    etudes_locatives_count: 0,
    opportunites_count: 0,
    dossier_ref: null,
    leads_count: 0,
    actions_count: 0,
    alertes_count: 0,
    suivi: false,
    avm: {
      prix_estime: 255000,
      fourchette_basse: 240000,
      fourchette_haute: 270000,
      loyer_estime: 1120,
      loyer_fourchette: [1050, 1200],
      score_confiance: 82,
      features_contributives: [
        { feature: 'Rénovation récente', impact: 'positif', poids: 0.06 },
      ],
      comparables_utilises: ['dvf_001'],
    },
    photo_principale: img('a4a'),
    photos: [img('a4a'), img('a4b')],
    prochaine_action: null,
    flag: 'nouveau',
    publie_il_y_a: '2h',
    signaux: ['nouvelle_annonce'],
    derniere_maj: '2026-04-23T14:00:00Z',
    evenements: [
      { id: 'e1', bien_id: 'bien_004', type: 'annonce_detectee', date: '2026-04-23T14:00:00Z', user: null, titre: 'Annonce détectée sur Seloger' },
    ],
    created_at: '2026-04-23T14:00:00Z',
    updated_at: '2026-04-23T14:00:00Z',
  },
  {
    id: 'bien_005',
    source_principale: 'annonce',
    adresse: '53 Rue Émile Cordon',
    code_postal: '75013',
    ville: 'Paris 13e',
    latitude: 48.8302,
    longitude: 2.3612,
    geocoding_confidence: 'exact',
    type: 'maison',
    surface_m2: 112,
    pieces: 5,
    etage: 0,
    nb_etages: 2,
    annee_construction: 1935,
    dpe: 'D',
    statut_commercial: null,
    responsable_nom: null,
    responsable_avatar: null,
    proprietaire_nom: null,
    proprietaire_lead_ref: null,
    reference_mandat: null,
    annonces: [
      {
        id: 'ann_005_1',
        bien_id: 'bien_005',
        source: 'pap',
        url_source: 'https://pap.fr/005-1',
        prix_affiche: 495000,
        prix_m2: 4420,
        publiee_le: '2026-04-19T08:00:00Z',
        statut: 'baisse_prix',
        evolution_prix: [
          { date: '2026-03-20', prix: 525000 },
          { date: '2026-04-19', prix: 495000 },
        ],
        photos: [img('cor1'), img('cor2')],
        description: 'Maison familiale RDC + étage.',
      },
    ],
    ventes_dvf_ids: ['dvf_004'],
    estimations_count: 0,
    avis_valeur_count: 0,
    etudes_locatives_count: 0,
    opportunites_count: 0,
    dossier_ref: null,
    leads_count: 0,
    actions_count: 0,
    alertes_count: 1,
    suivi: false,
    avm: {
      prix_estime: 488000,
      fourchette_basse: 465000,
      fourchette_haute: 510000,
      loyer_estime: 2200,
      loyer_fourchette: [2050, 2350],
      score_confiance: 76,
      features_contributives: [
        { feature: 'Jardin privatif', impact: 'positif', poids: 0.09 },
        { feature: 'DPE D', impact: 'negatif', poids: -0.04 },
      ],
      comparables_utilises: ['dvf_004', 'dvf_007'],
    },
    photo_principale: img('cor1'),
    photos: [img('cor1'), img('cor2')],
    prochaine_action: null,
    flag: 'baisse_prix',
    publie_il_y_a: '5h',
    signaux: ['baisse_prix'],
    derniere_maj: '2026-04-19T08:00:00Z',
    evenements: [
      { id: 'e1', bien_id: 'bien_005', type: 'changement_prix', date: '2026-04-19T08:00:00Z', user: null, titre: 'Baisse de prix 525k → 495k' },
    ],
    created_at: '2026-03-20T08:00:00Z',
    updated_at: '2026-04-19T08:00:00Z',
  },
  {
    id: 'bien_006',
    source_principale: 'annonce',
    adresse: '9 Rue de la Roquette',
    code_postal: '75011',
    ville: 'Paris 11e',
    latitude: 48.8567,
    longitude: 2.3722,
    geocoding_confidence: 'exact',
    type: 'appartement',
    surface_m2: 120,
    pieces: 3,
    etage: 4,
    nb_etages: 6,
    annee_construction: 1900,
    dpe: 'C',
    statut_commercial: null,
    responsable_nom: null,
    responsable_avatar: null,
    proprietaire_nom: null,
    proprietaire_lead_ref: null,
    reference_mandat: null,
    annonces: [
      {
        id: 'ann_006_1',
        bien_id: 'bien_006',
        source: 'seloger',
        url_source: 'https://seloger.com/006-1',
        prix_affiche: 850000,
        prix_m2: 7083,
        publiee_le: '2026-04-19T10:00:00Z',
        statut: 'remise_en_ligne',
        evolution_prix: [
          { date: '2026-02-01', prix: 895000 },
          { date: '2026-03-10', prix: 865000 },
          { date: '2026-04-19', prix: 850000 },
        ],
        photos: [img('roq1'), img('roq2')],
        description: 'T3 haussmannien refait à neuf.',
      },
      {
        id: 'ann_006_2',
        bien_id: 'bien_006',
        source: 'pap',
        url_source: 'https://pap.fr/006-2',
        prix_affiche: 845000,
        prix_m2: 7042,
        publiee_le: '2026-04-19T10:00:00Z',
        statut: 'remise_en_ligne',
        evolution_prix: [{ date: '2026-04-19', prix: 845000 }],
        photos: [img('roq1')],
        description: 'T3 Roquette.',
      },
      {
        id: 'ann_006_3',
        bien_id: 'bien_006',
        source: 'leboncoin',
        url_source: 'https://leboncoin.fr/006-3',
        prix_affiche: 855000,
        prix_m2: 7125,
        publiee_le: '2026-04-19T10:00:00Z',
        statut: 'remise_en_ligne',
        evolution_prix: [{ date: '2026-04-19', prix: 855000 }],
        photos: [img('roq2')],
        description: 'T3 Roquette.',
      },
    ],
    ventes_dvf_ids: ['dvf_007'],
    estimations_count: 1,
    avis_valeur_count: 0,
    etudes_locatives_count: 0,
    opportunites_count: 0,
    dossier_ref: null,
    leads_count: 0,
    actions_count: 0,
    alertes_count: 0,
    suivi: true,
    avm: {
      prix_estime: 860000,
      fourchette_basse: 820000,
      fourchette_haute: 900000,
      loyer_estime: 2850,
      loyer_fourchette: [2700, 3000],
      score_confiance: 81,
      features_contributives: [
        { feature: 'Refait à neuf', impact: 'positif', poids: 0.11 },
        { feature: 'Étage sans ascenseur', impact: 'negatif', poids: -0.05 },
      ],
      comparables_utilises: ['dvf_007', 'dvf_011'],
    },
    photo_principale: img('roq1'),
    photos: [img('roq1'), img('roq2'), img('roq3')],
    prochaine_action: null,
    flag: 'remise_en_ligne',
    publie_il_y_a: '1j',
    signaux: ['nouvelle_annonce'],
    derniere_maj: '2026-04-19T10:00:00Z',
    evenements: [],
    created_at: '2026-02-01T10:00:00Z',
    updated_at: '2026-04-19T10:00:00Z',
  },
  {
    id: 'bien_007',
    source_principale: 'annonce',
    adresse: '15 Boulevard Voltaire',
    code_postal: '75011',
    ville: 'Paris 11e',
    latitude: 48.8601,
    longitude: 2.3712,
    geocoding_confidence: 'exact',
    type: 'appartement',
    surface_m2: 45,
    pieces: 2,
    etage: 2,
    nb_etages: 5,
    annee_construction: 1910,
    dpe: 'D',
    statut_commercial: null,
    responsable_nom: null,
    responsable_avatar: null,
    proprietaire_nom: null,
    proprietaire_lead_ref: null,
    reference_mandat: null,
    annonces: [
      {
        id: 'ann_007_1',
        bien_id: 'bien_007',
        source: 'logic_immo',
        url_source: 'https://logic-immo.com/007-1',
        prix_affiche: 350000,
        prix_m2: 7778,
        publiee_le: '2026-04-23T13:00:00Z',
        statut: 'active',
        evolution_prix: [{ date: '2026-04-23', prix: 350000 }],
        photos: [img('vol1')],
        description: 'T2 Voltaire.',
      },
    ],
    ventes_dvf_ids: ['dvf_006'],
    estimations_count: 0,
    avis_valeur_count: 0,
    etudes_locatives_count: 0,
    opportunites_count: 1,
    dossier_ref: null,
    leads_count: 0,
    actions_count: 0,
    alertes_count: 0,
    suivi: false,
    avm: {
      prix_estime: 345000,
      fourchette_basse: 325000,
      fourchette_haute: 365000,
      loyer_estime: 1450,
      loyer_fourchette: [1350, 1550],
      score_confiance: 78,
      features_contributives: [
        { feature: 'Métro Ledru-Rollin', impact: 'positif', poids: 0.07 },
      ],
      comparables_utilises: ['dvf_006'],
    },
    photo_principale: img('vol1'),
    photos: [img('vol1'), img('vol2')],
    prochaine_action: null,
    flag: 'opportunite',
    publie_il_y_a: '2h',
    signaux: ['hot'],
    derniere_maj: '2026-04-23T13:00:00Z',
    evenements: [],
    created_at: '2026-04-23T13:00:00Z',
    updated_at: '2026-04-23T13:00:00Z',
  },
  {
    id: 'bien_008',
    source_principale: 'annonce',
    adresse: '7 Allée Vivaldi',
    code_postal: '75012',
    ville: 'Paris 12e',
    latitude: 48.8399,
    longitude: 2.3932,
    geocoding_confidence: 'exact',
    type: 'appartement',
    surface_m2: 145,
    pieces: 4,
    etage: 6,
    nb_etages: 7,
    annee_construction: 1985,
    dpe: 'B',
    statut_commercial: null,
    responsable_nom: null,
    responsable_avatar: null,
    proprietaire_nom: null,
    proprietaire_lead_ref: null,
    reference_mandat: null,
    annonces: [
      {
        id: 'ann_008_1',
        bien_id: 'bien_008',
        source: 'bienici',
        url_source: 'https://bienici.com/008-1',
        prix_affiche: 820000,
        prix_m2: 6138,
        publiee_le: '2026-04-23T07:30:00Z',
        statut: 'active',
        evolution_prix: [{ date: '2026-04-23', prix: 820000 }],
        photos: [img('viv1'), img('viv2')],
        description: 'T4 avec terrasse.',
      },
    ],
    ventes_dvf_ids: ['dvf_010'],
    estimations_count: 0,
    avis_valeur_count: 0,
    etudes_locatives_count: 0,
    opportunites_count: 0,
    dossier_ref: null,
    leads_count: 0,
    actions_count: 0,
    alertes_count: 0,
    suivi: false,
    avm: {
      prix_estime: 835000,
      fourchette_basse: 800000,
      fourchette_haute: 870000,
      loyer_estime: 3200,
      loyer_fourchette: [3000, 3400],
      score_confiance: 84,
      features_contributives: [
        { feature: 'Terrasse', impact: 'positif', poids: 0.13 },
        { feature: 'DPE B', impact: 'positif', poids: 0.04 },
      ],
      comparables_utilises: ['dvf_010'],
    },
    photo_principale: img('viv1'),
    photos: [img('viv1'), img('viv2')],
    prochaine_action: null,
    flag: 'nouveau',
    publie_il_y_a: '3h',
    signaux: ['nouvelle_annonce'],
    derniere_maj: '2026-04-23T07:30:00Z',
    evenements: [],
    created_at: '2026-04-23T07:30:00Z',
    updated_at: '2026-04-23T07:30:00Z',
  },
  {
    id: 'bien_009',
    source_principale: 'annonce',
    adresse: '103 Rue BonGarde',
    code_postal: '75012',
    ville: 'Paris 12e',
    latitude: 48.8421,
    longitude: 2.388,
    geocoding_confidence: 'exact',
    type: 'maison',
    surface_m2: 4039,
    pieces: 7,
    etage: 0,
    nb_etages: 2,
    annee_construction: 1910,
    dpe: null,
    statut_commercial: null,
    responsable_nom: null,
    responsable_avatar: null,
    proprietaire_nom: null,
    proprietaire_lead_ref: null,
    reference_mandat: null,
    annonces: [
      {
        id: 'ann_009_1',
        bien_id: 'bien_009',
        source: 'seloger',
        url_source: 'https://seloger.com/009-1',
        prix_affiche: 1000000,
        prix_m2: 248,
        publiee_le: '2026-04-22T18:00:00Z',
        statut: 'baisse_prix',
        evolution_prix: [
          { date: '2026-03-15', prix: 1100000 },
          { date: '2026-04-22', prix: 1000000 },
        ],
        photos: [img('bg1')],
        description: 'Maison familiale avec terrain.',
      },
    ],
    ventes_dvf_ids: [],
    estimations_count: 0,
    avis_valeur_count: 0,
    etudes_locatives_count: 0,
    opportunites_count: 0,
    dossier_ref: null,
    leads_count: 0,
    actions_count: 0,
    alertes_count: 0,
    suivi: false,
    avm: null,
    photo_principale: img('bg1'),
    photos: [img('bg1')],
    prochaine_action: null,
    flag: 'baisse_prix',
    publie_il_y_a: '6h',
    signaux: ['baisse_prix'],
    derniere_maj: '2026-04-22T18:00:00Z',
    evenements: [],
    created_at: '2026-03-15T18:00:00Z',
    updated_at: '2026-04-22T18:00:00Z',
  },
  {
    id: 'bien_010',
    source_principale: 'portefeuille',
    adresse: '78 Avenue Daumesnil',
    code_postal: '75012',
    ville: 'Paris 12e',
    latitude: 48.8422,
    longitude: 2.3822,
    geocoding_confidence: 'exact',
    type: 'appartement',
    surface_m2: 85,
    pieces: 4,
    etage: 3,
    nb_etages: 5,
    annee_construction: 1930,
    dpe: 'D',
    statut_commercial: 'estimation_en_cours',
    responsable_nom: 'Camille Bernard',
    responsable_avatar: 'https://i.pravatar.cc/80?u=camille',
    proprietaire_nom: 'Mme Petit',
    proprietaire_lead_ref: 'Lead #1189',
    reference_mandat: null,
    annonces: [],
    ventes_dvf_ids: ['dvf_005'],
    estimations_count: 1,
    avis_valeur_count: 0,
    etudes_locatives_count: 0,
    opportunites_count: 0,
    dossier_ref: null,
    leads_count: 1,
    actions_count: 3,
    alertes_count: 0,
    suivi: false,
    avm: {
      prix_estime: 615000,
      fourchette_basse: 590000,
      fourchette_haute: 640000,
      loyer_estime: 2050,
      loyer_fourchette: [1950, 2150],
      score_confiance: 80,
      features_contributives: [
        { feature: 'Gare de Lyon', impact: 'positif', poids: 0.06 },
      ],
      comparables_utilises: ['dvf_005'],
    },
    photo_principale: img('dau1'),
    photos: [img('dau1'), img('dau2')],
    prochaine_action: { libelle: 'Estimation', date: '2026-05-30' },
    flag: null,
    publie_il_y_a: null,
    signaux: ['hot', 'echeance', 'nouvelle_annonce'],
    derniere_maj: '2026-04-19T10:05:00Z',
    evenements: [],
    created_at: '2026-03-15T08:00:00Z',
    updated_at: '2026-04-19T10:05:00Z',
  },
  {
    id: 'bien_011',
    source_principale: 'portefeuille',
    adresse: '15 Boulevard Voltaire',
    code_postal: '75011',
    ville: 'Paris 11e',
    latitude: 48.8601,
    longitude: 2.3712,
    geocoding_confidence: 'exact',
    type: 'appartement',
    surface_m2: 45,
    pieces: 2,
    etage: 2,
    nb_etages: 5,
    annee_construction: 1910,
    dpe: 'D',
    statut_commercial: 'prospection',
    responsable_nom: 'Lucas Morel',
    responsable_avatar: 'https://i.pravatar.cc/80?u=lucas',
    proprietaire_nom: 'M. Durand',
    proprietaire_lead_ref: 'Lead #1256',
    reference_mandat: null,
    annonces: [],
    ventes_dvf_ids: ['dvf_006'],
    estimations_count: 0,
    avis_valeur_count: 0,
    etudes_locatives_count: 0,
    opportunites_count: 0,
    dossier_ref: null,
    leads_count: 1,
    actions_count: 1,
    alertes_count: 0,
    suivi: false,
    avm: {
      prix_estime: 345000,
      fourchette_basse: 325000,
      fourchette_haute: 365000,
      loyer_estime: 1450,
      loyer_fourchette: [1350, 1550],
      score_confiance: 78,
      features_contributives: [
        { feature: 'Métro Ledru-Rollin', impact: 'positif', poids: 0.07 },
      ],
      comparables_utilises: ['dvf_006'],
    },
    photo_principale: img('vol2'),
    photos: [img('vol2')],
    prochaine_action: { libelle: 'Email', date: '2026-05-31' },
    flag: null,
    publie_il_y_a: null,
    signaux: [],
    derniere_maj: '2026-04-19T17:35:00Z',
    evenements: [],
    created_at: '2026-03-20T10:00:00Z',
    updated_at: '2026-04-19T17:35:00Z',
  },
  {
    id: 'bien_012',
    source_principale: 'portefeuille',
    adresse: '9 Rue de la Roquette',
    code_postal: '75011',
    ville: 'Paris 11e',
    latitude: 48.8567,
    longitude: 2.3722,
    geocoding_confidence: 'exact',
    type: 'local',
    surface_m2: 120,
    pieces: null,
    etage: 0,
    nb_etages: 1,
    annee_construction: 1950,
    dpe: null,
    statut_commercial: 'sous_compromis',
    responsable_nom: 'Thomas Martin',
    responsable_avatar: 'https://i.pravatar.cc/80?u=thomas',
    proprietaire_nom: 'SARL Alpha',
    proprietaire_lead_ref: 'Lead #1133',
    reference_mandat: 'MDT-2024-00099',
    annonces: [],
    ventes_dvf_ids: ['dvf_007'],
    estimations_count: 0,
    avis_valeur_count: 0,
    etudes_locatives_count: 0,
    opportunites_count: 0,
    dossier_ref: 'DOS-2024-0055',
    leads_count: 1,
    actions_count: 2,
    alertes_count: 0,
    suivi: false,
    avm: null,
    photo_principale: img('roq3'),
    photos: [img('roq3')],
    prochaine_action: { libelle: 'Signature compromis', date: '2026-06-04' },
    flag: null,
    publie_il_y_a: null,
    signaux: ['hot', 'echeance'],
    derniere_maj: '2026-04-20T11:02:00Z',
    evenements: [],
    created_at: '2026-02-14T10:00:00Z',
    updated_at: '2026-04-20T11:02:00Z',
  },
  {
    id: 'bien_013',
    source_principale: 'portefeuille',
    adresse: '2 Place des Vosges',
    code_postal: '75004',
    ville: 'Paris 4e',
    latitude: 48.8555,
    longitude: 2.3657,
    geocoding_confidence: 'exact',
    type: 'appartement',
    surface_m2: 95,
    pieces: 4,
    etage: 2,
    nb_etages: 4,
    annee_construction: 1620,
    dpe: 'E',
    statut_commercial: 'mandat_exclusif',
    responsable_nom: 'Camille Bernard',
    responsable_avatar: 'https://i.pravatar.cc/80?u=camille',
    proprietaire_nom: 'Mme Girard',
    proprietaire_lead_ref: 'Lead #1077',
    reference_mandat: 'MDT-2024-00077',
    annonces: [],
    ventes_dvf_ids: ['dvf_008'],
    estimations_count: 0,
    avis_valeur_count: 1,
    etudes_locatives_count: 0,
    opportunites_count: 0,
    dossier_ref: null,
    leads_count: 1,
    actions_count: 4,
    alertes_count: 0,
    suivi: false,
    avm: {
      prix_estime: 1480000,
      fourchette_basse: 1420000,
      fourchette_haute: 1540000,
      loyer_estime: 4200,
      loyer_fourchette: [4000, 4400],
      score_confiance: 79,
      features_contributives: [
        { feature: 'Place des Vosges', impact: 'positif', poids: 0.18 },
        { feature: 'DPE E', impact: 'negatif', poids: -0.07 },
      ],
      comparables_utilises: ['dvf_008'],
    },
    photo_principale: img('vos1'),
    photos: [img('vos1'), img('vos2')],
    prochaine_action: { libelle: 'Photos pro', date: '2026-05-27' },
    flag: null,
    publie_il_y_a: null,
    signaux: ['hot', 'echeance', 'nouvelle_annonce'],
    derniere_maj: '2026-04-19T15:44:00Z',
    evenements: [],
    created_at: '2026-02-02T10:00:00Z',
    updated_at: '2026-04-19T15:44:00Z',
  },
  {
    id: 'bien_014',
    source_principale: 'portefeuille',
    adresse: '45 Rue de Charonne',
    code_postal: '75011',
    ville: 'Paris 11e',
    latitude: 48.8544,
    longitude: 2.3833,
    geocoding_confidence: 'exact',
    type: 'appartement',
    surface_m2: 70,
    pieces: 3,
    etage: 1,
    nb_etages: 5,
    annee_construction: 1900,
    dpe: 'C',
    statut_commercial: 'prospection',
    responsable_nom: 'Lucas Morel',
    responsable_avatar: 'https://i.pravatar.cc/80?u=lucas',
    proprietaire_nom: 'M. Roussel',
    proprietaire_lead_ref: 'Lead #1260',
    reference_mandat: null,
    annonces: [],
    ventes_dvf_ids: ['dvf_009'],
    estimations_count: 0,
    avis_valeur_count: 0,
    etudes_locatives_count: 0,
    opportunites_count: 0,
    dossier_ref: null,
    leads_count: 1,
    actions_count: 1,
    alertes_count: 0,
    suivi: false,
    avm: {
      prix_estime: 545000,
      fourchette_basse: 520000,
      fourchette_haute: 570000,
      loyer_estime: 1950,
      loyer_fourchette: [1850, 2050],
      score_confiance: 82,
      features_contributives: [
        { feature: 'Proximité bastille', impact: 'positif', poids: 0.07 },
      ],
      comparables_utilises: ['dvf_009'],
    },
    photo_principale: img('cha1'),
    photos: [img('cha1')],
    prochaine_action: { libelle: 'Appel', date: '2026-04-28' },
    flag: null,
    publie_il_y_a: null,
    signaux: [],
    derniere_maj: '2026-04-19T09:21:00Z',
    evenements: [],
    created_at: '2026-03-18T10:00:00Z',
    updated_at: '2026-04-19T09:21:00Z',
  },
  {
    id: 'bien_015',
    source_principale: 'portefeuille',
    adresse: '7 Allée Vivaldi',
    code_postal: '75012',
    ville: 'Paris 12e',
    latitude: 48.8399,
    longitude: 2.3932,
    geocoding_confidence: 'exact',
    type: 'maison',
    surface_m2: 145,
    pieces: 6,
    etage: 0,
    nb_etages: 2,
    annee_construction: 1985,
    dpe: 'B',
    statut_commercial: 'estimation_en_cours',
    responsable_nom: 'Thomas Martin',
    responsable_avatar: 'https://i.pravatar.cc/80?u=thomas',
    proprietaire_nom: 'M. & Mme Bernard',
    proprietaire_lead_ref: 'Lead #1211',
    reference_mandat: null,
    annonces: [],
    ventes_dvf_ids: ['dvf_010'],
    estimations_count: 1,
    avis_valeur_count: 0,
    etudes_locatives_count: 0,
    opportunites_count: 0,
    dossier_ref: null,
    leads_count: 1,
    actions_count: 2,
    alertes_count: 0,
    suivi: false,
    avm: {
      prix_estime: 895000,
      fourchette_basse: 860000,
      fourchette_haute: 935000,
      loyer_estime: 3400,
      loyer_fourchette: [3200, 3600],
      score_confiance: 83,
      features_contributives: [
        { feature: 'Terrasse', impact: 'positif', poids: 0.11 },
      ],
      comparables_utilises: ['dvf_010'],
    },
    photo_principale: img('viv3'),
    photos: [img('viv3')],
    prochaine_action: { libelle: 'Estimation', date: '2026-06-01' },
    flag: null,
    publie_il_y_a: null,
    signaux: ['hot', 'echeance'],
    derniere_maj: '2026-04-18T13:07:00Z',
    evenements: [],
    created_at: '2026-03-05T10:00:00Z',
    updated_at: '2026-04-18T13:07:00Z',
  },
  {
    id: 'bien_016',
    source_principale: 'annonce',
    adresse: '34 Rue Oberkampf',
    code_postal: '75011',
    ville: 'Paris 11e',
    latitude: 48.8633,
    longitude: 2.3705,
    geocoding_confidence: 'exact',
    type: 'appartement',
    surface_m2: 66,
    pieces: 3,
    etage: 4,
    nb_etages: 6,
    annee_construction: 1900,
    dpe: 'D',
    statut_commercial: null,
    responsable_nom: null,
    responsable_avatar: null,
    proprietaire_nom: null,
    proprietaire_lead_ref: null,
    reference_mandat: null,
    annonces: [
      {
        id: 'ann_016_1',
        bien_id: 'bien_016',
        source: 'leboncoin',
        url_source: 'https://leboncoin.fr/016-1',
        prix_affiche: 525000,
        prix_m2: 7955,
        publiee_le: '2026-04-22T11:00:00Z',
        statut: 'active',
        evolution_prix: [{ date: '2026-04-22', prix: 525000 }],
        photos: [img('obe1')],
        description: 'T3 Oberkampf.',
      },
    ],
    ventes_dvf_ids: ['dvf_016'],
    estimations_count: 0,
    avis_valeur_count: 0,
    etudes_locatives_count: 0,
    opportunites_count: 0,
    dossier_ref: null,
    leads_count: 0,
    actions_count: 0,
    alertes_count: 0,
    suivi: false,
    avm: {
      prix_estime: 530000,
      fourchette_basse: 505000,
      fourchette_haute: 555000,
      loyer_estime: 1900,
      loyer_fourchette: [1800, 2000],
      score_confiance: 79,
      features_contributives: [
        { feature: 'Quartier jeune', impact: 'positif', poids: 0.08 },
      ],
      comparables_utilises: ['dvf_016'],
    },
    photo_principale: img('obe1'),
    photos: [img('obe1')],
    prochaine_action: null,
    flag: null,
    publie_il_y_a: '1j',
    signaux: [],
    derniere_maj: '2026-04-22T11:00:00Z',
    evenements: [],
    created_at: '2026-04-22T11:00:00Z',
    updated_at: '2026-04-22T11:00:00Z',
  },
  {
    id: 'bien_017',
    source_principale: 'annonce',
    adresse: '98 Rue La Fayette',
    code_postal: '75010',
    ville: 'Paris 10e',
    latitude: 48.8772,
    longitude: 2.3533,
    geocoding_confidence: 'exact',
    type: 'appartement',
    surface_m2: 42,
    pieces: 2,
    etage: 3,
    nb_etages: 6,
    annee_construction: 1890,
    dpe: 'E',
    statut_commercial: null,
    responsable_nom: null,
    responsable_avatar: null,
    proprietaire_nom: null,
    proprietaire_lead_ref: null,
    reference_mandat: null,
    annonces: [
      {
        id: 'ann_017_1',
        bien_id: 'bien_017',
        source: 'seloger',
        url_source: 'https://seloger.com/017-1',
        prix_affiche: 365000,
        prix_m2: 8690,
        publiee_le: '2026-04-20T09:00:00Z',
        statut: 'active',
        evolution_prix: [{ date: '2026-04-20', prix: 365000 }],
        photos: [img('laf1')],
        description: 'T2 La Fayette.',
      },
    ],
    ventes_dvf_ids: ['dvf_017'],
    estimations_count: 0,
    avis_valeur_count: 0,
    etudes_locatives_count: 0,
    opportunites_count: 0,
    dossier_ref: null,
    leads_count: 0,
    actions_count: 0,
    alertes_count: 0,
    suivi: false,
    avm: {
      prix_estime: 360000,
      fourchette_basse: 340000,
      fourchette_haute: 380000,
      loyer_estime: 1250,
      loyer_fourchette: [1180, 1320],
      score_confiance: 76,
      features_contributives: [
        { feature: 'Gare du Nord', impact: 'positif', poids: 0.06 },
      ],
      comparables_utilises: ['dvf_017'],
    },
    photo_principale: img('laf1'),
    photos: [img('laf1')],
    prochaine_action: null,
    flag: null,
    publie_il_y_a: '3j',
    signaux: [],
    derniere_maj: '2026-04-20T09:00:00Z',
    evenements: [],
    created_at: '2026-04-20T09:00:00Z',
    updated_at: '2026-04-20T09:00:00Z',
  },
  {
    id: 'bien_018',
    source_principale: 'annonce',
    adresse: '4 Rue Lepic',
    code_postal: '75018',
    ville: 'Paris 18e',
    latitude: 48.8858,
    longitude: 2.3374,
    geocoding_confidence: 'exact',
    type: 'appartement',
    surface_m2: 55,
    pieces: 3,
    etage: 4,
    nb_etages: 6,
    annee_construction: 1905,
    dpe: 'D',
    statut_commercial: null,
    responsable_nom: null,
    responsable_avatar: null,
    proprietaire_nom: null,
    proprietaire_lead_ref: null,
    reference_mandat: null,
    annonces: [
      {
        id: 'ann_018_1',
        bien_id: 'bien_018',
        source: 'pap',
        url_source: 'https://pap.fr/018-1',
        prix_affiche: 445000,
        prix_m2: 8091,
        publiee_le: '2026-04-18T14:00:00Z',
        statut: 'active',
        evolution_prix: [{ date: '2026-04-18', prix: 445000 }],
        photos: [img('lep1'), img('lep2')],
        description: 'T3 Montmartre.',
      },
      {
        id: 'ann_018_2',
        bien_id: 'bien_018',
        source: 'bienici',
        url_source: 'https://bienici.com/018-2',
        prix_affiche: 450000,
        prix_m2: 8182,
        publiee_le: '2026-04-18T14:00:00Z',
        statut: 'active',
        evolution_prix: [{ date: '2026-04-18', prix: 450000 }],
        photos: [img('lep1')],
        description: 'T3 Montmartre.',
      },
    ],
    ventes_dvf_ids: ['dvf_015'],
    estimations_count: 0,
    avis_valeur_count: 0,
    etudes_locatives_count: 0,
    opportunites_count: 0,
    dossier_ref: null,
    leads_count: 0,
    actions_count: 0,
    alertes_count: 0,
    suivi: false,
    avm: {
      prix_estime: 440000,
      fourchette_basse: 420000,
      fourchette_haute: 465000,
      loyer_estime: 1650,
      loyer_fourchette: [1550, 1750],
      score_confiance: 81,
      features_contributives: [
        { feature: 'Montmartre', impact: 'positif', poids: 0.1 },
      ],
      comparables_utilises: ['dvf_015'],
    },
    photo_principale: img('lep1'),
    photos: [img('lep1'), img('lep2')],
    prochaine_action: null,
    flag: null,
    publie_il_y_a: '5j',
    signaux: [],
    derniere_maj: '2026-04-18T14:00:00Z',
    evenements: [],
    created_at: '2026-04-18T14:00:00Z',
    updated_at: '2026-04-18T14:00:00Z',
  },
];

export const PORTEFEUILLE_KPIS = {
  mandats_actifs: { value: 128, delta: 12 },
  nouveaux_mandats: { value: 18, delta: 20 },
  estimations_realisees: { value: 56, delta: 8 },
  valeur_mandats_actifs: { value: 28_400_000, delta: 9 },
};

export const ANNONCES_KPIS = {
  annonces_trouvees: 1842,
  nouveaux_biens: 47,
  baisses_prix: 23,
  biens_expires: 156,
};
