// Mocks équipe — données pré-calculées pour démonstration (mode maquette statique)

import type {
  AdoptionCollaboratorRow,
  AdoptionMetric,
  Absence,
  AgendaEvent,
  AgendaOverdueAction,
  BusinessCollaboratorRow,
  CaMonthlyPoint,
  CoachingInsight,
  Collaborateur,
  DeliverableQuality,
  DeliverableQualityAggregate,
  FunnelStage,
  Hypotheses,
  MandatsStatusSlice,
  MarcheZone,
  PortfolioItem,
  RdvBrief,
  RebalancingSuggestion,
  SourceConversionRow,
  TeamActivityItem,
  TeamObjective,
  WatchItem,
  WorkloadSnapshot,
} from '../types';

// ── Zones (agence) ────────────────────────────────────────────────────
export const ZONES = [
  { zone_id: 'z_p15', slug: 'paris-15', label: 'Paris 15e' },
  { zone_id: 'z_bgn', slug: 'boulogne', label: 'Boulogne' },
  { zone_id: 'z_issy', slug: 'issy', label: 'Issy-les-Moulineaux' },
  { zone_id: 'z_vanv', slug: 'vanves', label: 'Vanves' },
];

const ORG = 'org_propsight_demo';

// ── Collaborateurs (12) ───────────────────────────────────────────────
export const COLLABORATEURS: Collaborateur[] = [
  {
    user_id: 'u_sophie',
    organization_id: ORG,
    display_name: 'Sophie Martin',
    initials: 'SM',
    avatar_color: '#8B5CF6',
    email: 'sophie.martin@propsight.fr',
    role: 'OWNER',
    status: 'active',
    zones: [ZONES[0]],
    specialites: ['vente', 'estimation'],
    capacity_weekly_hours: 35,
    last_seen_at: '2026-04-24T08:12:00Z',
    created_at: '2024-02-01T00:00:00Z',
    updated_at: '2026-04-24T08:12:00Z',
    leads_actifs: 28,
    actions_retard: 6,
    actions_retard_haute: 2,
    rdv_semaine: 9,
    mandats: 9,
    mandats_exclusifs: 4,
    ca_pipe: 92000,
    ca_realise: 62400,
    estimations_30j: 18,
    avis_envoyes_30j: 11,
    etudes_locatives_30j: 3,
    rapports_ouverts: 7,
    signaux_traites_30j: 24,
    signaux_non_traites: 4,
    rapports_a_relancer: 4,
    workload_score: 87,
    workload_status: 'surcharge',
    trend_30j: [2, 3, 2, 4, 5, 4, 6, 5, 7, 8, 6, 9],
  },
  {
    user_id: 'u_marc',
    organization_id: ORG,
    display_name: 'Marc Lemoine',
    initials: 'ML',
    avatar_color: '#0EA5E9',
    email: 'marc.lemoine@propsight.fr',
    role: 'ADMIN',
    status: 'active',
    zones: [ZONES[1]],
    specialites: ['vente'],
    capacity_weekly_hours: 35,
    last_seen_at: '2026-04-24T09:45:00Z',
    created_at: '2024-03-10T00:00:00Z',
    updated_at: '2026-04-24T09:45:00Z',
    leads_actifs: 19,
    actions_retard: 4,
    actions_retard_haute: 1,
    rdv_semaine: 5,
    mandats: 4,
    mandats_exclusifs: 1,
    ca_pipe: 42500,
    ca_realise: 18200,
    estimations_30j: 12,
    avis_envoyes_30j: 2,
    etudes_locatives_30j: 1,
    rapports_ouverts: 2,
    signaux_traites_30j: 18,
    signaux_non_traites: 2,
    rapports_a_relancer: 1,
    workload_score: 74,
    workload_status: 'charge',
    trend_30j: [1, 2, 2, 3, 3, 2, 4, 3, 4, 3, 4, 4],
  },
  {
    user_id: 'u_camille',
    organization_id: ORG,
    display_name: 'Camille Durand',
    initials: 'CD',
    avatar_color: '#EC4899',
    email: 'camille.durand@propsight.fr',
    role: 'AGENT',
    status: 'active',
    zones: [ZONES[0], ZONES[2]],
    specialites: ['vente', 'investissement'],
    capacity_weekly_hours: 35,
    last_seen_at: '2026-04-24T10:02:00Z',
    created_at: '2024-04-15T00:00:00Z',
    updated_at: '2026-04-24T10:02:00Z',
    leads_actifs: 22,
    actions_retard: 3,
    actions_retard_haute: 1,
    rdv_semaine: 7,
    mandats: 8,
    mandats_exclusifs: 5,
    ca_pipe: 102400,
    ca_realise: 78900,
    estimations_30j: 18,
    avis_envoyes_30j: 13,
    etudes_locatives_30j: 4,
    rapports_ouverts: 9,
    signaux_traites_30j: 32,
    signaux_non_traites: 5,
    rapports_a_relancer: 1,
    workload_score: 58,
    workload_status: 'normal',
    trend_30j: [3, 4, 5, 5, 6, 7, 6, 8, 7, 9, 8, 10],
  },
  {
    user_id: 'u_thomas',
    organization_id: ORG,
    display_name: 'Thomas Morel',
    initials: 'TM',
    avatar_color: '#10B981',
    email: 'thomas.morel@propsight.fr',
    role: 'AGENT',
    status: 'active',
    zones: [ZONES[3]],
    specialites: ['location', 'gestion_locative'],
    capacity_weekly_hours: 35,
    last_seen_at: '2026-04-24T07:58:00Z',
    created_at: '2024-05-20T00:00:00Z',
    updated_at: '2026-04-24T07:58:00Z',
    leads_actifs: 12,
    actions_retard: 1,
    actions_retard_haute: 0,
    rdv_semaine: 3,
    mandats: 2,
    mandats_exclusifs: 2,
    ca_pipe: 28000,
    ca_realise: 14500,
    estimations_30j: 8,
    avis_envoyes_30j: 4,
    etudes_locatives_30j: 6,
    rapports_ouverts: 3,
    signaux_traites_30j: 14,
    signaux_non_traites: 1,
    rapports_a_relancer: 0,
    workload_score: 32,
    workload_status: 'disponible',
    trend_30j: [1, 1, 2, 1, 2, 2, 2, 3, 2, 3, 3, 3],
  },
  {
    user_id: 'u_nicolas',
    organization_id: ORG,
    display_name: 'Nicolas Petit',
    initials: 'NP',
    avatar_color: '#F59E0B',
    email: 'nicolas.petit@propsight.fr',
    role: 'AGENT',
    status: 'active',
    zones: [ZONES[2]],
    specialites: ['investissement'],
    capacity_weekly_hours: 35,
    last_seen_at: '2026-04-23T17:30:00Z',
    created_at: '2024-06-12T00:00:00Z',
    updated_at: '2026-04-23T17:30:00Z',
    leads_actifs: 15,
    actions_retard: 2,
    actions_retard_haute: 1,
    rdv_semaine: 4,
    mandats: 1,
    mandats_exclusifs: 0,
    ca_pipe: 32000,
    ca_realise: 9200,
    estimations_30j: 6,
    avis_envoyes_30j: 3,
    etudes_locatives_30j: 2,
    rapports_ouverts: 4,
    signaux_traites_30j: 21,
    signaux_non_traites: 8,
    rapports_a_relancer: 1,
    workload_score: 54,
    workload_status: 'normal',
    trend_30j: [1, 2, 2, 2, 3, 3, 3, 4, 3, 4, 4, 5],
  },
  {
    user_id: 'u_laura',
    organization_id: ORG,
    display_name: 'Laura Simon',
    initials: 'LS',
    avatar_color: '#6366F1',
    email: 'laura.simon@propsight.fr',
    role: 'AGENT',
    status: 'active',
    zones: [ZONES[1]],
    specialites: ['vente', 'location'],
    capacity_weekly_hours: 35,
    last_seen_at: '2026-04-24T08:40:00Z',
    created_at: '2024-07-01T00:00:00Z',
    updated_at: '2026-04-24T08:40:00Z',
    leads_actifs: 10,
    actions_retard: 1,
    actions_retard_haute: 0,
    rdv_semaine: 2,
    mandats: 1,
    mandats_exclusifs: 0,
    ca_pipe: 18500,
    ca_realise: 4800,
    estimations_30j: 5,
    avis_envoyes_30j: 2,
    etudes_locatives_30j: 1,
    rapports_ouverts: 1,
    signaux_traites_30j: 8,
    signaux_non_traites: 2,
    rapports_a_relancer: 0,
    workload_score: 28,
    workload_status: 'disponible',
    trend_30j: [0, 1, 1, 1, 1, 2, 1, 2, 2, 2, 2, 3],
  },
  {
    user_id: 'u_julien',
    organization_id: ORG,
    display_name: 'Julien Moreau',
    initials: 'JM',
    avatar_color: '#14B8A6',
    email: 'julien.moreau@propsight.fr',
    role: 'AGENT',
    status: 'active',
    zones: [ZONES[0]],
    specialites: ['vente', 'estimation'],
    capacity_weekly_hours: 35,
    last_seen_at: '2026-04-24T09:10:00Z',
    created_at: '2024-09-05T00:00:00Z',
    updated_at: '2026-04-24T09:10:00Z',
    leads_actifs: 8,
    actions_retard: 0,
    actions_retard_haute: 0,
    rdv_semaine: 2,
    mandats: 1,
    mandats_exclusifs: 1,
    ca_pipe: 15400,
    ca_realise: 3600,
    estimations_30j: 4,
    avis_envoyes_30j: 2,
    etudes_locatives_30j: 0,
    rapports_ouverts: 2,
    signaux_traites_30j: 11,
    signaux_non_traites: 1,
    rapports_a_relancer: 0,
    workload_score: 22,
    workload_status: 'disponible',
    trend_30j: [0, 1, 0, 1, 1, 1, 2, 1, 2, 2, 2, 2],
  },
  {
    user_id: 'u_chloe',
    organization_id: ORG,
    display_name: 'Chloé Bernard',
    initials: 'CB',
    avatar_color: '#EF4444',
    email: 'chloe.bernard@propsight.fr',
    role: 'AGENT',
    status: 'active',
    zones: [ZONES[2], ZONES[3]],
    specialites: ['investissement', 'estimation'],
    capacity_weekly_hours: 35,
    last_seen_at: '2026-04-24T09:22:00Z',
    created_at: '2024-10-11T00:00:00Z',
    updated_at: '2026-04-24T09:22:00Z',
    leads_actifs: 14,
    actions_retard: 1,
    actions_retard_haute: 0,
    rdv_semaine: 2,
    mandats: 1,
    mandats_exclusifs: 1,
    ca_pipe: 23000,
    ca_realise: 5200,
    estimations_30j: 7,
    avis_envoyes_30j: 4,
    etudes_locatives_30j: 2,
    rapports_ouverts: 3,
    signaux_traites_30j: 18,
    signaux_non_traites: 3,
    rapports_a_relancer: 1,
    workload_score: 46,
    workload_status: 'normal',
    trend_30j: [1, 1, 1, 2, 2, 3, 2, 3, 3, 3, 4, 4],
  },
  {
    user_id: 'u_eloise',
    organization_id: ORG,
    display_name: 'Éloïse Dubois',
    initials: 'ED',
    avatar_color: '#A855F7',
    email: 'eloise.dubois@propsight.fr',
    role: 'AGENT',
    status: 'active',
    zones: [ZONES[1]],
    specialites: ['vente'],
    capacity_weekly_hours: 35,
    last_seen_at: '2026-04-22T11:15:00Z',
    created_at: '2024-11-02T00:00:00Z',
    updated_at: '2026-04-22T11:15:00Z',
    leads_actifs: 7,
    actions_retard: 2,
    actions_retard_haute: 1,
    rdv_semaine: 1,
    mandats: 0,
    mandats_exclusifs: 0,
    ca_pipe: 8400,
    ca_realise: 2100,
    estimations_30j: 3,
    avis_envoyes_30j: 0,
    etudes_locatives_30j: 0,
    rapports_ouverts: 1,
    signaux_traites_30j: 5,
    signaux_non_traites: 4,
    rapports_a_relancer: 0,
    workload_score: 34,
    workload_status: 'disponible',
    trend_30j: [1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 2],
  },
  {
    user_id: 'u_paul',
    organization_id: ORG,
    display_name: 'Paul Richard',
    initials: 'PR',
    avatar_color: '#0891B2',
    email: 'paul.richard@propsight.fr',
    role: 'AGENT',
    status: 'active',
    zones: [ZONES[0]],
    specialites: ['location'],
    capacity_weekly_hours: 28,
    last_seen_at: '2026-04-24T10:00:00Z',
    created_at: '2024-12-14T00:00:00Z',
    updated_at: '2026-04-24T10:00:00Z',
    leads_actifs: 6,
    actions_retard: 0,
    actions_retard_haute: 0,
    rdv_semaine: 1,
    mandats: 0,
    mandats_exclusifs: 0,
    ca_pipe: 5800,
    ca_realise: 1800,
    estimations_30j: 2,
    avis_envoyes_30j: 1,
    etudes_locatives_30j: 1,
    rapports_ouverts: 1,
    signaux_traites_30j: 4,
    signaux_non_traites: 1,
    rapports_a_relancer: 0,
    workload_score: 24,
    workload_status: 'disponible',
    trend_30j: [0, 1, 1, 0, 1, 1, 1, 2, 1, 1, 2, 2],
  },
  {
    user_id: 'u_ines',
    organization_id: ORG,
    display_name: 'Inès Girard',
    initials: 'IG',
    avatar_color: '#F97316',
    email: 'ines.girard@propsight.fr',
    role: 'AGENT',
    status: 'active',
    zones: [ZONES[3]],
    specialites: ['estimation'],
    capacity_weekly_hours: 35,
    last_seen_at: '2026-04-24T09:30:00Z',
    created_at: '2025-01-08T00:00:00Z',
    updated_at: '2026-04-24T09:30:00Z',
    leads_actifs: 5,
    actions_retard: 1,
    actions_retard_haute: 0,
    rdv_semaine: 1,
    mandats: 0,
    mandats_exclusifs: 0,
    ca_pipe: 4200,
    ca_realise: 900,
    estimations_30j: 3,
    avis_envoyes_30j: 1,
    etudes_locatives_30j: 0,
    rapports_ouverts: 0,
    signaux_traites_30j: 6,
    signaux_non_traites: 2,
    rapports_a_relancer: 0,
    workload_score: 28,
    workload_status: 'disponible',
    trend_30j: [0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1],
  },
  {
    user_id: 'u_raphael',
    organization_id: ORG,
    display_name: 'Raphaël Leroy',
    initials: 'RL',
    avatar_color: '#84CC16',
    email: 'raphael.leroy@propsight.fr',
    role: 'VIEWER',
    status: 'active',
    zones: [ZONES[0], ZONES[1]],
    specialites: ['vente'],
    capacity_weekly_hours: 20,
    last_seen_at: '2026-04-20T16:00:00Z',
    created_at: '2025-02-01T00:00:00Z',
    updated_at: '2026-04-20T16:00:00Z',
    leads_actifs: 2,
    actions_retard: 0,
    actions_retard_haute: 0,
    rdv_semaine: 0,
    mandats: 0,
    mandats_exclusifs: 0,
    ca_pipe: 0,
    ca_realise: 0,
    estimations_30j: 0,
    avis_envoyes_30j: 0,
    etudes_locatives_30j: 0,
    rapports_ouverts: 0,
    signaux_traites_30j: 0,
    signaux_non_traites: 0,
    rapports_a_relancer: 0,
    workload_score: 6,
    workload_status: 'disponible',
    trend_30j: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  },
];

// ── Agrégats équipe ───────────────────────────────────────────────────
export const EQUIPE_KPI_SUMMARY = {
  leads_actifs: 128,
  leads_actifs_delta: '+12 vs sem. dern.',
  actions_retard: 18,
  actions_retard_haute: 5,
  rdv_semaine: 34,
  rdv_visites: 9,
  rdv_estimations: 12,
  mandats: 27,
  mandats_exclusifs: 8,
  ca_pipe: 286450,
  ca_pipe_delta: '+18 %',
  leads_unassigned: 12,
  leads_unassigned_48h: 3,
};

// ── Watch items (§7.5 tab À surveiller) ───────────────────────────────
export const WATCH_ITEMS: WatchItem[] = [
  {
    id: 'w_1',
    color: 'red',
    title: '12 leads entrants non assignés',
    subtitle: 'Widget estimation · âge moyen 4 h',
    cta_label: 'Assigner depuis Kanban',
    cta_target: '/app/activite/leads?assigne=null',
    priority: 'haute',
  },
  {
    id: 'w_2',
    color: 'orange',
    title: '7 rapports ouverts sans relance',
    subtitle: '5 AdV · 2 études · plus ancien = 8 j',
    cta_label: 'Créer relances',
    cta_target: '/app/equipe/activite?preset=rapports-a-relancer',
    priority: 'moyenne',
  },
  {
    id: 'w_3',
    color: 'orange',
    title: '5 actions haute priorité en retard',
    cta_label: 'Voir actions',
    cta_target: '/app/equipe/activite?preset=en-retard',
    priority: 'moyenne',
  },
  {
    id: 'w_4',
    color: 'yellow',
    title: 'Sophie est en surcharge',
    subtitle: 'Charge 87/100 · +42 % vs moyenne équipe',
    cta_label: 'Rééquilibrer',
    cta_target: '/app/equipe/agenda?collaborateur=u_sophie',
    priority: 'moyenne',
  },
  {
    id: 'w_5',
    color: 'yellow',
    title: '14 estimations rapides non promues',
    subtitle: 'Potentiel 3 AdV',
    cta_label: 'Voir estimations',
    cta_target: '/app/estimation/rapide',
    priority: 'basse',
  },
  {
    id: 'w_6',
    color: 'yellow',
    title: '4 avis avec écart AVM > 5 %',
    subtitle: 'Justification manquante',
    cta_label: 'Compléter',
    cta_target: '/app/equipe/portefeuille?preset=ecart-avm',
    priority: 'basse',
  },
  {
    id: 'w_7',
    color: 'grey',
    title: 'Paris 15e : forte tension, faible prospection',
    subtitle: 'Part captée 1,4 % · potentiel 420 k€',
    cta_label: 'Voir zone',
    cta_target: '/app/observatoire/contexte-local?zone=paris-15',
    priority: 'basse',
  },
  {
    id: 'w_8',
    color: 'grey',
    title: '3 mandats simples sous pression',
    subtitle: 'Concurrents actifs sur les zones',
    cta_label: 'Voir veille',
    cta_target: '/app/veille/agences-concurrentes',
    priority: 'basse',
  },
];

// ── Adoption (§7.5 tab Adoption) ──────────────────────────────────────
export const ADOPTION_METRICS: AdoptionMetric[] = [
  { id: 'actifs_7j', label: 'Utilisateurs actifs 7 j', value: 12, total: 15, pct: 80, trend: 'up' },
  { id: 'estimations', label: 'Estimations créées', value: 84, delta: '+18 %', trend: 'up' },
  { id: 'avis_envoyes', label: 'Avis de valeur envoyés', value: 37, delta: '+6 %', trend: 'up' },
  { id: 'etudes', label: 'Études locatives créées', value: 18, delta: '-12 %', trend: 'down' },
  { id: 'rapports_ouverts', label: 'Rapports ouverts', value: 21, delta: '+28 %', trend: 'up' },
  { id: 'signaux', label: 'Signaux prospection traités', value: 146, delta: '+42 %', trend: 'up' },
  { id: 'biens_suivis', label: 'Biens suivis ajoutés', value: 58, delta: '+8 %', trend: 'up' },
  { id: 'alertes', label: 'Alertes actives', value: 32, delta: '=', trend: 'flat' },
];

export const ADOPTION_SCORE = 72;

// ── Coaching insights (§7.5 tab Coaching) ─────────────────────────────
export const COACHING_INSIGHTS: CoachingInsight[] = [
  {
    insight_id: 'ci_001',
    rule_id: 'conversion_bloquee_avis_valeur',
    scope: 'collaborateur',
    target_id: 'u_marc',
    target_label: 'Marc',
    type: 'conversion_bloquee_avis_valeur',
    title: 'Marc crée des estimations mais envoie peu d’avis de valeur',
    explanation: 'Estimations 30 j : 12 · AdV envoyés : 2 · ratio 17 % (moyenne équipe 44 %)',
    recommended_action: 'Coaching : préparation RDV vendeur',
    cta_label: 'Planifier coaching',
    cta_target: '/app/equipe/agenda?collaborateur=u_marc',
    priority: 'moyenne',
    triggered_at: '2026-04-24T08:30:00Z',
    metric_snapshot: { estimations_30j: 12, avis_envoyes_30j: 2, ratio: 17, team_avg_ratio: 44 },
  },
  {
    insight_id: 'ci_002',
    rule_id: 'signaux_prospection_non_traites',
    scope: 'collaborateur',
    target_id: 'u_nicolas',
    target_label: 'Nicolas',
    type: 'signaux_prospection_non_traites',
    title: 'Nicolas traite beaucoup de signaux DPE mais convertit peu en leads',
    explanation: 'Signaux traités 30 j : 21 · Leads créés : 2 · ratio 10 %',
    recommended_action: 'Coaching : script prospection DPE',
    cta_label: 'Planifier coaching',
    cta_target: '/app/equipe/agenda?collaborateur=u_nicolas',
    priority: 'moyenne',
    triggered_at: '2026-04-24T08:30:00Z',
    metric_snapshot: { signaux_30j: 21, leads_30j: 2 },
  },
  {
    insight_id: 'ci_003',
    rule_id: 'relance_manquante_rapport',
    scope: 'collaborateur',
    target_id: 'u_sophie',
    target_label: 'Sophie',
    type: 'relance_manquante_rapport',
    title: 'Sophie a 4 rapports ouverts sans relance',
    explanation: 'Plus ancien ouvert le 16/04 · Moyenne ouverture : 3 vues',
    recommended_action: 'Créer les relances aujourd’hui',
    cta_label: 'Ouvrir activité',
    cta_target: '/app/equipe/activite?collaborateur=u_sophie&preset=rapports-a-relancer',
    priority: 'haute',
    triggered_at: '2026-04-24T08:30:00Z',
    metric_snapshot: { rapports_ouverts_sans_relance: 4 },
  },
  {
    insight_id: 'ci_004',
    rule_id: 'conversion_bloquee_etude_locative',
    scope: 'equipe',
    target_label: 'Équipe location',
    type: 'conversion_bloquee_etude_locative',
    title: 'L’équipe location crée peu d’études malgré 18 leads bailleurs',
    explanation: 'Leads bailleurs 30 j : 18 · Études créées : 7 · ratio 39 %',
    recommended_action: 'Campagne bailleurs ou script prospection locative',
    cta_label: 'Lancer campagne',
    cta_target: '#',
    priority: 'basse',
    triggered_at: '2026-04-24T08:30:00Z',
  },
  {
    insight_id: 'ci_005',
    rule_id: 'zone_sous_exploitee',
    scope: 'zone',
    target_id: 'issy',
    target_label: 'Issy-les-Moulineaux',
    type: 'zone_sous_exploitee',
    title: 'Issy : forte tension, faible prospection équipe',
    explanation: 'Volume DVF 12 m : 392 · Leads équipe 30 j : 3 · Part captée : 0,5 %',
    recommended_action: 'Lancer une campagne de prospection',
    cta_label: 'Voir zone',
    cta_target: '/app/observatoire/contexte-local?zone=issy',
    priority: 'basse',
    triggered_at: '2026-04-24T08:30:00Z',
  },
];

// ── Activité commerciale (§8.5) ───────────────────────────────────────
export const TEAM_ACTIVITY: TeamActivityItem[] = [
  {
    activity_id: 'act_1',
    type: 'lead',
    title: 'Mme Bertrand',
    source_module: 'leads',
    source_label: 'Widget',
    object_type: 'lead',
    object_id: 'lead_001',
    collaborator_id: 'u_sophie',
    collaborator_label: 'Sophie Martin',
    client_label: 'Mme Bertrand',
    client_contact: 'b.bertrand@…',
    adresse: '48 rue de Rennes, 75006 Paris',
    zone_slug: 'paris-15',
    zone_label: 'Paris 6e',
    derniere_action_label: 'Appel',
    derniere_action_at: '2026-04-20T11:24:00Z',
    prochaine_action_label: 'Appeler aujourd’hui',
    prochaine_action_at: '2026-04-24T10:00:00Z',
    priority: 'haute',
    status: 'en_cours',
    age_days: 4,
    event_at: '2026-04-24T10:00:00Z',
  },
  {
    activity_id: 'act_2',
    type: 'action',
    title: 'Relance Mme Durand',
    source_module: 'leads',
    source_label: 'Interne',
    object_type: 'action',
    object_id: 'act_b1',
    collaborator_id: 'u_marc',
    collaborator_label: 'Marc Lemoine',
    client_label: 'M. Dupont',
    adresse: '12 av. Victor Hugo, 75116 Paris',
    zone_slug: 'paris-15',
    zone_label: 'Paris 16e',
    derniere_action_label: 'Email',
    derniere_action_at: '2026-04-18T09:00:00Z',
    prochaine_action_label: 'Relancer',
    prochaine_action_at: '2026-04-23T00:00:00Z',
    priority: 'moyenne',
    status: 'en_retard',
    retard_days: 3,
    event_at: '2026-04-18T09:00:00Z',
  },
  {
    activity_id: 'act_3',
    type: 'avis_valeur',
    title: 'Avis de valeur Famille Martin',
    source_module: 'estimation',
    source_label: 'Site',
    object_type: 'avis_valeur',
    object_id: 'rap_001',
    collaborator_id: 'u_chloe',
    collaborator_label: 'Chloé Bernard',
    client_label: 'Famille Martin',
    adresse: '7 allée des Tilleuls, 92100 Boulogne',
    zone_slug: 'boulogne',
    zone_label: 'Boulogne',
    derniere_action_label: 'Envoi rapport',
    derniere_action_at: '2026-04-14T10:00:00Z',
    prochaine_action_label: 'Relancer rapport',
    prochaine_action_at: '2026-04-22T00:00:00Z',
    priority: 'moyenne',
    status: 'a_relancer',
    age_days: 10,
    event_at: '2026-04-14T10:00:00Z',
  },
  {
    activity_id: 'act_4',
    type: 'signal',
    title: 'Signal DPE — M. Girard',
    source_module: 'prospection',
    source_label: 'DPE',
    object_type: 'signal',
    object_id: 'sig_001',
    collaborator_id: 'u_nicolas',
    collaborator_label: 'Nicolas Petit',
    client_label: 'M. Girard',
    adresse: '28 rue des Écoles, 75005 Paris',
    zone_slug: 'paris-15',
    zone_label: 'Paris 5e',
    derniere_action_label: 'Qualification',
    derniere_action_at: '2026-04-21T15:00:00Z',
    prochaine_action_label: 'Contacter',
    prochaine_action_at: '2026-04-25T00:00:00Z',
    priority: 'haute',
    status: 'nouveau',
    event_at: '2026-04-21T15:00:00Z',
  },
  {
    activity_id: 'act_5',
    type: 'lead',
    title: 'Rue du Commerce — L. Bernard',
    source_module: 'leads',
    source_label: 'Site',
    object_type: 'lead',
    object_id: 'lead_002',
    collaborator_id: 'u_laura',
    collaborator_label: 'Laura Simon',
    client_label: 'L. Bernard',
    adresse: '58 rue de Commerce, 75015 Paris',
    zone_slug: 'paris-15',
    zone_label: 'Paris 15e',
    derniere_action_label: 'Appel',
    derniere_action_at: '2026-04-18T10:00:00Z',
    priority: 'moyenne',
    status: 'non_assigne',
    event_at: '2026-04-18T10:00:00Z',
  },
  {
    activity_id: 'act_6',
    type: 'lead',
    title: 'Estimateur — C. Petit',
    source_module: 'leads',
    source_label: 'Widget',
    object_type: 'lead',
    object_id: 'lead_003',
    collaborator_id: 'u_julien',
    collaborator_label: 'Julien Moreau',
    client_label: 'C. Petit',
    adresse: '9 rue d’Alsace, 69002 Lyon',
    zone_slug: 'paris-15',
    zone_label: 'Lyon 2e',
    derniere_action_label: 'Formulaire',
    derniere_action_at: '2026-04-18T10:00:00Z',
    priority: 'basse',
    status: 'non_assigne',
    event_at: '2026-04-18T10:00:00Z',
  },
  {
    activity_id: 'act_7',
    type: 'action',
    title: 'Relancer vendeur',
    source_module: 'estimation',
    source_label: 'Interne',
    object_type: 'action',
    object_id: 'act_b2',
    collaborator_id: 'u_thomas',
    collaborator_label: 'Thomas Morel',
    client_label: 'M. Leroy',
    adresse: '15 rue Pasteur, 94100 Saint-Maur',
    zone_slug: 'vanves',
    zone_label: 'Saint-Maur',
    derniere_action_label: 'Note',
    derniere_action_at: '2026-04-18T10:00:00Z',
    prochaine_action_label: 'Relancer',
    prochaine_action_at: '2026-04-23T00:00:00Z',
    priority: 'moyenne',
    status: 'en_cours',
    event_at: '2026-04-18T10:00:00Z',
  },
  {
    activity_id: 'act_8',
    type: 'signal',
    title: 'Signal Prix baisse — R. Simon',
    source_module: 'prospection',
    source_label: 'Prix',
    object_type: 'signal',
    object_id: 'sig_002',
    collaborator_id: 'u_sophie',
    collaborator_label: 'Sophie Martin',
    client_label: 'R. Simon',
    adresse: '102 bd Haussmann, 75008 Paris',
    zone_slug: 'paris-15',
    zone_label: 'Paris 8e',
    derniere_action_label: 'Qualification',
    derniere_action_at: '2026-04-09T10:00:00Z',
    prochaine_action_label: 'Analyser',
    prochaine_action_at: '2026-04-25T00:00:00Z',
    priority: 'moyenne',
    status: 'en_cours',
    event_at: '2026-04-09T10:00:00Z',
  },
  {
    activity_id: 'act_9',
    type: 'action',
    title: 'Relance acquéreur',
    source_module: 'leads',
    source_label: 'Interne',
    object_type: 'action',
    object_id: 'act_b3',
    collaborator_id: 'u_chloe',
    collaborator_label: 'Chloé Bernard',
    client_label: 'P. Richard',
    adresse: '31 rue La Fayette, 75009 Paris',
    zone_slug: 'paris-15',
    zone_label: 'Paris 9e',
    derniere_action_label: 'Email',
    derniere_action_at: '2026-04-08T10:00:00Z',
    prochaine_action_label: 'Relancer',
    prochaine_action_at: '2026-04-17T00:00:00Z',
    priority: 'moyenne',
    status: 'en_retard',
    retard_days: 7,
    event_at: '2026-04-08T10:00:00Z',
  },
  {
    activity_id: 'act_10',
    type: 'lead',
    title: 'Widget estimation — M. Girard',
    source_module: 'leads',
    source_label: 'Widget',
    object_type: 'lead',
    object_id: 'lead_004',
    collaborator_id: 'u_nicolas',
    collaborator_label: 'Nicolas Petit',
    client_label: 'M. Girard',
    adresse: '11 allée des Tilleuls, 78180 Montigny',
    zone_slug: 'issy',
    zone_label: 'Montigny',
    derniere_action_label: 'Formulaire',
    derniere_action_at: '2026-04-07T10:00:00Z',
    priority: 'basse',
    status: 'non_assigne',
    event_at: '2026-04-07T10:00:00Z',
  },
  {
    activity_id: 'act_11',
    type: 'avis_valeur',
    title: 'Avis 16 rue du Hameau',
    source_module: 'estimation',
    source_label: 'Site',
    object_type: 'avis_valeur',
    object_id: 'rap_002',
    collaborator_id: 'u_sophie',
    collaborator_label: 'Sophie Martin',
    client_label: 'Mme Bertrand',
    adresse: '16 rue du Hameau, 75015 Paris',
    zone_slug: 'paris-15',
    zone_label: 'Paris 15e',
    derniere_action_label: 'Ouverture rapport',
    derniere_action_at: '2026-04-23T18:00:00Z',
    prochaine_action_label: 'Relancer vendeur',
    priority: 'haute',
    status: 'ouvert_sans_relance',
    event_at: '2026-04-23T18:00:00Z',
  },
  {
    activity_id: 'act_12',
    type: 'opportunite',
    title: 'Opportunité Rue du Commerce',
    source_module: 'investissement',
    source_label: 'Interne',
    object_type: 'opportunite',
    object_id: 'opp_001',
    collaborator_label: 'Non assigné',
    client_label: 'Invest Partners',
    adresse: '32 rue du Commerce, 13001 Marseille',
    zone_slug: 'issy',
    zone_label: 'Marseille 1er',
    derniere_action_label: 'Qualification',
    derniere_action_at: '2026-04-17T09:14:00Z',
    prochaine_action_label: 'Qualifier',
    priority: 'moyenne',
    status: 'nouveau',
    event_at: '2026-04-17T09:14:00Z',
  },
];

// ── Portefeuille & dossiers (§9) ──────────────────────────────────────
export const PORTFOLIO_ITEMS: PortfolioItem[] = [
  {
    id: 'p_1',
    type: 'avis_valeur',
    type_label: 'Avis de valeur',
    title: '16 rue du Hameau',
    adresse: '16 rue du Hameau, 75015 Paris',
    zone_label: 'Paris 15e',
    collaborator_id: 'u_sophie',
    collaborator_label: 'Sophie Martin',
    client_label: 'M. Durand',
    statut: 'Ouvert',
    statut_tone: 'warning',
    valeur: 450000,
    valeur_label: '450 k€',
    last_activity_at: '2026-04-20T09:32:00Z',
    last_activity_label: '09:32 Relance client',
    next_action_label: '20 mai',
    quality_score: 92,
    risk: 'ok',
    risk_label: 'Faible',
    is_complete: true,
    ecart_avm_sup_5pct_sans_justif: false,
    has_relance: true,
  },
  {
    id: 'p_2',
    type: 'etude_locative',
    type_label: 'Étude locative',
    title: 'Maison 94 m²',
    adresse: '7 allée du Hameau, 69100 Villeurbanne',
    zone_label: 'Villeurbanne',
    collaborator_id: 'u_thomas',
    collaborator_label: 'Thomas Morel',
    client_label: 'Mme Bernard',
    statut: 'En cours',
    statut_tone: 'info',
    valeur: 1450,
    valeur_label: '1 450 €/mois',
    last_activity_at: '2026-04-19T13:00:00Z',
    last_activity_label: 'Hier · Analyse marché',
    next_action_label: 'Envoyer étude',
    quality_score: 78,
    risk: 'a_relancer',
    risk_label: 'Moyen',
    is_complete: false,
    ecart_avm_sup_5pct_sans_justif: false,
    has_relance: false,
  },
  {
    id: 'p_3',
    type: 'dossier_invest',
    type_label: 'Dossier investissement',
    title: 'Projet Lyon',
    adresse: '5 quai Saint-Vincent, 69001 Lyon',
    zone_label: 'Lyon',
    collaborator_id: 'u_chloe',
    collaborator_label: 'Chloé Bernard',
    client_label: 'Invest Partners',
    statut: 'En cours',
    statut_tone: 'info',
    valeur: 5.2,
    valeur_label: '5,20 %',
    valeur_unit: 'rendement',
    last_activity_at: '2026-04-21T11:22:00Z',
    last_activity_label: 'Hier 11:22 · Business plan',
    next_action_label: 'Comité invest.',
    quality_score: 88,
    risk: 'ok',
    risk_label: 'Faible',
    is_complete: true,
    ecart_avm_sup_5pct_sans_justif: false,
    has_relance: true,
  },
  {
    id: 'p_4',
    type: 'opportunite',
    type_label: 'Opportunité',
    title: 'Rue du Commerce',
    adresse: '32 rue du Commerce, 13001 Marseille',
    zone_label: 'Marseille',
    collaborator_id: 'u_nicolas',
    collaborator_label: 'Nicolas Petit',
    client_label: 'Lead qualifié',
    statut: 'Nouveau',
    statut_tone: 'success',
    valeur: 320000,
    valeur_label: '320 k€',
    last_activity_at: '2026-04-17T09:14:00Z',
    last_activity_label: '17 mai · Source SeLoger',
    next_action_label: 'Qualif. téléph.',
    quality_score: 55,
    risk: 'a_relancer',
    risk_label: 'Élevé',
    is_complete: false,
    ecart_avm_sup_5pct_sans_justif: false,
    has_relance: false,
  },
  {
    id: 'p_5',
    type: 'mandat',
    type_label: 'Mandat exclusif',
    title: 'Villa des Pins',
    adresse: '12 av. des Pins, 33120 Arcachon',
    zone_label: 'Arcachon',
    collaborator_id: 'u_laura',
    collaborator_label: 'Laura Simon',
    client_label: 'M. Girard',
    statut: 'Actif',
    statut_tone: 'success',
    valeur: 1250000,
    valeur_label: '1 250 k€',
    last_activity_at: '2026-04-19T10:00:00Z',
    last_activity_label: '19 mai · Visite effectuée',
    next_action_label: 'Compte rendu',
    quality_score: 71,
    risk: 'ok',
    risk_label: 'Moyen',
    is_complete: false,
    ecart_avm_sup_5pct_sans_justif: false,
    has_relance: true,
  },
  {
    id: 'p_6',
    type: 'avis_valeur',
    type_label: 'Avis de valeur',
    title: 'Appartement T3',
    adresse: '8 rue Victor Hugo, 44000 Nantes',
    zone_label: 'Nantes',
    collaborator_id: 'u_julien',
    collaborator_label: 'Julien Moreau',
    client_label: 'Mme Petit',
    statut: 'Ouvert',
    statut_tone: 'warning',
    valeur: 295000,
    valeur_label: '295 k€',
    last_activity_at: '2026-04-19T16:05:00Z',
    last_activity_label: 'Hier 16:05 · Relance mail',
    next_action_label: 'AVM générée',
    quality_score: 65,
    risk: 'a_relancer',
    risk_label: 'Moyen',
    is_complete: false,
    ecart_avm_sup_5pct_sans_justif: true,
    has_relance: true,
  },
  {
    id: 'p_7',
    type: 'etude_locative',
    type_label: 'Étude locative',
    title: 'T2 centre-ville',
    adresse: '3 place Carnot, 31000 Toulouse',
    zone_label: 'Toulouse',
    collaborator_id: 'u_camille',
    collaborator_label: 'Camille Durand',
    client_label: 'SCI Carnot',
    statut: 'En cours',
    statut_tone: 'info',
    valeur: 820,
    valeur_label: '820 €/mois',
    last_activity_at: '2026-04-15T18:20:00Z',
    last_activity_label: '15 mai · Comparables',
    next_action_label: 'Envoyer étude',
    quality_score: 82,
    risk: 'ok',
    risk_label: 'Faible',
    is_complete: true,
    ecart_avm_sup_5pct_sans_justif: false,
    has_relance: true,
  },
  {
    id: 'p_8',
    type: 'dossier_invest',
    type_label: 'Dossier investissement',
    title: 'Immeuble Bordeaux',
    adresse: '18 cours de Verdun, 33000 Bordeaux',
    zone_label: 'Bordeaux',
    collaborator_id: 'u_chloe',
    collaborator_label: 'Chloé Bernard',
    client_label: 'Family Office',
    statut: 'En cours',
    statut_tone: 'info',
    valeur: 6.1,
    valeur_label: '6,10 %',
    valeur_unit: 'rendement',
    last_activity_at: '2026-04-16T09:11:00Z',
    last_activity_label: '14 mai 09:11 · Note invest.',
    next_action_label: 'Due diligence',
    quality_score: 90,
    risk: 'ok',
    risk_label: 'Faible',
    is_complete: true,
    ecart_avm_sup_5pct_sans_justif: false,
    has_relance: true,
  },
  {
    id: 'p_9',
    type: 'opportunite',
    type_label: 'Opportunité',
    title: 'Local commercial',
    adresse: '102 av. Jean Jaurès, 59000 Lille',
    zone_label: 'Lille',
    collaborator_id: 'u_sophie',
    collaborator_label: 'Sophie Martin',
    client_label: 'Lead web',
    statut: 'Nouveau',
    statut_tone: 'success',
    valeur: 210000,
    valeur_label: '210 k€',
    last_activity_at: '2026-04-14T09:14:00Z',
    last_activity_label: '14 mai 09:14 · Qualification',
    next_action_label: 'Qualifier',
    quality_score: 48,
    risk: 'bloque',
    risk_label: 'Élevé',
    is_complete: false,
    ecart_avm_sup_5pct_sans_justif: false,
    has_relance: false,
  },
  {
    id: 'p_10',
    type: 'avis_valeur',
    type_label: 'Avis de valeur',
    title: 'Maison familiale',
    adresse: '9 impasse des Lilas, 33000 Charbonnières',
    zone_label: 'Charbonnières',
    collaborator_id: 'u_chloe',
    collaborator_label: 'Chloé Bernard',
    client_label: 'M. Morel',
    statut: 'Ouvert',
    statut_tone: 'warning',
    valeur: 680000,
    valeur_label: '680 k€',
    last_activity_at: '2026-04-14T14:00:00Z',
    last_activity_label: '14 mai · Photos reçues',
    next_action_label: 'Visite conseil',
    quality_score: 72,
    risk: 'a_relancer',
    risk_label: 'Moyen',
    is_complete: false,
    ecart_avm_sup_5pct_sans_justif: true,
    has_relance: false,
  },
];

export const PORTFOLIO_KPIS = {
  biens: 428,
  rapports_en_cours: 86,
  ouverts_sans_relance: 31,
  dossiers: 64,
  rapports_complets_pct: 74,
};

// ── Qualité livrables agrégée (§9.7) ──────────────────────────────────
export const DELIVERABLE_QUALITY_AGGREGATE: DeliverableQualityAggregate = {
  taux_rapports_complets: 74,
  total_deliverables: 78,
  by_criterion: {
    couverture_personnalisee: 96,
    comparables_selectionnes: 82,
    contexte_local_present: 68,
    justification_avm: 91,
    relance_programmee: 43,
    branding_agence: 100,
    photos_bien: 88,
  },
  by_type: [
    { type: 'avis_valeur', count: 37, completeness_pct: 71 },
    { type: 'etude_locative', count: 18, completeness_pct: 83 },
    { type: 'dossier_invest', count: 23, completeness_pct: 69 },
  ],
};

// ── Agenda (§10) ──────────────────────────────────────────────────────
const WEEK_DAYS = ['2026-04-27', '2026-04-28', '2026-04-29', '2026-04-30', '2026-05-01', '2026-05-02', '2026-05-03'];
export const AGENDA_WEEK_DAYS = WEEK_DAYS;
export const AGENDA_WEEK_LABEL = 'Sem. 18 · 27 avr. → 3 mai 2026';

export const AGENDA_EVENTS: AgendaEvent[] = [
  // Sophie — surcharge
  { id: 'ev_1', collaborator_id: 'u_sophie', type: 'rdv_vendeur', label: 'RDV vendeur', zone_label: 'Paris 17e', day: WEEK_DAYS[0], hour: '09:30', tone: 'violet' },
  { id: 'ev_2', collaborator_id: 'u_sophie', type: 'visite', label: 'Visite', zone_label: 'Paris 15e', day: WEEK_DAYS[1], hour: '10:00', tone: 'blue' },
  { id: 'ev_3', collaborator_id: 'u_sophie', type: 'rdv_vendeur', label: 'RDV vendeur', zone_label: 'Boulogne', day: WEEK_DAYS[2], hour: '09:00', tone: 'violet' },
  { id: 'ev_4', collaborator_id: 'u_sophie', type: 'visite', label: 'Visite', zone_label: 'Levallois', day: WEEK_DAYS[3], hour: '11:00', tone: 'blue' },
  { id: 'ev_5', collaborator_id: 'u_sophie', type: 'rdv_vendeur', label: 'RDV vendeur', zone_label: 'Saint-Mandé', day: WEEK_DAYS[4], hour: '10:30', tone: 'violet' },
  { id: 'ev_6', collaborator_id: 'u_sophie', type: 'rdv_estimation', label: 'Estimation', zone_label: 'Paris 16e', day: WEEK_DAYS[0], hour: '14:00', tone: 'orange' },
  { id: 'ev_7', collaborator_id: 'u_sophie', type: 'relance', label: 'Relance vendeurs', day: WEEK_DAYS[1], hour: '13:30', tone: 'slate' },
  { id: 'ev_8', collaborator_id: 'u_sophie', type: 'rdv_estimation', label: 'Estimation', zone_label: 'Neuilly', day: WEEK_DAYS[2], hour: '13:30', tone: 'orange' },
  { id: 'ev_9', collaborator_id: 'u_sophie', type: 'dossier', label: 'Dossier acquéreurs', day: WEEK_DAYS[3], hour: '14:00', tone: 'green' },
  { id: 'ev_10', collaborator_id: 'u_sophie', type: 'signature', label: 'Signature', day: WEEK_DAYS[4], hour: '15:00', tone: 'violet' },

  // Marc — chargé
  { id: 'ev_11', collaborator_id: 'u_marc', type: 'rdv_vendeur', label: 'RDV vendeur', zone_label: 'Lyon 6e', day: WEEK_DAYS[0], hour: '11:00', tone: 'violet' },
  { id: 'ev_12', collaborator_id: 'u_marc', type: 'rdv_estimation', label: 'Estimation', zone_label: 'Lyon 3e', day: WEEK_DAYS[1], hour: '09:30', tone: 'orange' },
  { id: 'ev_13', collaborator_id: 'u_marc', type: 'visite', label: 'Visite', zone_label: 'Écully', day: WEEK_DAYS[2], hour: '10:30', tone: 'blue' },
  { id: 'ev_14', collaborator_id: 'u_marc', type: 'visite', label: 'Visite', zone_label: 'Tassin', day: WEEK_DAYS[3], hour: '09:15', tone: 'blue' },
  { id: 'ev_15', collaborator_id: 'u_marc', type: 'rdv_vendeur', label: 'RDV vendeur', zone_label: 'Lyon 7e', day: WEEK_DAYS[4], hour: '11:00', tone: 'violet' },
  { id: 'ev_16', collaborator_id: 'u_marc', type: 'appel', label: 'Appels acquéreurs', day: WEEK_DAYS[0], hour: '16:00', tone: 'slate' },
  { id: 'ev_17', collaborator_id: 'u_marc', type: 'rdv_estimation', label: 'Estimation', zone_label: 'Villeurbanne', day: WEEK_DAYS[1], hour: '14:30', tone: 'orange' },
  { id: 'ev_18', collaborator_id: 'u_marc', type: 'dossier', label: 'Dossier constitution', day: WEEK_DAYS[2], hour: '15:30', tone: 'green' },
  { id: 'ev_19', collaborator_id: 'u_marc', type: 'relance', label: 'Relance vendeurs', day: WEEK_DAYS[3], hour: '15:30', tone: 'slate' },
  { id: 'ev_20', collaborator_id: 'u_marc', type: 'appel', label: 'Appels prospects', day: WEEK_DAYS[4], hour: '16:00', tone: 'slate' },

  // Camille — normal
  { id: 'ev_21', collaborator_id: 'u_camille', type: 'dossier', label: 'Dossier signature', zone_label: 'Marseille', day: WEEK_DAYS[0], hour: '14:00', tone: 'violet' },
  { id: 'ev_22', collaborator_id: 'u_camille', type: 'visite', label: 'Visite', zone_label: 'Marseille 8e', day: WEEK_DAYS[1], hour: '10:00', tone: 'blue' },
  { id: 'ev_23', collaborator_id: 'u_camille', type: 'rdv_vendeur', label: 'RDV vendeur', zone_label: 'Marseille 7e', day: WEEK_DAYS[2], hour: '11:30', tone: 'violet' },
  { id: 'ev_24', collaborator_id: 'u_camille', type: 'visite', label: 'Visite', zone_label: 'Aubagne', day: WEEK_DAYS[3], hour: '10:30', tone: 'blue' },
  { id: 'ev_25', collaborator_id: 'u_camille', type: 'dossier', label: 'Dossier constitution', day: WEEK_DAYS[4], hour: '14:00', tone: 'green' },
  { id: 'ev_26', collaborator_id: 'u_camille', type: 'relance', label: 'Relance acquéreurs', day: WEEK_DAYS[0], hour: '16:30', tone: 'slate' },
  { id: 'ev_27', collaborator_id: 'u_camille', type: 'appel', label: 'Appels prospects', day: WEEK_DAYS[1], hour: '15:30', tone: 'slate' },
  { id: 'ev_28', collaborator_id: 'u_camille', type: 'rdv_estimation', label: 'Estimation', zone_label: 'Aix-en-P.', day: WEEK_DAYS[2], hour: '14:00', tone: 'orange' },
  { id: 'ev_29', collaborator_id: 'u_camille', type: 'relance', label: 'Relance vendeurs', day: WEEK_DAYS[3], hour: '15:30', tone: 'slate' },

  // Thomas — disponible
  { id: 'ev_30', collaborator_id: 'u_thomas', type: 'appel', label: 'Appels prospects', day: WEEK_DAYS[0], hour: '15:00', tone: 'slate' },
  { id: 'ev_31', collaborator_id: 'u_thomas', type: 'relance', label: 'Relance vendeurs', day: WEEK_DAYS[1], hour: '13:30', tone: 'slate' },
  { id: 'ev_32', collaborator_id: 'u_thomas', type: 'appel', label: 'Appels prospects', day: WEEK_DAYS[2], hour: '16:00', tone: 'slate' },
  { id: 'ev_33', collaborator_id: 'u_thomas', type: 'relance', label: 'Relance vendeurs', day: WEEK_DAYS[3], hour: '14:00', tone: 'slate' },
  { id: 'ev_34', collaborator_id: 'u_thomas', type: 'appel', label: 'Appels prospects', day: WEEK_DAYS[4], hour: '15:00', tone: 'slate' },
];

export const AGENDA_KPIS = {
  rdv_semaine: 126,
  rdv_semaine_delta: '+9 % vs 5-11 mai',
  actions_retard: 86,
  actions_retard_delta: '+18 % vs 5-11 mai',
  relances_critiques: 23,
  relances_critiques_delta: '+7 % vs 5-11 mai',
  surcharges: 2,
  surcharges_delta: '+1 vs 5-11 mai',
  creneaux_dispo: 58,
  creneaux_dispo_delta: '+15 % vs 5-11 mai',
};

export const AGENDA_OVERDUE: AgendaOverdueAction[] = [
  {
    id: 'ov_1',
    label: 'Relance vendeur — M. Bernard',
    collaborator_id: 'u_sophie',
    collaborator_label: 'Sophie Martin',
    retard_days: 6,
    priority: 'haute',
    cta_label: 'Réassigner',
  },
  {
    id: 'ov_2',
    label: 'Relance acquéreur — Mme Lefèvre',
    collaborator_id: 'u_marc',
    collaborator_label: 'Marc Lemoine',
    retard_days: 5,
    priority: 'haute',
    cta_label: 'Assigner',
  },
  {
    id: 'ov_3',
    label: 'Envoi estimation T3',
    collaborator_id: 'u_camille',
    collaborator_label: 'Camille Durand',
    retard_days: 7,
    priority: 'moyenne',
    cta_label: 'Voir signal',
  },
];

export const REBALANCING: RebalancingSuggestion[] = [
  {
    id: 'rb_1',
    type: 'charge',
    title: 'Réassigner 8 relances à Thomas Morel',
    explanation: 'Il a 26 pts de charge disponibles cette semaine.',
    cta_label: 'Réassigner',
    tone: 'violet',
  },
  {
    id: 'rb_2',
    type: 'creneaux',
    title: 'Répartir les estimations entre Camille et Marc',
    explanation: 'Charge optimisée sur jeudi et vendredi.',
    cta_label: 'Rééquilibrer',
    tone: 'blue',
  },
  {
    id: 'rb_3',
    type: 'leads_unassigned',
    title: 'Distribuer 12 nouveaux leads à Thomas Morel',
    explanation: 'Capacité disponible identifiée.',
    cta_label: 'Distribuer',
    tone: 'orange',
  },
];

// ── Absences (§10.8) ──────────────────────────────────────────────────
export const ABSENCES: Absence[] = [
  {
    absence_id: 'abs_1',
    collaborator_id: 'u_sophie',
    collaborator_label: 'Sophie Martin',
    type: 'conges',
    period_start: '2026-05-11',
    period_end: '2026-05-18',
    note: 'Congés planifiés',
    created_by: 'u_sophie',
    created_at: '2026-04-02T10:00:00Z',
  },
  {
    absence_id: 'abs_2',
    collaborator_id: 'u_marc',
    collaborator_label: 'Marc Lemoine',
    type: 'formation',
    period_start: '2026-04-30',
    period_end: '2026-04-30',
    note: 'Formation estimation avancée',
    created_by: 'u_sophie',
    created_at: '2026-04-15T09:00:00Z',
  },
  {
    absence_id: 'abs_3',
    collaborator_id: 'u_thomas',
    collaborator_label: 'Thomas Morel',
    type: 'maladie',
    period_start: '2026-04-25',
    period_end: '2026-04-26',
    created_by: 'u_thomas',
    created_at: '2026-04-24T07:30:00Z',
  },
];

// ── Workload snapshots ────────────────────────────────────────────────
export const WORKLOAD_SNAPSHOTS: WorkloadSnapshot[] = COLLABORATEURS.map(c => ({
  collaborator_id: c.user_id,
  period_start: '2026-04-21',
  period_end: '2026-04-27',
  actions_open: c.leads_actifs,
  actions_overdue: c.actions_retard,
  rdv_count: c.rdv_semaine,
  visits_count: Math.floor(c.rdv_semaine / 2),
  leads_active: c.leads_actifs,
  dossiers_active: Math.max(0, Math.floor(c.mandats / 2)),
  rapports_a_relancer: c.rapports_a_relancer,
  opportunites_a_qualifier: Math.floor(c.signaux_non_traites / 2),
  capacity_weekly_hours: c.capacity_weekly_hours,
  workload_score: c.workload_score,
  status: c.workload_status,
}));

// ── Performance ───────────────────────────────────────────────────────
export const FUNNEL_STAGES: FunnelStage[] = [
  { key: 'leads_entrants', label: 'Leads entrants', value: 1248, pct_from_top: 100, pct_from_previous: 100 },
  { key: 'qualifies', label: 'Qualifiés', value: 474, pct_from_top: 38, pct_from_previous: 38 },
  { key: 'rdv', label: 'RDV réalisés', value: 199, pct_from_top: 16, pct_from_previous: 42 },
  { key: 'estimations', label: 'Estimations', value: 126, pct_from_top: 10, pct_from_previous: 63 },
  { key: 'rapports_envoyes', label: 'Rapports envoyés', value: 68, pct_from_top: 5, pct_from_previous: 54 },
  { key: 'mandats', label: 'Mandats signés', value: 26, pct_from_top: 2.1, pct_from_previous: 21 },
  { key: 'signatures', label: 'Signatures', value: 18, pct_from_top: 1.4, pct_from_previous: 69 },
];

export const FUNNEL_KPIS: AdoptionMetric[] = [
  { id: 'leads_entrants', label: 'Leads entrants', value: '1 248', delta: '+12 % vs 1-30 avr.', trend: 'up' },
  { id: 'taux_qualif', label: 'Taux qualification', value: '38 %', delta: '+3 pts vs 1-30 avr.', trend: 'up' },
  { id: 'taux_rdv', label: 'Taux RDV', value: '42 %', delta: '-2 pts vs 1-30 avr.', trend: 'down' },
  { id: 'taux_estim', label: 'Taux estimation', value: '63 %', delta: '+5 pts vs 1-30 avr.', trend: 'up' },
  { id: 'taux_rapport', label: 'Taux rapport envoyé', value: '54 %', delta: '+4 pts vs 1-30 avr.', trend: 'up' },
  { id: 'taux_mandat', label: 'Taux mandat', value: '21 %', delta: '+2 pts vs 1-30 avr.', trend: 'up' },
  { id: 'delai_mandat', label: 'Délai lead → mandat', value: '26 j', delta: '-4 j vs 1-30 avr.', trend: 'up' },
];

export const SOURCE_CONVERSION: SourceConversionRow[] = [
  { source: 'Widget estimation', leads: 452, qualif_pct: 41, rapports: 28, mandats: 12, ca_genere: 620000, delai_moyen_jours: 16 },
  { source: 'Prospection DPE', leads: 268, qualif_pct: 37, rapports: 17, mandats: 6, ca_genere: 310000, delai_moyen_jours: 22 },
  { source: 'Prospection DVF', leads: 214, qualif_pct: 33, rapports: 11, mandats: 4, ca_genere: 210000, delai_moyen_jours: 19 },
  { source: 'Annonce', leads: 184, qualif_pct: 34, rapports: 5, mandats: 2, ca_genere: 155000, delai_moyen_jours: 25 },
  { source: 'Ancien client', leads: 130, qualif_pct: 58, rapports: 9, mandats: 4, ca_genere: 285000, delai_moyen_jours: 12 },
];

export const BUSINESS_KPIS: AdoptionMetric[] = [
  { id: 'ca_realise', label: 'CA réalisé', value: '1,42 M€', delta: '+18 % vs 1-30 avr.', trend: 'up' },
  { id: 'ca_pipe', label: 'CA pipe pondéré', value: '1,82 M€', delta: '+15 % vs 1-30 avr.', trend: 'up' },
  { id: 'mandats_signes', label: 'Mandats signés', value: '26', delta: '+21 % vs 1-30 avr.', trend: 'up' },
  { id: 'taux_exclus', label: 'Taux exclusivité', value: '69 %', delta: '+6 pts vs 1-30 avr.', trend: 'up' },
  { id: 'commission_moy', label: 'Commission moyenne', value: '54,6 k€', delta: '+4,1 k€ vs 1-30 avr.', trend: 'up' },
];

export const BUSINESS_COLLAB_ROWS: BusinessCollaboratorRow[] = [
  { collaborator_id: 'u_sophie', collaborator_label: 'Sophie Martin', ca_realise: 624000, ca_pipe: 840000, mandats_signes: 9, taux_exclusivite_pct: 60, commission_moyenne: 69300 },
  { collaborator_id: 'u_camille', collaborator_label: 'Camille Durand', ca_realise: 389000, ca_pipe: 512400, mandats_signes: 7, taux_exclusivite_pct: 71, commission_moyenne: 55570 },
  { collaborator_id: 'u_marc', collaborator_label: 'Marc Lemoine', ca_realise: 182000, ca_pipe: 425000, mandats_signes: 4, taux_exclusivite_pct: 50, commission_moyenne: 45500 },
  { collaborator_id: 'u_chloe', collaborator_label: 'Chloé Bernard', ca_realise: 124000, ca_pipe: 230000, mandats_signes: 3, taux_exclusivite_pct: 67, commission_moyenne: 41300 },
  { collaborator_id: 'u_laura', collaborator_label: 'Laura Simon', ca_realise: 72000, ca_pipe: 185000, mandats_signes: 2, taux_exclusivite_pct: 50, commission_moyenne: 36000 },
  { collaborator_id: 'u_thomas', collaborator_label: 'Thomas Morel', ca_realise: 29000, ca_pipe: 62000, mandats_signes: 1, taux_exclusivite_pct: 100, commission_moyenne: 29000 },
];

export const CA_MONTHLY: CaMonthlyPoint[] = [
  { label: 'Nov.', ca_realise: 880, mandats: 3 },
  { label: 'Déc.', ca_realise: 560, mandats: 2 },
  { label: 'Janv.', ca_realise: 1010, mandats: 4 },
  { label: 'Févr.', ca_realise: 1180, mandats: 5 },
  { label: 'Mars', ca_realise: 1250, mandats: 6 },
  { label: 'Avr.', ca_realise: 1420, mandats: 7 },
];

export const MANDATS_BY_STATUS: MandatsStatusSlice[] = [
  { label: 'Signés', value: 26, pct: 33, tone: 'violet' },
  { label: 'En négociation', value: 32, pct: 41, tone: 'blue' },
  { label: 'En rendez-vous', value: 14, pct: 18, tone: 'orange' },
  { label: 'En estimation', value: 6, pct: 8, tone: 'slate' },
];

export const MANDATS_TOTAL = 78;

export const MARCHE_ZONES_PERF: MarcheZone[] = [
  {
    zone_id: 'z_p15',
    slug: 'paris-15',
    label: 'Paris 15e',
    volume_dvf_12m: 842,
    leads_equipe: 48,
    mandats: 12,
    part_captee_pct: 1.4,
    part_moyenne_marche_pct: 2.0,
    potentiel_ca: 2560000,
    ca_realise_12m: 640000,
    tension_score: 82,
    signal_label: 'Sous-exploité',
    signal_tone: 'orange',
  },
  {
    zone_id: 'z_bgn',
    slug: 'boulogne',
    label: 'Boulogne-Billancourt',
    volume_dvf_12m: 488,
    leads_equipe: 31,
    mandats: 9,
    part_captee_pct: 1.8,
    part_moyenne_marche_pct: 2.2,
    potentiel_ca: 1200000,
    ca_realise_12m: 360000,
    tension_score: 71,
    signal_label: 'Bon niveau',
    signal_tone: 'green',
  },
  {
    zone_id: 'z_issy',
    slug: 'issy',
    label: 'Issy-les-Moulineaux',
    volume_dvf_12m: 392,
    leads_equipe: 12,
    mandats: 2,
    part_captee_pct: 0.5,
    part_moyenne_marche_pct: 1.4,
    potentiel_ca: 1680000,
    ca_realise_12m: 220000,
    tension_score: 68,
    signal_label: 'À attaquer',
    signal_tone: 'red',
  },
  {
    zone_id: 'z_vanv',
    slug: 'vanves',
    label: 'Vanves',
    volume_dvf_12m: 234,
    leads_equipe: 8,
    mandats: 1,
    part_captee_pct: 0.4,
    part_moyenne_marche_pct: 1.1,
    potentiel_ca: 840000,
    ca_realise_12m: 112000,
    tension_score: 58,
    signal_label: 'À attaquer',
    signal_tone: 'red',
  },
];

export const MARCHE_KPIS = {
  marche_adressable: 8.6,
  part_captee_pct: 16.5,
  potentiel_ca_restant: 7.2,
  zones_sous_exploitees: 3,
  segments_a_attaquer: 2,
};

export const HYPOTHESES_DEFAULT: Hypotheses = {
  taux_commission_pct: 3.8,
  panier_moyen: 520000,
  taux_mandat_atteignable_pct: 4,
  part_objectif_pct: 2,
  periode_reference_mois: 12,
};

export const ADOPTION_COLLAB_ROWS: AdoptionCollaboratorRow[] = [
  {
    collaborator_id: 'u_sophie',
    collaborator_label: 'Sophie Martin',
    estimations: 18,
    rapports_envoyes: 11,
    rapports_ouverts: 7,
    relances: 4,
    mandats: 9,
    signal_label: 'Très bon post-rapport',
    signal_tone: 'green',
  },
  {
    collaborator_id: 'u_marc',
    collaborator_label: 'Marc Lemoine',
    estimations: 12,
    rapports_envoyes: 2,
    rapports_ouverts: 1,
    relances: 0,
    mandats: 4,
    signal_label: 'Coaching AdV',
    signal_tone: 'orange',
  },
  {
    collaborator_id: 'u_camille',
    collaborator_label: 'Camille Durand',
    estimations: 18,
    rapports_envoyes: 13,
    rapports_ouverts: 9,
    relances: 7,
    mandats: 8,
    signal_label: 'Forte adoption',
    signal_tone: 'violet',
  },
  {
    collaborator_id: 'u_thomas',
    collaborator_label: 'Thomas Morel',
    estimations: 8,
    rapports_envoyes: 4,
    rapports_ouverts: 3,
    relances: 1,
    mandats: 2,
    signal_label: 'Potentiel à charger',
    signal_tone: 'slate',
  },
  {
    collaborator_id: 'u_chloe',
    collaborator_label: 'Chloé Bernard',
    estimations: 7,
    rapports_envoyes: 4,
    rapports_ouverts: 3,
    relances: 1,
    mandats: 1,
    signal_label: 'À accompagner',
    signal_tone: 'slate',
  },
];

export const DEFAULT_OBJECTIVE: TeamObjective = {
  objective_id: 'obj_q2_2026',
  organization_id: ORG,
  period: 'quarter',
  period_label: 'Q2 2026',
  period_start: '2026-04-01',
  period_end: '2026-06-30',
  ca_target: 250000,
  ca_pipe_target: 500000,
  mandates_target: 24,
  exclusive_mandates_target: 15,
  avis_valeur_target: 45,
  etudes_locatives_target: 25,
  rdv_target: 120,
  created_at: '2026-04-01T00:00:00Z',
  updated_at: '2026-04-20T00:00:00Z',
};

export const OBJECTIVE_PROGRESS = {
  ca: { value: 174000, target: 250000 },
  mandats: { value: 15, target: 24 },
  mandats_exclusifs: { value: 10, target: 15 },
  avis: { value: 37, target: 45 },
  etudes: { value: 18, target: 25 },
};

// ── RDV brief (§10.9) ─────────────────────────────────────────────────
export const RDV_BRIEF_DEMO: RdvBrief = {
  rdv_id: 'rdv_1234',
  date: '2026-04-25T10:00:00Z',
  type_rdv: 'vendeur',
  client_label: 'Mme Bertrand',
  collaborator_label: 'Sophie Martin',
  bien_adresse: '16 rue du Hameau, 75015 Paris',
  bien_type: 'Appartement T2',
  bien_surface: 42,
  bien_pieces: 2,
  bien_annee: 2010,
  bien_dpe: 'D',
  estimation_min: 420000,
  estimation_median: 432000,
  estimation_max: 445000,
  last_interaction_type: 'Appel',
  last_interaction_by: 'Sophie Martin',
  last_interaction_at: '2026-04-18T10:15:00Z',
  last_interaction_summary: 'Vendeuse hésitante, craint de brader.',
  rapport_type: 'Avis de valeur',
  rapport_sent_at: '2026-04-20T09:00:00Z',
  rapport_opened_count: 3,
  rapport_last_opened_at: '2026-04-23T18:00:00Z',
  points_defendus: ['Prix au m² zone', 'Délai vente 62 j'],
  points_a_defendre: [
    'Tension Paris 15e : 82/100',
    'Comparables vendus -5 % en 6 mois (vs -12 % attendu)',
    'Délai moyen vente zone : 62 jours',
  ],
  prix_m2_median: 10450,
  evolution_12m: -3.2,
  actions_recommandees: [
    'Préparer 3 comparables récents vendus',
    'Ouvrir la page Observatoire avant le RDV',
  ],
  timeline: [
    { id: 't1', date: '2026-04-12T14:00:00Z', type: 'note', label: 'Lead créé via widget estimation' },
    { id: 't2', date: '2026-04-14T09:30:00Z', type: 'appel', label: 'Premier contact téléphonique', by: 'Sophie Martin' },
    { id: 't3', date: '2026-04-18T10:15:00Z', type: 'appel', label: 'Appel qualification', by: 'Sophie Martin' },
    { id: 't4', date: '2026-04-20T09:00:00Z', type: 'email', label: 'Avis de valeur envoyé', by: 'Sophie Martin' },
    { id: 't5', date: '2026-04-21T11:20:00Z', type: 'ouverture_rapport', label: 'Rapport ouvert (1ʳᵉ fois)' },
    { id: 't6', date: '2026-04-22T14:05:00Z', type: 'ouverture_rapport', label: 'Rapport ouvert (2ᵉ fois)' },
    { id: 't7', date: '2026-04-23T18:00:00Z', type: 'ouverture_rapport', label: 'Rapport ouvert (3ᵉ fois)' },
  ],
};

// ── Quality entries détaillées (§9.7) ─────────────────────────────────
export const DELIVERABLE_QUALITY_DETAIL: DeliverableQuality[] = [
  {
    deliverable_id: 'rap_001',
    deliverable_type: 'avis_valeur',
    collaborator_id: 'u_chloe',
    criteria: {
      couverture_personnalisee: true,
      comparables_selectionnes: true,
      contexte_local_present: false,
      justification_avm: true,
      relance_programmee: false,
      branding_agence: true,
      photos_bien: true,
    },
    is_complete: false,
    completeness_score: 71,
    computed_at: '2026-04-20T10:00:00Z',
  },
  {
    deliverable_id: 'rap_002',
    deliverable_type: 'avis_valeur',
    collaborator_id: 'u_sophie',
    criteria: {
      couverture_personnalisee: true,
      comparables_selectionnes: true,
      contexte_local_present: true,
      justification_avm: true,
      relance_programmee: true,
      branding_agence: true,
      photos_bien: true,
    },
    is_complete: true,
    completeness_score: 100,
    computed_at: '2026-04-20T10:00:00Z',
  },
];
