import { ProjetInvestisseur } from '../types';

export const MOCK_PROJETS: ProjetInvestisseur[] = [
  {
    project_id: 'proj_paris15',
    name: 'Paris 15e — Rendement locatif',
    owner_user_id: 'user_me',
    porteur_type: 'self',
    target_zones: ['Paris 15e', 'Paris 14e'],
    budget_min: 400000,
    budget_max: 600000,
    down_payment_target: 120000,
    strategy_type: 'rendement',
    yield_target: 4.5,
    cashflow_target: 0,
    holding_period: 10,
    preferred_property_types: ['t1', 't2', 't3', 'studio'],
    occupancy_mode_target: 'meuble',
    works_tolerance: 'legers',
    risk_tolerance: 'equilibre',
    taux_effort_reference: 0.33,
    tmi: 30,
    nombre_parts: 2,
    profil_locataire_cible: {
      type_dominant: 'jeune_actif',
      types_secondaires: ['couple_sans_enfant', 'etudiant'],
      profondeur_demande: 'forte',
      revenu_indicatif_requis: 2790,
      taux_effort_reference: 0.33,
      part_population_eligible: 0.28,
      niveau_confiance: 'eleve',
      sources: ['Filosofi IRIS', 'Structure ménages INSEE'],
    },
    notes: '',
    status: 'actif',
    created_at: '2026-01-15T09:00:00Z',
    updated_at: '2026-04-20T14:30:00Z',
    nb_opportunites: 264,
    progression_pct: 40,
  },
  {
    project_id: 'proj_lyon3',
    name: 'Lyon 3e — Cash-flow positif',
    owner_user_id: 'user_me',
    porteur_type: 'self',
    target_zones: ['Lyon 3e', 'Villeurbanne'],
    budget_min: 150000,
    budget_max: 250000,
    down_payment_target: 50000,
    strategy_type: 'cashflow',
    yield_target: 5.5,
    cashflow_target: 200,
    holding_period: 15,
    preferred_property_types: ['studio', 't1', 't2'],
    occupancy_mode_target: 'colocation',
    works_tolerance: 'moyens',
    risk_tolerance: 'offensif',
    taux_effort_reference: 0.33,
    tmi: 30,
    nombre_parts: 2,
    profil_locataire_cible: {
      type_dominant: 'etudiant',
      types_secondaires: ['jeune_actif'],
      profondeur_demande: 'forte',
      revenu_indicatif_requis: 1650,
      taux_effort_reference: 0.33,
      part_population_eligible: 0.42,
      niveau_confiance: 'eleve',
      sources: ['Filosofi IRIS', 'INSEE'],
    },
    notes: '',
    status: 'pause',
    created_at: '2026-02-10T09:00:00Z',
    updated_at: '2026-03-22T14:30:00Z',
    nb_opportunites: 87,
    progression_pct: 25,
  },
  {
    project_id: 'proj_grenoble',
    name: 'Grenoble — Patrimonial long terme',
    owner_user_id: 'user_me',
    porteur_type: 'self',
    target_zones: ['Grenoble', 'Échirolles'],
    budget_min: 180000,
    budget_max: 280000,
    down_payment_target: 60000,
    strategy_type: 'patrimonial',
    yield_target: 4,
    cashflow_target: 0,
    holding_period: 20,
    preferred_property_types: ['t2', 't3'],
    occupancy_mode_target: 'nu',
    works_tolerance: 'legers',
    risk_tolerance: 'prudent',
    taux_effort_reference: 0.33,
    tmi: 30,
    nombre_parts: 2,
    profil_locataire_cible: {
      type_dominant: 'couple_sans_enfant',
      types_secondaires: ['famille', 'jeune_actif'],
      profondeur_demande: 'correcte',
      revenu_indicatif_requis: 2100,
      taux_effort_reference: 0.33,
      part_population_eligible: 0.35,
      niveau_confiance: 'moyen',
      sources: ['Filosofi IRIS'],
    },
    notes: '',
    status: 'actif',
    created_at: '2026-03-01T09:00:00Z',
    updated_at: '2026-04-18T14:30:00Z',
    nb_opportunites: 42,
    progression_pct: 15,
  },
];

export const ACTIVE_PROJECT_ID_DEFAULT = 'proj_paris15';
