import { Ville } from '../types';

export const MOCK_VILLES: Ville[] = [
  {
    id: 'paris15',
    nom: 'Paris 15e',
    code_postal: '75015',
    prix_m2_median: 9450,
    loyer_m2_median: 38.1,
    rendement_median: 4.8,
    vacance_pct: 2.1,
    tension: 'tres_elevee',
    profondeur: 'forte',
    profil_dominant: 'jeune_actif',
    evol_prix_5a: 12,
    evol_loyers_5a: 8,
    avis_note: 4.2,
    signal_plu: 'favorable',
    part_csp_plus: 42,
    budget_min_compatible: 420000,
  },
  {
    id: 'paris14',
    nom: 'Paris 14e',
    code_postal: '75014',
    distance: '2 km',
    prix_m2_median: 9100,
    loyer_m2_median: 36.5,
    rendement_median: 4.6,
    vacance_pct: 2.3,
    tension: 'tres_elevee',
    profondeur: 'forte',
    profil_dominant: 'jeune_actif',
    evol_prix_5a: 10,
    evol_loyers_5a: 7,
    avis_note: 4.3,
    signal_plu: 'favorable',
    part_csp_plus: 40,
    budget_min_compatible: 400000,
  },
  {
    id: 'lyon3',
    nom: 'Lyon 3e',
    code_postal: '69003',
    distance: '100 km',
    prix_m2_median: 4150,
    loyer_m2_median: 17.2,
    rendement_median: 4.7,
    vacance_pct: 1.8,
    tension: 'tres_elevee',
    profondeur: 'forte',
    profil_dominant: 'jeune_actif',
    evol_prix_5a: 18,
    evol_loyers_5a: 12,
    avis_note: 4.2,
    signal_plu: 'favorable',
    part_csp_plus: 42,
    budget_min_compatible: 250000,
  },
  {
    id: 'grenoble3',
    nom: 'Grenoble 3e',
    code_postal: '38100',
    distance: '110 km',
    prix_m2_median: 2890,
    loyer_m2_median: 13.8,
    rendement_median: 5.7,
    vacance_pct: 2.5,
    tension: 'elevee',
    profondeur: 'correcte',
    profil_dominant: 'etudiant',
    evol_prix_5a: 9,
    evol_loyers_5a: 10,
    avis_note: 4.5,
    signal_plu: 'favorable',
    part_csp_plus: 38,
    budget_min_compatible: 160000,
  },
  {
    id: 'saint-etienne',
    nom: 'Saint-Étienne Centre',
    code_postal: '42000',
    distance: '60 km de Lyon',
    prix_m2_median: 1680,
    loyer_m2_median: 11.5,
    rendement_median: 8.2,
    vacance_pct: 4.2,
    tension: 'moyenne',
    profondeur: 'etroite',
    profil_dominant: 'mixte',
    evol_prix_5a: 4,
    evol_loyers_5a: 6,
    avis_note: 3.1,
    signal_plu: 'neutre',
    part_csp_plus: 28,
    budget_min_compatible: 90000,
  },
  {
    id: 'villeurbanne',
    nom: 'Villeurbanne',
    code_postal: '69100',
    distance: '5 km de Lyon',
    prix_m2_median: 3850,
    loyer_m2_median: 16.2,
    rendement_median: 5.0,
    vacance_pct: 2.0,
    tension: 'elevee',
    profondeur: 'forte',
    profil_dominant: 'jeune_actif',
    evol_prix_5a: 15,
    evol_loyers_5a: 11,
    avis_note: 4.0,
    signal_plu: 'favorable',
    part_csp_plus: 36,
    budget_min_compatible: 230000,
  },
  {
    id: 'levallois',
    nom: 'Levallois-Perret',
    code_postal: '92300',
    distance: '6 km',
    prix_m2_median: 9800,
    loyer_m2_median: 30.5,
    rendement_median: 4.7,
    vacance_pct: 2.0,
    tension: 'elevee',
    profondeur: 'forte',
    profil_dominant: 'couple_sans_enfant',
    evol_prix_5a: 11,
    evol_loyers_5a: 7,
    avis_note: 4.1,
    signal_plu: 'favorable',
    part_csp_plus: 45,
    budget_min_compatible: 380000,
  },
];
