package com.apeiron.immoxperts.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AdresseLocalAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdresseLocalAllPropertiesEquals(AdresseLocal expected, AdresseLocal actual) {
        assertAdresseLocalAutoGeneratedPropertiesEquals(expected, actual);
        assertAdresseLocalAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdresseLocalAllUpdatablePropertiesEquals(AdresseLocal expected, AdresseLocal actual) {
        assertAdresseLocalUpdatableFieldsEquals(expected, actual);
        assertAdresseLocalUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdresseLocalAutoGeneratedPropertiesEquals(AdresseLocal expected, AdresseLocal actual) {
        assertThat(actual)
            .as("Verify AdresseLocal auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdresseLocalUpdatableFieldsEquals(AdresseLocal expected, AdresseLocal actual) {
        assertThat(actual)
            .as("Verify AdresseLocal relevant properties")
            .satisfies(a -> assertThat(a.getCoddep()).as("check coddep").isEqualTo(expected.getCoddep()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdresseLocalUpdatableRelationshipsEquals(AdresseLocal expected, AdresseLocal actual) {
        assertThat(actual)
            .as("Verify AdresseLocal relationships")
            .satisfies(a -> assertThat(a.getMutation()).as("check mutation").isEqualTo(expected.getMutation()))
            .satisfies(a -> assertThat(a.getAdresse()).as("check adresse").isEqualTo(expected.getAdresse()));
    }
}
