package com.apeiron.immoxperts.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AdresseDispoparcAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdresseDispoparcAllPropertiesEquals(AdresseDispoparc expected, AdresseDispoparc actual) {
        assertAdresseDispoparcAutoGeneratedPropertiesEquals(expected, actual);
        assertAdresseDispoparcAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdresseDispoparcAllUpdatablePropertiesEquals(AdresseDispoparc expected, AdresseDispoparc actual) {
        assertAdresseDispoparcUpdatableFieldsEquals(expected, actual);
        assertAdresseDispoparcUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdresseDispoparcAutoGeneratedPropertiesEquals(AdresseDispoparc expected, AdresseDispoparc actual) {
        assertThat(actual)
            .as("Verify AdresseDispoparc auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdresseDispoparcUpdatableFieldsEquals(AdresseDispoparc expected, AdresseDispoparc actual) {
        // empty method

    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdresseDispoparcUpdatableRelationshipsEquals(AdresseDispoparc expected, AdresseDispoparc actual) {
        assertThat(actual)
            .as("Verify AdresseDispoparc relationships")
            .satisfies(a -> assertThat(a.getMutation()).as("check mutation").isEqualTo(expected.getMutation()))
            .satisfies(a -> assertThat(a.getAdresse()).as("check adresse").isEqualTo(expected.getAdresse()));
    }
}
