package com.apeiron.immoxperts.domain;

import static com.apeiron.immoxperts.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class LotAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLotAllPropertiesEquals(Lot expected, Lot actual) {
        assertLotAutoGeneratedPropertiesEquals(expected, actual);
        assertLotAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLotAllUpdatablePropertiesEquals(Lot expected, Lot actual) {
        assertLotUpdatableFieldsEquals(expected, actual);
        assertLotUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLotAutoGeneratedPropertiesEquals(Lot expected, Lot actual) {
        assertThat(actual)
            .as("Verify Lot auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLotUpdatableFieldsEquals(Lot expected, Lot actual) {
        assertThat(actual)
            .as("Verify Lot relevant properties")
            .satisfies(a -> assertThat(a.getIddispolot()).as("check iddispolot").isEqualTo(expected.getIddispolot()))
            .satisfies(a ->
                assertThat(a.getScarrez()).as("check scarrez").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getScarrez())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLotUpdatableRelationshipsEquals(Lot expected, Lot actual) {
        // empty method
    }
}
